### ISSUE TITLE
[Bug]:     Error: failed to read schema for module.kube-hetzner.module.agents.hcloud_server.server

### ISSUE THREAD

**Issue by grig0701** [kube-hetzner/terraform-hcloud-kube-hetzner#1007]
### Description

Good afternoon, trying to fix https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/980, I decided to change in nginx service ` load-balancer.hetzner.cloud/uses-proxyprotocol: 'false' ` for a test , not having a successful result, this specification was changed back. 

After that I tried to run the terraform plan and I got an error

```Error: failed to read schema for module.kube-hetzner.module.agents.hcloud_server.server in registry.terraform.io/hetznercloud/hcloud: failed to retrieve schema from provider "registry.terraform.io/hetznercloud/hcloud": Invalid Provider Server Combination: The combined provider has differing provider schema implementations across providers. Provider schemas must be identical across providers. This is always an issue in the provider implementation and should be reported to the provider developers. Provider schema difference:   &tfprotov6.Schema{    Version: 0,    Block: &tfprotov6.SchemaBlock{    Version: 0,    Attributes: []*tfprotov6.SchemaAttribute{    &{Name: "endpoint", Type: s"tftypes.String", Description: "The Hetzner Cloud API endpoint, can be used to override the defa"..., Optional: true, ...},    &{Name: "poll_interval", Type: s"tftypes.String", Description: "The interval at which actions are polled by the client. Default "..., Optional: true, ...},    &{    ... // 2 identical fields    NestedType: nil,    Description: "The Hetzner Cloud API token, can also be specified with the HCLO"..., -  Required: true, +  Required: false, -  Optional: false, +  Optional: true,    Computed: false,    Sensitive: true,    ... // 2 identical fields    },    },    BlockTypes: nil,    Description: "",    ... // 2 identical fields    },   }```

Could this be due to a specification change?

Any chance to fix this? Can you please help me understand the problem, how could this happen, where should I look to understand this?

### Kube.tf file

```terraform
module "kube-hetzner" {


  providers = {
    hcloud = hcloud
  }
  extra_firewall_rules = [
    {
      description     = "Access to MySQL cluster"
      direction       = "out"
      protocol        = "tcp"
      port            = "3306"
      source_ips      = [] # Won't be used for this rule
      destination_ips = ["0.0.0.0/0", "::/0"]
    },
    {
      description     = "Access to redis"
      direction       = "in"
      protocol        = "tcp"
      port            = "6379"
      source_ips      = ["0.0.0.0/0", "::/0"] # Won't be used for this rule
      destination_ips = []
    },
    {
      description     = "Access to redis"
      direction       = "out"
      protocol        = "tcp"
      port            = "6379"
      source_ips      = [] # Won't be used for this rule
      destination_ips = ["0.0.0.0/0", "::/0"]
    },

  ]
  hcloud_token            = var.hcloud_token
  source                  = "kube-hetzner/kube-hetzner/hcloud"
  ssh_public_key          = var.pub
  ssh_private_key         = var.priv
  network_region          = "eu-central"
  create_kubeconfig       = false
  create_kustomization    = false
  #
  use_control_plane_lb    = false
  lb_hostname             = ""
  control_plane_lb_type   = "lb11"
  enable_rancher          = true
  initial_k3s_channel     = "v1.25"
  rancher_install_channel = "stable"
  rancher_hostname        = ""

  cluster_name = ""

  automatically_upgrade_k3s = false
  automatically_upgrade_os  = false

  ingress_controller = "nginx"


  control_plane_nodepools = [
    {
      name        = "control-plane",
      server_type = "cx31",
      location    = "fsn1",
      labels      = ["role=master"],
      taints      = [],
      count       = 1

      # Enable automatic backups via Hetzner (default: false)
      # backups = true
    },

  ]

  agent_nodepools = [
    {
      name        = "agent-development",
      server_type = "cpx41",
      location    = "fsn1",
      labels      = ["environment=development", "role=worker"],
      taints      = [],
      count       = 2

      # Enable automatic backups via Hetzner (default: false)
      # backups = true
    },
    #
    {
      name        = "agent-redis-dev",
      server_type = "cx21",
      location    = "fsn1",
      labels      = ["environment=redis"],
      taints      = [],
      count       = 1

      # Enable automatic backups via Hetzner (default: false)
      # backups = true
    },
  ]

  load_balancer_type     = "lb11"
  load_balancer_location = "fsn1"

}
```

### Platform

Linux

**Comment by swarnat** [comment]
Just want to say, that this probably is not related to your changes, because I scale a pool to zero and got the exact same error.

Probably something related to the update, the provider got 4 hours ago and there should be something adjusted in kube.tf. But I'm also slightly new within terraform for this project.

I fixed that by pinning the provider version to 1.43. 
Simple search for this block in kube.tf and adjust the version line: (I commented the original line to move back)
```
terraform {
  required_version = ">= 1.4.0"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "= 1.43.0"
#      version = ">= 1.41.0
    }
  }
}
```

**Comment by mysticaltech** [comment]
@swarnat Thanks for the info. Let's see how this evolves. @grig0701 for rancher, make sure to not use the latest version of kube, but instead a version that is compatible with rancher. So make sure to tweak initial_k3s_channel and rancher_version to a pair that is compatible to one another, I do not think you need to touch the LB settings, proxy protocol is usually useful.

**Comment by grig0701** [comment]
> @swarnat Thanks for the info. Let's see how this evolves. @grig0701 for rancher, make sure to not use the latest version of kube, but instead a version that is compatible with rancher. So make sure to tweak `initial_k3s_channel` and `rancher_version` to a pair that is compatible to one another (see kube.tf.example for a better explanation), I do not think you need to touch the LB settings, proxy protocol is usually useful.

Thanks for the answer! My version is v1.25.12+k3s1
Rancher version: v2.7.5

**Comment by grig0701** [comment]
> Just want to say, that this probably is not related to your changes, because I scale a pool to zero and got the exact same error.
> 
> Probably something related to the update, the provider got 4 hours ago and there should be something adjusted in kube.tf. But I'm also slightly new within terraform for this project.
> 
> I fixed that by pinning the provider version to 1.43. Simple search for this block in kube.tf and adjust the version line: (I commented the original line to move back to stay up to date)
> 
> ```
> terraform {
>   required_version = ">= 1.4.0"
>   required_providers {
>     hcloud = {
>       source  = "hetznercloud/hcloud"
>       version = "= 1.43.0"
> #      version = ">= 1.41.0
>     }
>   }
> }
> ```

Thank you very much for your help, it helped!

**Comment by mysticaltech** [comment]
@grig0701 Were you able to make it work?

**Comment by grig0701** [comment]
> @grig0701 Were you able to make it work?

Yes, the terraform issue has been fixed, the rancher issue has not
