### ISSUE TITLE
Download for x86-MicroOS dead

### ISSUE THREAD

**Issue by tim-olbrich** [kube-hetzner/terraform-hcloud-kube-hetzner#1057]
Hello!

currently the download link for the microOS image when creating the snapshots is not working. 
(https://download.opensuse.org/repositories/devel:/kubic:/images/openSUSE_Tumbleweed/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2)

Thank you for your hard work on this project!

**Comment by mysticaltech** [comment]
Thanks for the info @tim-olbrich, it seems the link has changed to https://download.opensuse.org/tumbleweed/appliances/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2, will submit a corrective PR right away!

**Comment by tim-olbrich** [comment]
Thank you very much!

**Comment by mysticaltech** [comment]
It's fixed in v2.3.4, thanks again for the tip 🙏
