### ISSUE TITLE
[Bug]: Kubelet args from example

### ISSUE THREAD

**Issue by aleksasiriski** [kube-hetzner/terraform-hcloud-kube-hetzner#1109]
### Description

Using kube.tf examples for kubelet args results in error:
```
Error: failed to run Kubelet: --system-reserved value failed to parse: failed to parse quantity "memory=200Mi" for "cpu" resource: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
Dec 04 13:23:00 k3s-control-plane-fsn1-mbq k3s[5016]: time="2023-12-04T13:23:00Z" level=fatal msg="kubelet exited: failed to run Kubelet: --system-reserved value failed to parse: failed to parse quantity \"memory=200Mi\" for \"cpu\" resource: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"
```

~~My guess is that~~ it should be:
```terraform
["kube-reserved=cpu=100m,memory=200Mi,ephemeral-storage=1Gi", "system-reserved=cpu=100m,memory=200Mi"]
```

Also, reading minimum requirement for MicroOS [here](https://microos.opensuse.org/blog/2020-11-23-requirements/) and for K3s [here](https://docs.k3s.io/reference/resource-profiling?_highlight=ram#k3s-agent) I would argue that these example values should be used:

For control planes:
```terraform
kubelet_args = ["kube-reserved=cpu=250m,memory=1500Mi,ephemeral-storage=1Gi", "system-reserved=cpu=250m,memory=300Mi"]
```

And for agents:
```terraform
kubelet_args = ["kube-reserved=cpu=50m,memory=300Mi,ephemeral-storage=1Gi", "system-reserved=cpu=250m,memory=300Mi"]
```

**If we decide that this is correct I will gladly make a PR. Also, I would like to propose that we make these example values applied by default**

### Kube.tf file

```terraform
kubelet_args = ["kube-reserved=cpu=100m,memory=200Mi,ephemeral-storage=1Gi", "system-reserved=cpu=memory=200Mi"]
```

### Platform

Linux

**Comment by mysticaltech** [comment]
@aleksasiriski  Sounds like a good idea for stability. And definitely, we should fix the error, please don't hesitate to do a PR if you can 🙏

**Comment by mysticaltech** [comment]
Deployed in v2.10.2  🚀
