### ISSUE TITLE
[Bug/Issue]: kured may get stuck

### ISSUE THREAD

**Issue by Timeraa** [kube-hetzner/terraform-hcloud-kube-hetzner#1117]
I had the issue that kured got stuck because of an autoscaled node being killed and I had to unlock it manually, I checked the arguments of kured and I don't see this option being set and from what I can read out of the documentation kured highly recommends this to be set when using the cluster autoscaler. So I think this should be set as an argument by default on kured

These are the default arguments of kured:
<img width="1213" alt="image" src="https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/assets/29104008/3fc6a422-9e72-40dc-a8a4-b1219f3a02bd">

This is taken from kured's documentation:
https://kured.dev/docs/operation/#automatic-unlock
<img width="823" alt="image" src="https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/assets/29104008/5672dc67-fe1b-4a84-a122-06d1d994bd56">

**Comment by mysticaltech** [comment]
Super valuable! Thanks for the share @Timeraa. PR most welcome please.
