### ISSUE TITLE
[Bug]: When specifing custom namespace for ingress (traefik) controller, hanging waiting for deployment

### ISSUE THREAD

**Issue by childotg** [kube-hetzner/terraform-hcloud-kube-hetzner#1146]
### Description

Hi there, first of all thank you for this amazing project and support.
In short, if you specify this:
ingress_target_namespace = "something"
The resources are created correctly BUT, during the terraform provisioning, this step fails:
```
 Error: remote-exec provisioner error
│
│   with module.kube-hetzner.null_resource.kustomization,
│   on .terraform/modules/kube-hetzner/init.tf line 288, in resource "null_resource" "kustomization":
│  288:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_1183884130.sh": Process exited with status 124
```
Because this part of the script:
```
kubectl apply -k /var/post_install
echo 'Waiting for the system-upgrade-controller deployment to become available...'
kubectl -n system-upgrade wait --for=condition=available --timeout=360s deployment/system-upgrade-controller
sleep 7
kubectl -n system-upgrade apply -f /var/post_install/plans.yaml
timeout 360 bash <<EOF
until [ -n "\$(kubectl get -n traefik service/traefik --output=jsonpath='{.status.loadBalancer.ingress[0].ip}' 2> /dev/null)" ]; do
    echo "Waiting for load-balancer to get an IP..."
    sleep 2
done
EOF
```
Is doing this:
`kubectl get -n traefik service/traefik`
which has the classic "traefik" namespace hardcoded.
Unfortunately I'm not familiar with this custom terraform templates, so excuse me if I don't provide a PR for this.
Rregards
Rob

### Kube.tf file

```terraform
ingress_controller = "traefik"
ingress_target_namespace = "infra"
```

### Platform

WSL

**Comment by mysticaltech** [comment]
@childotg Really appreciate you finding this sneaky bug, it was fixed in v2.11.5. Enjoy!
