### ISSUE TITLE
[Request]: can multiple kubernetes services share hetzner's loadbalancer through annotations?

### ISSUE THREAD

**Issue by virtuman** [kube-hetzner/terraform-hcloud-kube-hetzner#1203]
### Description

Is it possible to use same hetzner load-balancer for multiple kubernetes services of type: LoadBalancer.

[According to the documentation referencing loadbalancer is available, but it won't merge for multiple services](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/load_balancers.md#reference-existing-load-balancers) 

Any chance I missed the documentation for this feature or that the feature would be added? 

Thanks

### Kube.tf file

```terraform
n/a
```

### Platform

linux

**Comment by mysticaltech** [comment]
One Hetzner LB per LB service. If you want to share, just use ingress definitions to share the same LB already deployed by default. See the example folder.
