### ISSUE TITLE
[Bug]: kured wrong sentinel path

### ISSUE THREAD

**Issue by jr-dimedis** [kube-hetzner/terraform-hcloud-kube-hetzner#1204]
### Description

**kured sentinel issue no. 1**

I recently upgraded the module from v2.7.2 to v2.11.7 (and I am pretty sure the issue is not fixed in v2.11.8, when I look at the source code). **EDIT**: I verified this on a test cluster - it's the same with v2.11.8.

Since that nodes do not reboot anymore in the configured time range.

Looking at the kured pod logs I see that kured is checking for `/var/run/reboot-required` but the host's `/var/run` is mounted to `/sentinel` in the pod.

So the correct location to check for is `/sentinel/reboot-required`. I added this to the kured options and then nodes were correctly rebooted by kured. 

Checking the differences between v2.7.2 and v2.11.7 I can see that there were changes regarding the kured deployment. Probably default settings changed due to this and now we have to set this option explicitly?

**kured sentinel issue no. 2** (solved, see EDIT below)

Then I made another observation.

I ran `transactional-update` manually on some of the nodes that had different MicroOS versions. Afterwards the file `/var/run/reboot-needed` was created (NOT `reboot-required`). I remember that I performed manual updates a few weeks ago using `systemctl start transactional-update.service` and I am pretty sure the expected `/var/run/reboot-required` file was created.

Is it possible that running `transactional-update` directly from the shell shows this different behavior? I checked the service configuration to see if there are special env variables set or something like that, and yes - that's the case. But the env files mentioned did not contain any sentinel options... Unfortunately I can't reproduce this now, because my nodes are up-to-date and currently the update does nothing. 

If `transactional-update` should better be called via `systemctl` the README should be adjusted accordingly.

**EDIT**: I checked this today and can confirm that executing `transactional-update` directly and not via systemd creates `/var/run/reboot-needed` instead of `/var/run/reboot-required`.

### Kube.tf file

```terraform
# Relevant parts of kube.tf file
module "kube-hetzner" {
  source = "kube-hetzner/kube-hetzner/hcloud"
  version = "2.11.7"

  kured_options = {
    "reboot-days": "su"
    "start-time": "3am"
    "end-time": "8am"
    "time-zone": "Europe/Berlin"

    # Required to set with v2.11.7 because of dangerous default
    "lock-ttl": "0"

    # This is required to make it work
    # "reboot-sentinel": "/sentinel/reboot-required"
  }

  initial_k3s_channel = "v1.26"

  automatically_upgrade_os = false
  automatically_upgrade_k3s = false

  # ...
}
```

### Platform

Linux

**Comment by mysticaltech** [comment]
@jr-dimedis Are you using MicroOS nodes outside of this project? If so, yes they do behave differently. However we configure the nodes to work with the kured reboot method.

I will have a look again at your issue, but it would surprise me if there's really a problem there. Please do make sure to upgrade the project to the latest version of kube-hetzner.

**Comment by mysticaltech** [comment]
If you `cat /etc/transactional-update.conf` it should see `REBOOT_METHOD=kured`,  this is what ensures that the file created is reboot-required and not reboot-needed.

**Comment by jr-dimedis** [comment]
I just upgraded kube-hetzner on a test cluster to latest v2.11.8. No changes on the cluster, in particular no Kured redeployment or something like that. So this version bump makes no difference.

**Comment by mysticaltech** [comment]
@jr-dimedis I will investigate this more, thanks for the info. Keep you posted.
