### ISSUE TITLE
[Feature Request]: Disable LoadBalancer in kube.tf

### ISSUE THREAD

**Issue by remotejob** [kube-hetzner/terraform-hcloud-kube-hetzner#1249]
### Description

I try to disable  LoadBalancer 

`load_balancer_disable_ipv6 = true
`

`load_balancer_disable_public_network = true`

service:
  enabled: **false**
  type: LoadBalancer

But anyway Loadbalancer was created after `terraform apply`

**Comment by mysticaltech** [comment]
@remotejob Use `ingress_controller = "none"`.
