### ISSUE TITLE
Allow configuring s3 `etcd-snapshot-retention` in config file

### ISSUE THREAD

**Issue by maggie44** [kube-hetzner/terraform-hcloud-kube-hetzner#1307]
### Description

k3s has a number of options for configuring s3: https://docs.k3s.io/cli/etcd-snapshot#options

These can be configured by adding the flags, but ideally they would be added to the `kube.tf` config file as specific options. 

This has become particularly pertinent as a PR introduced back in August (https://github.com/k3s-io/k3s/issues/9866) changed the way s3 backups are done and for a standard 3 control plane cluster the default k3s value of `5` is likely insufficient for most as it no longer backs up all of the control planes for a sufficient time span. Instead, we may need to start scaling that number based on the number of control planes we run.

**Comment by mysticaltech** [comment]
@maggie44 PR please.
