### ISSUE TITLE
Is there a documented solution for applying a PVC to the Traefik pod to persist certificate claims?

### ISSUE THREAD

**Issue by dantudor** [kube-hetzner/terraform-hcloud-kube-hetzner#136]
I receive multiple occurrences of the following error in the `svc/traefik` logs. 
I believe this is due to the pod restarting and the data folder not persisting therefore a new cert request is issued to letsencrypt.

I'd like to add a PVC to the pod as the /data folder. Wondering if anyone has covered this already

```time="2022-03-22T10:12:02Z" level=error msg="Unable to obtain ACME certificate for domains \"redacted.com\": unable to generate a certificate for the domains [redacted.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: redacted.com: see https://letsencrypt.org/docs/rate-limits/" providerName=le.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=devnet-api-ingress-default-redacted-com@kubernetes rule="Host(`redacted.com`) && PathPrefix(`/`)"```

**Comment by mysticaltech** [comment]
@dantudor Unfortunately not, but the simplest way is just to "outsource" SSL certificate management to `cert-manager` instead! See https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/123

**Comment by dantudor** [comment]
Thanks. Implemented cert-manager instead of using traefik. 👍
