### ISSUE TITLE
Update `cluster-autoscaler` version

### ISSUE THREAD

**Issue by karsten42** [kube-hetzner/terraform-hcloud-kube-hetzner#1364]
I [added the usage of a debug logger](https://github.com/kubernetes/autoscaler/pull/6862) to the `cluster-autoscaler` that shows all requests/responses made toward the Hetzner API when specifying a high log level (`--v=5` or higher). I needed this because I saw "unknown" errors from the Hetzner api when trying to scale nodes. 
I saw that a fork of the `autoscaler` repository is used here. 

How often is the fork updated to the latest version of the base repo?

Sorry if this is the wrong issue format but it didn't really fit the other templates.

**Comment by mysticaltech** [comment]
@karsten42 We last updated it about a month ago or so, pending merges and release of some changes on the mother repo. @Silvest89 do you know if the needed changes have been released already or not on the mother repo?

**Comment by mysticaltech** [comment]
@Silvest89 FYI, please your input is needed bro 🙏

**Comment by Silvest89** [comment]
@mysticaltech Yes we can revert back to the cluster-autoscaler. They have released them.

**Comment by mysticaltech** [comment]
@Silvest89 Thanks, appreciate it! Will do the change 🙏
