### ISSUE TITLE
[Bug]: image pull backoff error with latest: hetznercloud/hcloud-csi-driver:v2.7.0

### ISSUE THREAD

**Issue by elassadi** [kube-hetzner/terraform-hcloud-kube-hetzner#1373]
### Description

The hcloud-csi DaemonSet and hcloud-controller are failing to start due to an image pull backoff error for hetznercloud/hcloud-csi-driver:v2.7.0. 

The image docker.io/hetznercloud/hcloud-csi-driver:v2.7.0 is not available. Reverting to hcloud-csi-driver:v2.6.0 resolves the issue.

Affected Component: **hcloud-csi DaemonSet, hcloud-csi-controller**
Error Message: Image pull backoff error for hetznercloud/hcloud-csi-driver:v2.7.0
Image URL: docker.io/hetznercloud/hcloud-csi-driver:v2.7.0
**Workaround**: set variable   hetzner_csi_version = "2.6.0" solves the problem

### Kube.tf file

```terraform
Default Kube.tf latest version
```

### Platform

Linux

**Comment by stempler** [comment]
This was due to the csi driver release being broken (some images were not pushed, see [here](https://github.com/hetznercloud/csi-driver/issues/611)) and is resolved now.

**Comment by mysticaltech** [comment]
Thanks for the info @stempler, good to see they acted fast.
