### ISSUE TITLE
[Feature Request]: Make kubeconfig_server_address configurable

### ISSUE THREAD

**Issue by kranich** [kube-hetzner/terraform-hcloud-kube-hetzner#1390]
### Description

Making [`kubeconfig_server_address`](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/eb39273101356a8c428e7c00684511ced4cffa24/kubeconfig.tf#L15C3-L15C17) configurable would be helpful in a setup without a control plane loadbalancer but with a common hostname pointing to the IP addresses of all control plane nodes, as described [here](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/eb39273101356a8c428e7c00684511ced4cffa24/kube.tf.example#L748-L750).

When using the IP address of the first control plane node as `kubeconfig_server_address`, as currently implemented, the cluster cannot be accessed using that kubeconfig in case the first node is down. However, the cluster would still be accessible if the kubeconfig contained the hostname pointing to the IP addresses of all control plane nodes.

**Comment by mysticaltech** [comment]
@kranich That's a good idea, we the control-plane LB actually does that, but this would be simpler and cheaper. PR welcome!
