### ISSUE TITLE
Connection error i/o timeout while bootstrapping cluster

### ISSUE THREAD

**Issue by META-DREAMER** [kube-hetzner/terraform-hcloud-kube-hetzner#140]
[Full Logs](https://gist.github.com/META-DREAMER/b2a409491b1627de1f9c51b529d0c3d0#file-kube-hetzner-log-L999) 

Seems like its able to initially SSH in fine but then gets errors and doesn't finish bootstrapping once it tried to reboot MicroOS. 

Regenerated new ed25519 SSH keys, still doesn't work

Seems to be an issue with the firewall being added and blocking SSH before TF is done provisioning. If I manually remove the firewall when it gets created terraform progresses a bit further as seen in the logs (downloads microOS, etc), but still gets stuck. The server responds to pings, but hangs when trying to connect via SSH.

**Comment by phaer** [comment]
Hi @META-DREAMER, if I read this correctly, the attached logs are from a run where you disabled the firewall already?

Seeing that ssh is failing to establish a tcp connection before even being able to try to authenticate, I assume it's not related to your ssh keys.

What are you seeing when you open up the machine in question in hetzner clouds web interface? Is the machine booting up correctly?

**Comment by mysticaltech** [comment]
@META-DREAMER @phaer definitely has a point. But please make sure you do not use passphrases in your SSH key, if you do, you need to add them to the SSH agent.

**Comment by META-DREAMER** [comment]
> @META-DREAMER @phaer definitely has a point. But please make sure you do not use a passphrase in your SSH key, if you do, you need to add them to the SSH agent.

There’s no passphrase

@phaer in the hetzner cloud machines when I open the console they are usually on the rescue login prompt. I can ping them at this state, but the terraform logs just keep trying to connect via SSH and failing. 

If others can’t reproduce this from a fresh repo and fresh hetzner account, then it’s probably something in my network getting in the way

**Comment by mysticaltech** [comment]
@META-DREAMER From your description above, it just seems that your machine did not reboot. Which would point out the fact that the local-exec did not run properly. Why OS are you on? If you are on Windows, you need to use the Linux subsystem.

**Comment by META-DREAMER** [comment]
@mysticaltech I'm on macOS Monterey (M1 chip)

**Comment by mysticaltech** [comment]
Ok, in that case, you need to test how the code that runs in each local-exec executes in your bash.

Also, if you can, please post here the non-detailed (normal) terraform logs.

**Comment by HenkVanMaanen** [comment]
Same problem here, only Opensuse is booted. 

![image](https://user-images.githubusercontent.com/36051232/161429839-156519dd-864f-48aa-bc3d-00da6e8eb74c.png)

```static login: ```

When I try to connect to the server by hand (ssh with private key) I get ```port 22: connection timed out```. Even when I remove the server from the firewall.

**Comment by HenkVanMaanen** [comment]
Alright, found the solution that worked for me. You NEED to have an ed25519 key. I don't know what kind of key I previously had, but when I created a key using the ed25519 format it worked.

**Comment by phaer** [comment]
I am still not sure, what the suspected relationship to SSH is here?
Was the issue reproducible with an RSA key? Or could it be that it's a race condition which just did not pop up when @HenkVanMaanen (and others before) re-tried with an ed25519 key?
As written, the "i/o timeout" error should not be related to SSH keys at all because that error is about the TCP connection, happening before SSH key exchange has even started.

So until someone provides a log and/or reproducible scenario which shows that it's in fact the SSH key type, I am a bit skeptical whether it's really SSH.

**Comment by HenkVanMaanen** [comment]
@phaer I did not have the same problem as @META-DREAMER . https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/140#issuecomment-1086866536

I tried it 3 times with a key I already had (non ed25519 key for sure, don't know what kind of key). Then I tried it for the first time with a newly generated ed25519 key which worked.

**Comment by HenkVanMaanen** [comment]
Tried it again. Same result. Standard RSA key generated by `ssh-keygen` will give `dial tcp **.**.**.**:22: i/o timeout` error while trying to connect to the rebooted MicroOS node. ED25519 key works just fine, no errors no nothing.

**Comment by phaer** [comment]
Thanks for reproducing @HenkVanMaanen! So if I interpret you correctly, the node does not reboot correctly when using an RSA key? Did you confirm via web console? Or do you happen to have full json logs (TF_LOG=JSON) of both scenarios? I'd **love** to understand what exactly is happening here as this an issue which has been bothering us for quite some time now

**Comment by HenkVanMaanen** [comment]
I'm setting the ssh_private_key directly to my private key file. The screen I see via web console is: 
![image](https://user-images.githubusercontent.com/36051232/161704050-d7d9b753-313b-446b-9c21-b65a12aa934c.png)

The error is `port 22: connection timed out`. Same error when I try to `ssh -i private_key_file -o IdentitiesOnly=yes root@server_ip` by hand.

**Comment by mglinski** [comment]
This seems to be related to the [tallow](https://github.com/clearlinux/tallow) service temp-banning the connection attempts coming from Terraform. It is very likely related to one or more of these [rules](https://github.com/clearlinux/tallow/blob/master/data/sshd.json).

I am about to try and spin up a cluster with tallow disabled in the cloud-init and see if I can finally connect.

**Comment by mglinski** [comment]
Ok, I found the actual issue.

From `journalctl` on a fresh VM after terraform trying to connect for 7 mins:

```
Apr 09 07:02:42 static sshd[1641]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Apr 09 07:02:42 static sshd[1641]: Connection closed by authenticating user root 123.456.789.100 port 59492 [preauth]
Apr 09 07:02:58 static sshd[1643]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Apr 09 07:02:59 static sshd[1643]: Connection closed by authenticating user root 123.456.789.100 port 59506 [preauth]

```

This combined with [this](https://github.com/clearlinux/tallow/blob/master/data/sshd.json#L33) rule in tallow is simultaneously rejecting ssh-rsa publickey auth type connection attempts from terraform, and `tallow` is then temp-banning the connecting IP address, resulting in IO timeouts on future connection attempts.

**Comment by phaer** [comment]
Oh nice catch @mglinski! That totally explains, I think :)

**Comment by mysticaltech** [comment]
@mglinski Thank you for the deep-dive; that clarifies everything indeed! Well done 🙏

Will update the docs to reflect the allowed algorithms. As if it's removed, it's probably for a good reason.

**Comment by mysticaltech** [comment]
To recap, folks have to use either of these green algorithms. Basically, `rsa-sha2-*` and `ssh-ed25519`.

![ksnip_20220411-104527](https://user-images.githubusercontent.com/518555/162699642-f839d94f-795f-4d59-9e97-4294ac36a09f.png)

**Comment by mysticaltech** [comment]
All SSH options were clarified in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/docs/ssh.md.

**Comment by META-DREAMER** [comment]
> I am still not sure, what the suspected relationship to SSH is here? Was the issue reproducible with an RSA key? Or could it be that it's a race condition which just did not pop up when @HenkVanMaanen (and others before) re-tried with an ed25519 key? As written, the "i/o timeout" error should not be related to SSH keys at all because that error is about the TCP connection, happening before SSH key exchange has even started.
> 
> So until someone provides a log and/or reproducible scenario which shows that it's in fact the SSH key type, I am a bit skeptical whether it's really SSH.

Yea I don't think its SSH, I've tried many times with a ED25519 key, still doesn't work. The nodes boot into the rescue OS and get stuck there.

**Comment by mglinski** [comment]
> > I am still not sure, what the suspected relationship to SSH is here? Was the issue reproducible with an RSA key? Or could it be that it's a race condition which just did not pop up when @HenkVanMaanen (and others before) re-tried with an ed25519 key? As written, the "i/o timeout" error should not be related to SSH keys at all because that error is about the TCP connection, happening before SSH key exchange has even started.
> > So until someone provides a log and/or reproducible scenario which shows that it's in fact the SSH key type, I am a bit skeptical whether it's really SSH.
> 
> Yea I don't think its SSH, I've tried many times with a ED25519 key, still doesn't work. The nodes boot into the rescue OS and get stuck there. Occasionally its able to install MicroOS and boot into that, but then it still gets stuck on `Waiting for MicroOS to reboot and become available...`
> 
> When I manually create a new VM and attach the same firewall and SSH key, I'm able to SSH into the Ubuntu server just fine.
> 
> While the TF script is running if I try to SSH into one of the nodes when its in recovery mode, it just hangs and times out. I am still able to ping the node

Above I also described an issue with the built in SSH jail software included in the MicroOS image. If you are getting 0 response from the machines when trying to connect, that might be something to investigate.

**Comment by mysticaltech** [comment]
@META-DREAMER You are getting banned by Tallow as stated by @mglinski. Please make sure to:
1. Destroy your cluster, start from a new Hetzner project and never touch things like the firewall manually.
2. Recreate fresh ssh keys, ED25519 without passphrase.
3. Update your OpenSSH client to latest and greatest.
4.Try again, it cannot not work! :)

**Comment by mysticaltech** [comment]
@METADREAMER Make sure you do not use a passphrase, and try again please!
