### ISSUE TITLE
[Feature Request]: Configure all HelmChart deployments with version

### ISSUE THREAD

**Issue by schlichtanders** [kube-hetzner/terraform-hcloud-kube-hetzner#1413]
### Description

Currently the version for some HelmCharts cannot be set

e.g.
- longhorn
- cert-manager
- ... probably more

For recreating the very same cluster it is essential to be able to fix these versions

**Comment by mysticaltech** [comment]
@schlichtanders Very good you took this on, it's was a pain point I knew about but did not have time to focus on. Thanks!
