### ISSUE TITLE
Placement group 10 servers limit

### ISSUE THREAD

**Issue by HenkVanMaanen** [kube-hetzner/terraform-hcloud-kube-hetzner#142]
First of all, thank you for this amazing project. I created my own terraform module to deploy k3s on Hetzner. But this project is way more organized and really nice! 

If I recall correctly the placement group is limited by 10 servers per group. So [this code adding placement groups](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/34) will only work until there are more than 10 servers.

**Comment by mysticaltech** [comment]
Good find @HenkVanMaanen! It seems to be the case indeed. I have verified the info here https://docs.hetzner.com/cloud/placement-groups/overview.

@phaer @mnencia, I propose we make the placement group optional then. @HenkVanMaanen, please do not hesitate to submit a PR; using a variable flag for this would be ideal.

**Comment by mnencia** [comment]
I would use, by default, one placement group per node group plus one for the control plane. However, having a flag to disable them looks like a good idea if you hit the limits.

**Comment by HenkVanMaanen** [comment]
The solution I used was creating enough placement groups so that all servers would fit into these groups, with this algorithm the servers will get round robinned into the placement groups e.g.: 

```terraform
locals {
  hcloud_placement_group_limit = 10
}

resource "hcloud_placement_group" "workers" {
  count = ceil(var.worker_replicas / local.hcloud_placement_group_limit)
  name = "workers-group-${count.index + 1}"
  type = "spread"
}

resource "hcloud_server" "workers" {
  count       = var.worker_replicas
  name        = "${var.cluster_name}-worker-${count.index + 1}"
  placement_group_id = element(hcloud_placement_group.workers.*.id, ceil(count.index / local.hcloud_placement_group_limit))
}
```

**Comment by mnencia** [comment]
This is an interesting way to support more than ten servers in the same group. With this trick and having different placement groups per node pool, we could avoid having the switch to disable placement groups globally.

**Comment by HenkVanMaanen** [comment]
We still need to consider the 50 placement group limit of Hetzner.

![image](https://user-images.githubusercontent.com/36051232/161519027-7a4ee212-b0cf-44df-a9b0-59e428fbd6bf.png)

**Comment by mnencia** [comment]
Well, if you have 500 servers, you probably have the resources to contribute to the project a global disable placement group patch :-)

**Comment by mysticaltech** [comment]
Nice solution, @HenkVanMaanen!

**Comment by gor181** [comment]
> The solution I used was creating enough placement groups so that all servers would fit into these groups, with this algorithm the servers will get round robinned into the placement groups e.g.:
> 
> ```terraform
> locals {
>   hcloud_placement_group_limit = 10
> }
> 
> resource "hcloud_placement_group" "workers" {
>   count = ceil(var.worker_replicas / local.hcloud_placement_group_limit)
>   name = "workers-group-${count.index + 1}"
>   type = "spread"
> }
> 
> resource "hcloud_server" "workers" {
>   count       = var.worker_replicas
>   name        = "${var.cluster_name}-worker-${count.index + 1}"
>   placement_group_id = element(hcloud_placement_group.workers.*.id, ceil(count.index / local.hcloud_placement_group_limit))
> }
> ```

@HenkVanMaanen - Thank you very much for pointing me in the right direction with this. Being pretty new to the terraform in general would it be possible for you to help me a bit further with this?

I'm currently getting 

![image](https://user-images.githubusercontent.com/8964589/162609778-0b8c5620-ad6f-44b1-b648-724c283c8c1f.png)

Appreciate your response.

**Comment by gor181** [comment]
Ok I went semi-automatic 😄 

Requirements:
- Create the placement groups manually on Hetzner and copy their id's

Code changes:

`agents.tf`:
![image](https://user-images.githubusercontent.com/8964589/162632414-a7656e9a-e303-453e-a12b-04d1eb8052fb.png)

`locals.tf`:
![image](https://user-images.githubusercontent.com/8964589/162632473-26dab92e-2538-489e-ab4b-68b87c4b251f.png)

Maybe a potential solution would be to allow users to manually specify the placement groups or automatically via round-robin.
