### ISSUE TITLE
Disk partitions

### ISSUE THREAD

**Issue by HenkVanMaanen** [kube-hetzner/terraform-hcloud-kube-hetzner#144]
Why is the disk on a server, for example cpx11, split into 2 partitions of 20 GB each?

**Comment by mysticaltech** [comment]
@HenkVanMaanen That is how OpenSuse MicroOS does it. We do not interfere with its partitioning scheme. Seehttps://en.opensuse.org/Portal:MicroOS/Design#Filesystem
