### ISSUE TITLE
Instance type cx22 is not available (currently or anymore)

### ISSUE THREAD

**Issue by virtuman** [kube-hetzner/terraform-hcloud-kube-hetzner#1440]
Packer fails when trying to build images since it's referencing instance type that is not available. I saw some updated from hetzner about instance types, but sort of missed the point, whether it was no longer available, or jsut currently not available.

I think it would be nice to have it dynamically pick available instance type with min resources that are needed to build the images, instead of having a hardcoded value. 

https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/e171efcc9f3f2dd9f4f283fdf64b0793e4aaa259/packer-template/hcloud-microos-snapshots.pkr.hcl#L83

**Comment by ricristian** [comment]
Nope packer is not failing on anything I've just rebuild the opensuse images using packer following readme guide and everything was just fine. 

```
mkdir /path/to/your/new/folder
cd /path/to/your/new/folder
curl -sL https://raw.githubusercontent.com/kube-hetzner/terraform-hcloud-kube-hetzner/master/kube.tf.example -o kube.tf
curl -sL https://raw.githubusercontent.com/kube-hetzner/terraform-hcloud-kube-hetzner/master/packer-template/hcloud-microos-snapshots.pkr.hcl -o hcloud-microos-snapshots.pkr.hcl
export HCLOUD_TOKEN="your_hcloud_token"
packer init hcloud-microos-snapshots.pkr.hcl
packer build hcloud-microos-snapshots.pkr.hcl
hcloud context create <project-name>
```

Without providing more details from your side like screenshots of commands and so on I propose that issue to be closed

**Comment by mysticaltech** [comment]
Thanks for confirming @ricristian. @virtuman It might have been a temporary issue on hetzner's side. Please try again with the method exposed above. Closing this for now.
