### ISSUE TITLE
[Bug]: microos snapshots - Error: no image found matching the selection

### ISSUE THREAD

**Issue by baraka121** [kube-hetzner/terraform-hcloud-kube-hetzner#1441]
### Description

It seems that Hetzner has removed microOS snapshots from their library.

While I'm trying to run this command:
`hcloud image list --selector 'microos-snapshot=yes'`

I'm getting no results.
What can I do to resolve this?

### Kube.tf file

```terraform
no need
```

### Platform

Mac

**Comment by wiemann** [comment]
seems like it happened again.
