### ISSUE TITLE
[Feature Request]: Add taint toleration to cluster-autoscaler

### ISSUE THREAD

**Issue by mabilinab** [kube-hetzner/terraform-hcloud-kube-hetzner#1455]
### Description

I have added a taint to my master node, and now, the cluster-autoscaler pods can no longer be scheduled since they do not have the right taint toleration.
Is it possible to configure the cluster-autoscaler deployment to have the right toleration to be scheduled on the master node?
(I think I can do that through kubectl, but that will be overridden whenever I apply the kube.tf)

**Comment by mysticaltech** [comment]
@mabilinab  It should not get overwritten as the tf state was not changed. Try it, you'll see that it remains.
