### ISSUE TITLE
[Feature Request]: output hostname, ipv4, ipv6 for agent and control plane nodes

### ISSUE THREAD

**Issue by 0xch4z** [kube-hetzner/terraform-hcloud-kube-hetzner#1460]
### Description

Right now ipv4 addresses are available as an output but not mapped to the corresponding hetzner server name.

Providing users with a `agent_nodes` and `control_plane_nodes` output of type `list(map)` and including hostname and ips would allow users to create DNS records outside of Hetzner Cloud (with Cloudflare or Route 53) for example.

Maybe forwarding all outputs from `modules/host` makes the most sense for extensibility. e.g.:

```json
{
  "outputs": {
    // ...
    "agent_nodes": [
      // ...
      {
        "ipv4_address": "8.8.8.8",
        "ipv6_address": "2001:4860:4860::8888",
        "private_ipv4_address": "172.18.0.1",
        "name": "special-worker-06",
        "id": "c46033b2-80b6-4802-ab97-47659b05960d"
      }
    ]
  }
}

**Comment by mysticaltech** [comment]
Thanks @0xch4z, that sounds like a good idea, I will process the PR ASAP.
