### ISSUE TITLE
[Bug]: Cluster autoscaler will break after 6/9

### ISSUE THREAD

**Issue by WebSpider** [kube-hetzner/terraform-hcloud-kube-hetzner#1465]
### Description

I've just received an email from Hetzner.
This relates to https://github.com/kubernetes/autoscaler/issues/7210

We should decide if we want to wait for this issue to be merged and bump the cluster-autoscaler version, or use the Hetzner provided temporary cluster-autoscaler version as mentioned here: https://docs.hetzner.cloud/changelog#2024-08-30-bug-cx11-removal-will-break-certain-versions-of-cluster-autoscaler

### Kube.tf file

```terraform
-
```

### Platform

Linux

**Comment by apricote** [comment]
Hello :wave:,

existing users of the cluster-autoscaler should be save.

New users will get the error mentioned in the autoscaler issue. You can switch to the temporary images, or at least point new users at the possibility of using those to get cluster-autoscaler working during the weeks inbetween.

**Comment by mysticaltech** [comment]
@Silvest89  Any recommendation on the best course of action for us here, please?

**Comment by Silvest89** [comment]
> @Silvest89 Any recommendation on the best course of action for us here, please?
> 
> I think I will switch the the Hetzner provided images right away.

I think using the hetzner provided images would be the best course of action for now. Saves us from using our repo for it :P.

**Comment by mysticaltech** [comment]
Fully agree! Will integrate it today.

**Comment by mysticaltech** [comment]
Fixed in [v2.14.5](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/releases/tag/v2.14.5)
