### ISSUE TITLE
Cascading issue which renders a node unavailable

### ISSUE THREAD

**Issue by dantudor** [kube-hetzner/terraform-hcloud-kube-hetzner#148]
I'm running with the following setup:

```
location = "nbg1"       # change to `ash` for us-east Ashburn, Virginia location
network_region   = "eu-central" # change to `us-east` if location is ash

control_plane_count = 1
control_plane_server_type = "cpx11"

agent_nodepools = [
  {
    name        = "agent-small",
    server_type = "cpx11",
    count       = 0
  },
  {
    name        = "agent-large",
    server_type = "cpx21",
    count       = 2
  }
]

load_balancer_type        = "lb11"

traefik_enabled = true
metric_server_enabled = false

allow_scheduling_on_control_plane = false

automatically_upgrade_k3s = false

cluster_name = "XXXX"
use_cluster_name_in_node_name = false

extra_firewall_rules = [
  {
    direction = "out"
    protocol  = "tcp"
    port      = "26257"
    destination_ips = [
      "0.0.0.0/0",
      "::/0"
    ]
  }
]
```

One of my nodes gets into the following state:
1. New pods cannot be scheduled to the node
2. Terminating nodes rename in the terminating state
3. Existing pods lose connectivity to the world and fall into a restart cycle after terminating
4. Bashing into the node and performing a curl will work

The node shows health conditions:
```
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Thu, 31 Mar 2022 23:21:06 +0100   Thu, 31 Mar 2022 23:21:06 +0100   RouteCreated                 RouteController created a route
  MemoryPressure       False   Thu, 07 Apr 2022 20:10:37 +0100   Wed, 06 Apr 2022 21:48:30 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Thu, 07 Apr 2022 20:10:37 +0100   Wed, 06 Apr 2022 21:48:30 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Thu, 07 Apr 2022 20:10:37 +0100   Wed, 06 Apr 2022 21:48:30 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Thu, 07 Apr 2022 20:10:37 +0100   Wed, 06 Apr 2022 21:48:40 +0100   KubeletReady                 kubelet is posting ready status
```

All non terminated pods show as not using any resources:
```
Non-terminated Pods:          (17 in total)
  Namespace                   Name                                              CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                              ------------  ----------  ---------------  -------------  ---
  default                     api-569dbfbfb5-lmjcm                              0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  ...
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
  hugepages-1Gi      0 (0%)    0 (0%)
  hugepages-2Mi      0 (0%)    0 (0%)
```

If I drain the node and then power cycle the node will come back to life and will work again as expected.  
Seems to fall over once every 3-4 days.

**Comment by dantudor** [comment]
I realise this may not be specific to this setup. Just not really sure what logs to examine where to find the root cause.
Not sure where to find things like kubelet or scheduler logs

**Comment by mysticaltech** [comment]
@dantudor This is happening because you are not in HA (minimum 3 control plane nodes required for that), and your cluster still does automatic upgrades of the OS (not k3s, you have turned that off). 

For non-HA setup, you need to disable automatic upgrades of the OS too! See https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner#automatic-upgrade.

**Comment by dantudor** [comment]
@mysticaltech This seems to not be due to my HA configuration.

I've tested with the following configurations:
1. 3 control planes 3 agents - auto updates on
2. 3 control planes 3 agents - auto updates off (including OS auto updates disabled)
3. 1 control plane, 3 agents -  auto updates off (including OS auto updates disabled)

All three scenarios result in nodes losing network connectivity within containers and no new pods deployable due to not being able to pull images.

**Comment by mysticaltech** [comment]
@dantudor Thank you for doing a deep dive. At some point, this project used CCM and CSI manifests that kustomized latest or canary tags, and that was causing the issue that you describe above.

Please, try redeploying with the latest version, lots of things have improved now. It should work well! 🤞

**Comment by dantudor** [comment]
@mysticaltech I've upgraded to the latest master commit but my nodes still eventually lose connectivity to pull new images or internet access from within the existing pods.
Do you know if there are any relevant logs in microos that may shed some light on the issue?

**Comment by mysticaltech** [comment]
@dantudor Weird! Please do try to look at the internal Kube logs. The fastest would be to use something like [Lens](https://www.mirantis.com/software/lens/).

Also, the k3s logs. To do so, SSH into the nodes (see Readme) and execute:

For control plane nodes:

`
journalctl -u k3s
`

And for agent nodes:

`
journalctl -u k3s-agent
`

**Comment by dantudor** [comment]
It happened again this evening. I think it occurs after a certain amount of traffic has flowed. It's been hit quite a bit today (maybe a few days worth of traffic so dropped connectivity sooner).

Nothing notable in the agent k3s-agent log.

There was a repeition if this error in the control plane k3s log:
```Apr 22 21:33:05 zildexr-control-plane-01-yot k3s[1998]: {"level":"info","ts":"2022-04-22T21:33:05.506Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":652276}
Apr 22 21:33:05 zildexr-control-plane-01-yot k3s[1998]: {"level":"info","ts":"2022-04-22T21:33:05.520Z","caller":"mvcc/kvstore_compaction.go:57","msg":"finished scheduled compaction","compact-revision":>
Apr 22 21:33:16 zildexr-control-plane-01-yot k3s[1998]: E0422 21:33:16.946661    1998 network_policy_controller.go:248] Aborting sync. Failed to sync network policy chains: %!v(MISSING)ipset v7.6: Kerne>
```

**Comment by mysticaltech** [comment]
Maybe it's low on ressources? You need to dig deeper down the internal working logs of the cluster, down the pod, node, and container level and really get to the bottom of the issue. The pod that lost connectivity, dive deep down it's logs and inspect the resource usage. As said above, Lens seems ideal for that research!

**Comment by dantudor** [comment]
Lens gave some good incites.

I tracked down a service in my cluster that was leaving HTTP connections open and I guess eventually hitting an os/kube limit that prevented new outbound connections from being established. 

Thank you for the advice and support! Really appreciate the work you've done here and the code you've shared.

**Comment by mysticaltech** [comment]
Great to hear! Thanks Dan 🙏
