### ISSUE TITLE
[Bug]: One control plane node stuck waiting for MicroOS

### ISSUE THREAD

**Issue by heysarver** [kube-hetzner/terraform-hcloud-kube-hetzner#1484]
### Description

I'm trying to deploy a cluster with 3 or 5 control nodes, both have the same result.  N-1 nodes come up successfully but after several terraform destroy and apply plans there's always 1 control node that is stuck in "Waiting for MicroOS to become available..." until terraform times out.

### Kube.tf file

```terraform
module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  source = "kube-hetzner/kube-hetzner/hcloud"
  version = "~> 2.14.0"
  hcloud_token = var.hcloud_token

  ssh_public_key = var.ssh_public_key
  ssh_private_key = var.ssh_private_key

  network_region = "us-east"
  
  initial_k3s_channel    = "v1.29"

  cluster_name = "k8s-primary"
  base_domain = "hzr.*******.net"

  control_plane_nodepools = [
    {
      name        = "control",
      server_type = "cpx41",
      location    = "ash",
      count       = 3,
      labels      = [],
      taints      = []
    }
  ]

  agent_nodepools = [
    {
      name        = "worker",
      server_type = "cpx21",
      location    = "ash",
      labels      = [],
      taints      = [],
      count       = 0
    }
  ]

  allow_scheduling_on_control_plane = true

  load_balancer_type     = "lb11"
  load_balancer_location = "ash"
  load_balancer_disable_ipv6 = true
  load_balancer_algorithm_type = "least_connections"
  load_balancer_health_check_interval = "5s"
  load_balancer_health_check_timeout = "3s"

  use_control_plane_lb = true
  control_plane_lb_type = "lb11"

  cluster_autoscaler_version   = "20240226"
  cluster_autoscaler_log_level = 4

  ingress_controller = "nginx"
  ingress_target_namespace = "ingress-nginx"
  ingress_replica_count = 3

  kured_options = {
    "reboot-days": "su",
    "start-time": "3am",
    "end-time": "8am",
    "time-zone": "America/New_York",
    "lock-ttl" : "30m",
  }

  dns_servers = [
    "8.8.8.8",
    "1.1.1.1",
  ]

  cert_manager_values = <<EOT
installCRDs: true
replicaCount: 3
webhook:
  replicaCount: 3
cainjector:
  replicaCount: 3
  EOT

  nginx_values = <<EOT
controller:
  watchIngressWithoutClass: "true"
  kind: "DaemonSet"
  config:
    "use-forwarded-headers": "true"
    "compute-full-forwarded-for": "true"
    "use-proxy-protocol": "true"
  service:
    annotations:
      "load-balancer.hetzner.cloud/name": "k8s-primary-nginx"
      "load-balancer.hetzner.cloud/use-private-ip": "false"
      "load-balancer.hetzner.cloud/disable-private-ingress": "false"
      "load-balancer.hetzner.cloud/location": "ash"
      "load-balancer.hetzner.cloud/type": "lb11"
      "load-balancer.hetzner.cloud/uses-proxyprotocol": "true"
  EOT

}
```

### Screenshots

Failed Node:
![Screenshot 2024-09-20 at 12 21 57 PM](https://github.com/user-attachments/assets/b0d397e3-f148-44ec-84c5-4d3cba2b8994)

### Platform

MacOS, Terraform Cloud

**Comment by mysticaltech** [comment]
@heysarver Please try rebooting the node with hcloud, see if it fixes it.

**Comment by JWDobken** [comment]
I experience the same problem!

Two things that I noted.

1. the particular nodes don't have a Private IP
<img width="1142" alt="image" src="https://github.com/user-attachments/assets/946347bf-ef4d-49ee-95f8-228bad2f553a">

2. They are both not connected to the private network:

<img width="496" alt="image" src="https://github.com/user-attachments/assets/c3fe97c1-4698-4fea-8edf-734bf1e02520">



- rebooting does not help
- manually connecting to the network neither

**Comment by mysticaltech** [comment]
@heysarver Also check the missing private ip also happens to you, like for @JWDobken, please.

**Comment by mysticaltech** [comment]
@JWDobken please create a new issue with all the details.

**Comment by JWDobken** [comment]
rebuilding the image seemed to have solved my issue, thank you.

**Comment by heysarver** [comment]
@mysticaltech I've started using it already and have hit my limits on a new account so I'll have to wait to try, but sounds reasonable.

**Comment by heysarver** [comment]
I can confirm this was my issue with kured_options lock-ttl set to 30m.

I also had to manually open the firewall ports for the nginx ingress load balancer with this config.  Any ideas on that or should I open a new issue?

**Comment by heysarver** [comment]
@mysticaltech I'm having to add rules for the destination nginx-ingress ports manually to the firewall after creating, otherwise all the targets are unhealthy.  This causes terraform state to get out of sync.

![Screenshot 2024-11-08 at 12 45 39 PM](https://github.com/user-attachments/assets/eff8d841-c139-451e-a940-bd9b00d17327)
![Screenshot 2024-11-08 at 12 46 22 PM](https://github.com/user-attachments/assets/f9208f4f-07fe-4583-8cb3-642b1717b4e2)

**Comment by mysticaltech** [comment]
@heysarver Please open a new issue with the full working kube.tf apart from private info, and steps to reproduce please.

**Comment by adamthewilliam** [comment]
Make sure that the IP of the machine you're running the terraform commands is included in the firewall_ssh_source array in the kube.tf

**Comment by dvcrn** [comment]
running into this as well, terraform cloud, macos, clean install following README. though no load balancers

disabled firewall completely to not have port issues, rebooted but still stuck on "Waiting for MicroOS to become available"

How did you all fix it?

**Comment by dvcrn** [comment]
Solved my issue. It was the SSH key 

I wanted to use agent auth, but obviously that doesn't work when run through terraform cloud. Fixed by specifying an actual SSH key and importing it into hetzner
