### ISSUE TITLE
[Bug]: Agent nodes stuck in "Still creating" after upgrade from 2.14.1 to any newer version

### ISSUE THREAD

**Issue by jonasmock** [kube-hetzner/terraform-hcloud-kube-hetzner#1491]
### Description

With version 2.14.1  everything is working fine. But upgrading to any of the newer versions leads to infinite loop of "Still creating" the agent nodes while setup. 

### Kube.tf file

```terraform
module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = var.hcloud_token

  create_kubeconfig    = false
  create_kustomization = false

  source  = "kube-hetzner/kube-hetzner/hcloud"
  version = "2.14.5"

  cluster_name = "xxx"


  ssh_public_key  = var.ssh_public_key
  ssh_private_key = var.ssh_private_key

  network_region = var.network_region

  control_plane_nodepools = var.control_plane_nodepools
  agent_nodepools         = var.agent_nodepools

  load_balancer_type     = var.load_balancer_type
  load_balancer_location = var.load_balancer_location
  lb_hostname            = var.load_balancer_hostname

  dns_servers = [
    "1.1.1.1",
    "8.8.8.8",
    "2606:4700:4700::1111",
  ]

  # Ingress configuration
  ingress_controller = "nginx"

  # Storage configuration
  enable_longhorn = true
  longhorn_values = <<EOT
defaultSettings:
  defaultDataPath: /var/longhorn
  backupTarget: "${var.backup_target}"
  backupTargetCredentialSecret: "${var.backup_target_credential_secret}"
  node-down-pod-deletion-policy: delete-both-statefulset-and-deployment-pod
persistence:
  defaultFsType: ext4
  defaultClassReplicaCount: 3
  defaultClass: true
  EOT

  # Schedule automatic reboots e.g. for system upgrades on Sundays between 4am and 8am UTC
  kured_options = {
    "reboot-days" : "su",
    "start-time" : "4am",
    "end-time" : "8am",
    "lock-ttl" : "30m",
  }

  disable_hetzner_csi = true

  extra_firewall_rules = [
    {
      description     = "Allow SMB connections to SMB/CIFS storage"
      direction       = "out"
      protocol        = "tcp"
      port            = "445"
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    },
    {
      description     = "Allow Azure Event Hubs connections"
      direction       = "out"
      protocol        = "tcp"
      port            = "9093"
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    },
  ]

}




# Kubernetes Control Plane Nodepools
export TF_VAR_control_plane_nodepools='[
  {
    "name": "control-plane-01",
    "server_type": "cax11",
    "location": "fsn1",
    "labels": [],
    "taints": [],
    "count": 1
  },
  {
    "name": "control-plane-02",
    "server_type": "cax11",
    "location": "fsn1",
    "labels": [],
    "taints": [],
    "count": 1
  },
  {
    "name": "control-plane-03",
    "server_type": "cax11",
    "location": "nbg1",
    "labels": [],
    "taints": [],
    "count": 1
  }
]'

# Kubernetes Agent Nodepools
export TF_VAR_agent_nodepools='[
  {
    "name": "agent-pool-01",
    "server_type": "cax21",
    "location": "fsn1",
    "labels": [],
    "taints": [],
    "count": 1
  },
  {
    "name": "agent-pool-02",
    "server_type": "cax21",
    "location": "fsn1",
    "labels": [],
    "taints": [],
    "count": 1
  },
  {
    "name": "agent-pool-03",
    "server_type": "cax21",
    "location": "nbg1",
    "labels": [],
    "taints": [],
    "count": 1
  }
]'
```

### Screenshots

![image](https://github.com/user-attachments/assets/6834548f-8803-4731-b6dc-855b99b9727b)

### Platform

Mac

**Comment by wv-opt-ai** [comment]
I also ran into this, and narrowed it down to
`disable_hetzner_csi = false` being the workaround. Setting `disable_hetzner_csi = true` is triggering the "still creating", because `systemctl start k3s-agent` does *not* return, because the control plane nodes are stuck in a drained state with `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule`. Don't know the solution though at the code level though.

**Comment by wv-opt-ai** [comment]
By the way, I think the first commit after which this error appears is 9d6cd42c5973b6860f3cfeb2358f093aedebf511 .

**Comment by jonasmock** [comment]
> I also ran into this, and narrowed it down to `disable_hetzner_csi = false` being the workaround. Setting `disable_hetzner_csi = true` is triggering the "still creating", because `systemctl start k3s-agent` does _not_ return, because the control plane nodes are stuck in a drained state with `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule`. Don't know the solution though at the code level though.

`disable_hetzner_csi = false` works for me. But then I have two default storage classes. Not sure if this will cause issues:

![image](https://github.com/user-attachments/assets/17b47b5c-1802-497e-8d7f-a854b708074b)

**Comment by mysticaltech** [comment]
@jonasmock  The two storage classes are, one for hetzner csi, the other for longhorn. @wv-opt-ai Thanks for the tip, will look into it.

**Comment by mysticaltech** [comment]
That shouldn't be happening anymore. Let me know if it does!

**Comment by jonasmock** [comment]
@mysticaltech I tried with latest v2.15.2 but the issue still seems to exist for me:

<img width="991" alt="image" src="https://github.com/user-attachments/assets/10dbc777-cee3-4b11-a707-8a706032fca2">

**Comment by mysticaltech** [comment]
@jonasmock Are you upgrading or creating a new cluster?

If creating a new cluster, see the destroy section in our readme, you need to start from a clean slate always.

Also make you *terraform init -upgrade" and use the latest of the tooling. Last but not least if your images are old, create new ones.

Also I see you do not use the standard format for the nodepools, make sure you debug with our cusrom gpt or by looking at kube.tf.example.

I think it your kube.tf that's missing something.  The export, is definitely not standard, like with the export statements.

**Comment by jonasmock** [comment]
@mysticaltech I create a new cluster. With new images / snapshots and with `terraform init -upgrade`.

For me its the exact same behaviour:

If I use `disable_hetzner_csi = true` -> Stuck in agent pools still creating

If I use `disable_hetzner_csi = false` -> Setup works but I then have two default storage classes which is not the behavoiur I want as I only need longhorn storage class.

**Comment by mysticaltech** [comment]
@jonasmock The only possibility for such behavior is the custom helm values. Try doing without them at first.

**Comment by jonasmock** [comment]
@mysticaltech Okay, but why does it work until Version: 2.14.1?

**Comment by mysticaltech** [comment]
> @mysticaltech Okay, but why does it work until Version: 2.14.1?

I don't know @jonasmock I sorry. Could be new csi version, no idea really

**Comment by jonrosner** [comment]
I am getting the same issue. Unfortunately, I couldn't solve it by setting `disable_hetzner_csi = false`. Any idea why that is and how one can debug it?
