### ISSUE TITLE
Add new worker node

### ISSUE THREAD

**Issue by arkkanoid** [kube-hetzner/terraform-hcloud-kube-hetzner#150]
I've an existing cluster with 3 control planes + 1 worker node working. I added a new worker node but I'm not available to add them into the cluster. In the Terraform config file I incremented the count to 2, the script added the new node with no errors in the same subnet than the first worker node. 
If I connect to the new node I can ping the control planes and the worker node.
I tried to add them manually with this config:

`{
  "kind": "Node",
  "apiVersion": "v1",
  "metadata": {
    "name": "10.0.2.6",
    "labels": {
      "name": "agent-big-1"
    }
  }
}`

But the logs are:
kubectl describe node 10.0.2.6

`node 10.0.2.6 after 230.759893ms: hcloud/CreateRoute: hcops/AllServersCache.ByName: 10.0.2.6 hcops/AllServersCache.getCache: not found
  Warning  FailedToCreateRoute  4m46s (x53 over 13m)  route_controller  (combined from similar events): Could not create route 244b6a6e-2e16-4e68-b98b-6024d3037846 10.42.5.0/24 for node 10.0.2.6 after 274.573378ms: hcloud/CreateRoute: hcops/AllServersCache.ByName: 10.0.2.6 hcops/AllServersCache.getCache: not found`

How can I fix it?

**Comment by mysticaltech** [comment]
@arkkanoid Which version of kube-hetzner are you using? See here https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/tags. You have to choose the same version as your cluster was deployed with.
