### ISSUE TITLE
[Bug]: The ClusterRoleBinding "system-upgrade" is invalid

### ISSUE THREAD

**Issue by maaft** [kube-hetzner/terraform-hcloud-kube-hetzner#1538]
### Description

Got
```
The ClusterRoleBinding "system-upgrade" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"system-upgrade-controller"}: cannot change roleRef
```

When applying with latest version on existing cluster.

### Kube.tf file

```terraform
did not change between applys
```

### Platform

Linux

**Comment by maaft** [comment]
Previous working version was v2.14.6

**Comment by morinow** [comment]
Same here when upgrading from 2.15.0 to 2.15.3

**Comment by mysticaltech** [comment]
The system-upgrade-controller manifests have changed. Maybe we need those two manifests to be added to the kustomization too:

https://github.com/rancher/system-upgrade-controller/blob/master/manifests/clusterrolebinding.yaml
https://github.com/rancher/system-upgrade-controller/blob/master/manifests/clusterrole.yaml

The same way that crd.yml was added. If someone can test this and shoot a PR, it would be super appreciated.

**Comment by mysticaltech** [comment]
Folks, brand new clusters work well now with the version. For upgrade, in case you experience issues:

`kubectl delete -f https://raw.githubusercontent.com/rancher/system-upgrade-controller/9e7e45c1bdd528093da36be1f1f32472469005e6/manifests/system-upgrade-controller.yaml
`
Cleanup the old one. Then upgrade!
