### ISSUE TITLE
[Question] Why not create a snapshot and provision future nodes from it?

### ISSUE THREAD

**Issue by gc-ss** [kube-hetzner/terraform-hcloud-kube-hetzner#154]
> This project currently installs openSUSE MicroOS via the Hetzner rescue mode, making things a few minutes slower. If you could take a few minutes to send a support request to Hetzner, asking them to please add openSUSE MicroOS as a default image, not just an ISO. The more requests they receive, the likelier they are to add support for it, and if they do, that will cut the deployment time by half

I was wondering, instead of installing from ISO, we could installing from a snapshot we have built.

1. Would it decrease the deployment time?
2. installing from ISO takes the same time as installing from a snapshot, so there's no decrease in the deployment time?

**Comment by mysticaltech** [comment]
Imdeed, 2. Is the correct answer! All node get MicroOS installed in parallel. That means that if we were to use 1., It would take longer!

Ideally, Hetzner would support MicroOS as one of their default operating systems. I and another have asked, they said they do not have enough demands, so lets demand this.

Have explained the above request for help, at the bottom of the readme in the contribution section! If we successfully push for this, it will decrease the deploy time big time.
