### ISSUE TITLE
[Bug]: Unable to build MicroOs

### ISSUE THREAD

**Issue by cedric-lovit** [kube-hetzner/terraform-hcloud-kube-hetzner#1541]
### Description

When following the getting started steps, I'm unable to build the MicroOs. Before the reboot happens of the packer server, I'm able to ssh into the machine.

After reboot it's not possible.

I've tested this using packer build -debug and used the generated ssh key to ssh into the machine at first.

### Kube.tf file

```terraform
default one
```

### Platform

mac

**Comment by mysticaltech** [comment]
@cedric-lovit Make sure you use the `createkh` script. and if you encounter errors, open a new task with all the logs. Make sure you also follow the steps carefully in the readme.

**Comment by cedric-lovit** [comment]
Hello,

This "bug" wasn't actually a bug. It's working great.
My own router marked the packer server's ip addresses as threats so SSH was timing out.

Sorry for the inconvenience 

Kind regards,
Cedric
