### ISSUE TITLE
Agent 'storage' type - what his role?

### ISSUE THREAD

**Issue by eduscrakozabrus** [kube-hetzner/terraform-hcloud-kube-hetzner#156]

**Comment by mysticaltech** [comment]
It's just an example of agents that would be used exclusively as storage nodes.

**Comment by eduscrakozabrus** [comment]
Where find StorageClass for this role?

**Comment by diazoxide** [comment]
Any clear explanation?

**Comment by mysticaltech** [comment]
@diazoxide It's just an example. In Kubernetes, you can give arbitrary labels to nodes, but in that case, it's an example of a nodepools that was going to be used with Longhorn for storage.

**Comment by diazoxide** [comment]
> @diazoxide It's just an example. In Kubernetes, you can give arbitrary labels to nodes, but in that case, it's an example of a nodepool that was going to be used with Longhorn for storage.

Kudos !
