### ISSUE TITLE
[Bug]: Arm64 nodes hangs during creation, x86 works

### ISSUE THREAD

**Issue by kaotika** [kube-hetzner/terraform-hcloud-kube-hetzner#1585]
### Description

Hi, I created clean snapshots yesterday for both x86 and arm64. If I create a new cluster (3 control, 3 agents) using arm nodes only, tofu hangs in `hcloud_server.server: Still creating`. I still can't connect to the nodes manually via ssh. If I switch to x86 arch the same config comes up fine. Downgrading the terraform-hcloud-kube-hetzner module to 2.14.6 did'nt helper, nor does reducing the node count or the size of the nodes.
I did not realize any uncommen boot messages on the arm nodes. Can't give you more information, cause I can't connect to the server for more information. If I create a server from the arm snapshot manually and pass it my public key, I still can ssh connect to the node.

### Kube.tf file

```terraform
-
```

### Platform

Linux

**Comment by janfrederik** [comment]
Seems to be working fine for me now, with arm nodes.

Tested with the following kube.tf, which is as close as possible to the stock kube.tf:
```hcl
locals {
  hcloud_token = "xxxxxxxxxxx"
}

module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token

  source = "kube-hetzner/kube-hetzner/hcloud"

  ssh_public_key = file("~/.ssh/id_ed25519.pub")
  ssh_private_key = file("~/.ssh/id_ed25519")
  ssh_max_auth_tries = 5

  network_region = "eu-central"

  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cax11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "control-plane-nbg1",
      server_type = "cax11",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "control-plane-hel1",
      server_type = "cax11",
      location    = "hel1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]

  agent_nodepools = [
    {
      name        = "agent-small",
      server_type = "cax11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },
  ]

  load_balancer_type     = "lb11"
  load_balancer_location = "fsn1"

  system_upgrade_use_drain = true
  initial_k3s_channel = "v1.30"

  dns_servers = [
    "1.1.1.1",
    "8.8.8.8",
    "2606:4700:4700::1111",
  ]
}

provider "hcloud" {
  token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
}

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.43.0"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}

variable "hcloud_token" {
  sensitive = true
  default   = ""
}
```

**Comment by janfrederik** [comment]
@kaotika There were some problems with the k3s channel server. See https://github.com/k3s-io/k3s/issues/11421. Possibly the cause of your issue. I had similar problems as you and the channel server was the cause. Channel server is ok now, so best to try again ;-)

**Comment by tskimmett** [comment]
I'm experiencing the same. x86 servers get stuck too for me though.

**Comment by ViRb3** [comment]
If your `terraform apply` is getting stuck, then this is because you were unlucky and set up your cluster during the problematic window where k3s stable channel was pointing to the beta version `v1.30.7-k3s1` instead of the real stable version `v1.30.6-k3s1`. When k3s `system-upgrade-controller` runs, this requests a downgrade, however, as written in the official docs, this is not supported, and will in turn cordon your nodes:

> Kubernetes does not support downgrades of control-plane components. The k3s-upgrade image used by upgrade plans will refuse to downgrade K3s, failing the plan and leaving your nodes cordoned.

To check:

```sh
ubuntu@user:~$ kubectl get pods -n system-upgrade
NAME                                                              READY   STATUS    RESTARTS   AGE
apply-k3s-server-on-ip-172-31-0-16-with-7af95590a5af8e8c3-2cdc6   0/1     Error     0          9m25s
apply-k3s-server-on-ip-172-31-10-23-with-7af95590a5af8e8c-9xvwg   0/1     Error     0          14m
apply-k3s-server-on-ip-172-31-13-213-with-7af95590a5af8e8-8j72v   0/1     Error     0          18m
system-upgrade-controller-7c4b84d5d9-kkzr6                        1/1     Running   0          20m

ubuntu@user:~$ kubectl get nodes
NAME               STATUS                     ROLES                       AGE   VERSION
ip-172-31-0-16     Ready,SchedulingDisabled   control-plane,etcd,master   19h   v1.27.4+k3s1
ip-172-31-10-23    Ready,SchedulingDisabled   control-plane,etcd,master   19h   v1.27.4+k3s1
ip-172-31-13-213   Ready,SchedulingDisabled   control-plane,etcd,master   19h   v1.27.4+k3s1
ip-172-31-2-13     Ready                      <none>                      19h   v1.27.4+k3s1
```
Source: https://docs.k3s.io/upgrades/automated#downgrade-prevention

---

So, how to fix?

You first need to manually edit BOTH of your k3s `system-upgrade-controller` plans and replace their `version` or `channel` field with the newer version that you have:

```bash
kubectl -n system-upgrade edit plan k3s-server

# edit as follows:
apiVersion: upgrade.cattle.io/v1
kind: Plan
...
spec:
  ...
  version: v1.30.7-k3s1

kubectl -n system-upgrade edit plan k3s-agent
# same here
```

Once that's done, uncordon your nodes:

```bash
kubectl uncordon k3s-control-plane-fsn1-vkc
# and any others marked as "SchedulingDisabled" in the first command
```

That should fix it! If it's still stuck, do a cleanup:

```bash
kubectl -n system-upgrade delete jobs --all
kubectl -n system-upgrade delete pods --all
```

**Comment by ViRb3** [comment]
I also built a brand new cluster since then, and it worked as expected. Hard to say what's wrong without some logs, but I suspect it's a different issue.

**Comment by kaotika** [comment]
For me the setup now works. But I had to rebuild the snapshots (#1481). Most likely a very bad timing :D
