### ISSUE TITLE
mixed type of `extra_firewall_rules`

### ISSUE THREAD

**Issue by teliaz** [kube-hetzner/terraform-hcloud-kube-hetzner#159]
I run into a problem when I wanted to have mixed type of `extra_firewall_rules` 

Output of terraform plan 
```
The given value is not suitable for child module variable "extra_firewall_rules" defined at
│ .terraform/modules/kube-hetzner/variables.tf:115,1-32: all list elements must have the same type.
```

So I came up to this solution 

Instead of having the following (which caused the above error) 
```hcl
   {
      direction       = "in"
      protocol        = "tcp"
      port            = "5432"
      source_ips      = ["0.0.0.0/0", "::/0"]
     },
    {
      direction       = "out"
      protocol        = "tcp"
      port            = "22"
      destination_ips = ["0.0.0.0/0", "::/0"]
    }
  ```
  
  I matched the elements with the bellow 
  ```hcl
  {
      direction       = "in"
      protocol        = "tcp"
      port            = "5432"
      source_ips      = ["0.0.0.0/0", "::/0"]
      destination_ips = [] # Won't be used for this rule 
    },
    {
      direction       = "out"
      protocol        = "tcp"
      port            = "22"
      source_ips      = [] # Won't be used for this rule 
      destination_ips = ["0.0.0.0/0", "::/0"]
    }
 ```

I should contribute but I am not very experienced with terraform. Maybe a small update in the [example file](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/terraform.tfvars.example) to keep things simple. 

In case someone wonders why I need this rule for port 22, had to open access for ArgoCD (adding a github repo) 
Amazing work with this module! Thanks

**Comment by mysticaltech** [comment]
Good find @teliaz! And thank you for making me understand why ArgoCD was not connecting to SSH resources! 🤦🏻 :) Have fixed the example accordingly.
