### ISSUE TITLE
[REQ] Ability to install Longhorn to use local storage for volumes

### ISSUE THREAD

**Issue by karbowiak** [kube-hetzner/terraform-hcloud-kube-hetzner#160]
Hello there,

I just tried installing Longhorn onto the cluster, but during driver-deployment it hangs itself and waits forever - which if i remember correctly is because open-iscsi is missing on the system (OR it can't find a path, but that usually comes with a different error 😅)

Is there a way to install open-iscsi onto the nodes so Longhorn can run, or is there something bigger preventing Longhorn from working.

Would be lovely to have some volumes locally and others in hcloud, both money and performance wise 😄

**Comment by mysticaltech** [comment]
@karbowiak Try installing open-iscsi at this level: 

https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/5087c15bf20754d73ee0c42a8d3e5b06721baac7/modules/host/main.tf#L71-L73

Do it by adding the following command to the command array there: 

`transactional-update pkg install open-iscsi
`
And if it works for you, please submit a PR.

**Comment by mysticaltech** [comment]
Hey @karbowiak, do you need help with this? Ideally, please do try it, and if you can make Longhorn work with this, I will commit it to the repo and release a new minor version of the module.

**Comment by karbowiak** [comment]
@mysticaltech hey! thanks for the example - i'll totally give it a try this weekend ! :D

And yes, if it all works out - i'll see if i can't make it nice with a kustomize and some enable/disable flags and make a pull request :)

**Comment by mysticaltech** [comment]
Sounds like a plan!!

**Comment by skriems** [comment]
I'm currently looking into this as well. What I've got so far is

```
# Install open-iscsi
  provisioner "remote-exec" {
    inline = [
      "set -ex",
      "transactional-update pkg install -y open-iscsi",
      "systemctl enable iscsid",
      "systemctl start iscsid",
    ]
  }
```
This worked manually on one node so I think this is fine and doesn't need a restart or anything. Will continue on the others, deploy longhorn and report back how it goes

**Comment by mysticaltech** [comment]
Good to hear; yes, the way MicroOS works, it needs to restart after any installation of packages to commit the new snapshot. It's a transactional system.

Best to do the installation at https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/5087c15bf20754d73ee0c42a8d3e5b06721baac7/modules/host/main.tf#L71-L73, as stated above.

For the reboot, it's already being done after the above point, so that is already taken care of. 

And for `systemctl enable --now iscsid`, it has to be later in the code, after the reboot, so maybe just create a new remote-exec at the end of the file above, just for that!

**Comment by skriems** [comment]
exactly that worked. And then I installed Longhorn usinge a `helmfile` like

```
---
helmDefaults:
  timeout: 3600
  wait: true
  force: false
  atomic: true

repositories:
  - name: longhorn
    url: https://charts.longhorn.io 

releases:
  - name: longhorn
    namespace: longhorn
    chart: longhorn/longhorn
```
although I would prefer to have it as a kustomization I guess. I like the idea that everything related to infrastructure could be a kustomization and apps are installed via helm... /shrug. But it works great. With k9s I was easily able to create a port forward and view the UI. Loving it ❤️

**Comment by skriems** [comment]
I said "exactly that worked" ... tbh I haven't tried spinning up a cluster from scratch but by logic it _should_ work ;)

**Comment by mysticaltech** [comment]
Awesome! I believe this kind of "addons" being installed by helm is a decent solution! 

This is what AWS does for EKS over here https://aws-ia.github.io/terraform-aws-eks-blueprints/add-ons/. And this is the direction that I would like to take for this project, as it also makes the addons easier to maintain, customize, and upgrade.

**Comment by karbowiak** [comment]
Found time to have a look at both of your comments, and gave it a shot at implementing it.

Literally the first time writing anything for Terraform, or using Helmfile for that matter 😅 
So please do let me know if there is something i can do better, and i'll definitely do it 😄

**Comment by mysticaltech** [comment]
Again, amazing work @karbowiak! Longhorn is a major win for this repo.

**Comment by karbowiak** [comment]
np @mysticaltech - happy to help..

Now, where do you land on making the CCM replaceable with MetalLB ? 😂 
Oh and getting rid of Traefik in exchange for Nginx-Ingress + CertManager ? 😅

**Comment by mysticaltech** [comment]
@karbowiak Have a look at https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/176. Cert-manager is already coming down the pipe! :) 

Nginx-Ingress, yes, Sir, please shoot!

Metal LB is not needed cause the cluster already comes with KlipperLB, which is used for single-node clusters (try deploying a single cluster to see it live). It would be great to make this optional even for more nodes.

All of the above, yes, Sir! But... Not dropping the CCM altogether, as it is very useful to take care of the private networking routes node tagging, etc. It does plenty of continuous magic under the hood to integrate well with Hetzner. But we can definitely do without the Hetzner LB, optionally.

**Comment by karbowiak** [comment]
@mysticaltech oohh neat!

I'll definitely give nginx-ingress a whack then, and thanks for the invite! 🥳 

.. i wonder what this button does 😂

**Comment by mysticaltech** [comment]
Perfect man! Now you can create branches, and do lots of good stuff, and don't forget to target `staging` as before!

I am hesitating about adding `external_dns`, too; I think it's pretty useful to have included. The only thing I am pondering on is to include a basic setup for Cloudflare, or other massively used DNS providers, out of the box or not. 

That said, it's probably wise to have one example `HelmChartConfig` for each addon that we support so that folks can later change the config easily.

**Comment by mysticaltech** [comment]
@karbowiak Now that you're part of the team, you can also join our private chat room; it's helpful for direct comms and sharing of info! https://matrix.to/#/#kube-hetzner:matrix.org

_Will delete this comment after you've joined!_
