### ISSUE TITLE
[REQ] set ssh key by string and not by file path

### ISSUE THREAD

**Issue by batthebee** [kube-hetzner/terraform-hcloud-kube-hetzner#161]
I want to use your environment to set up multiple clusters. The ssh keys should be created dynamically with `tls_private_key`, each host a different one. 

Now I would have to generate the key and write it to a file, which I pass to the module, which generates noise on each ci run and is overall quite unattractive.

Do you have a better suggestion? Or should I adapt the module so that it also accepts ssh keys as string?

**Comment by batthebee** [comment]
I took a closer look and saw that you also need to access the cluster via ssh. So the local ssh key is needed. I close the issue again.

**Comment by mysticaltech** [comment]
Having access to keys as string would be a sweet option to have. 

It needs to be ed25519 and passphrase-less in order to work without SSH agents. 

And for local use, it's easy in bash to makes strings look as files!


PR welcome and appreciated.

**Comment by mysticaltech** [comment]
Done in #204 🎯
