### ISSUE TITLE
[REQ] loop over module

### ISSUE THREAD

**Issue by batthebee** [kube-hetzner/terraform-hcloud-kube-hetzner#164]
As of terraform 0.13 it is possible to loop over modules (for_each etc.). Unfortunately there must not be a provider configuration inside the module.

I would like to use your project for setting up several similar clusters and implement this via for_each. 
I could provide a PR that moves the provider configuration into the examples. What do you think?

**Comment by mysticaltech** [comment]
I would be very curious about that, if we do not lose functionality and only gain some, it would be great! Please shoot a PR.

**Comment by mysticaltech** [comment]
Hey @batthebee, please do join us on https://matrix.to/#/#kube-hetzner:matrix.org, it's a chat room for Kube-Hetzner core! Would love to chat with you there :) 🙏

**Comment by mysticaltech** [comment]
This can now be done since the new release 1.2.0! Please reopen if not the case.
