### ISSUE TITLE
[REQ] add more (all) k3s channels for kubernetes version

### ISSUE THREAD

**Issue by batthebee** [kube-hetzner/terraform-hcloud-kube-hetzner#165]
In my cluster, we are installing components that are not currently running on kubernetes >v1.21. however, the stable channel is already on v1.22.x. K3s itself offers additional channels like v1.21. But these are not allowed in the channel variable. 

I could provide a PR that adds the missing channels to the variable. What do you think?

**Comment by mysticaltech** [comment]
@batthebee I thought there were just `stable` `latest`, `testing`. If there are more, like those for specific versions, I do not see any harm in adding them. Please shoot away a PR.
