### ISSUE TITLE
[REQ] import into rancher

### ISSUE THREAD

**Issue by batthebee** [kube-hetzner/terraform-hcloud-kube-hetzner#166]
Our clusters are managed via rancher. The created K3s cluster can be imported successfully with a few modifications.

I could either offer a PR that optionally does full registration in rancher at the same time ( create rancher cluster and import k3s ) or just customize the few places (set the rights of kubeconfig).

What do you think about this?

**Comment by mysticaltech** [comment]
Yes, Sir! :) OOTB support for Rancher would be awesome. Why not even an option of automatically deploying it. Do as you see fit, this project needs to support real world scenarios like the ones you are exposing.

**Comment by strowi** [comment]
Both solutions would be very useful. (I am currently planning on moving some Clusters from our rancher/bare-meta/datacenter -> hcloud ) and still trying to wrap my head around the ui-node-driver or importing the cluster afterwards (besides the hetzner-controller etc..).

Im guessing deploying rancher ist very simple, since it is just a helm deployment, just have to figure out the ssl/letsencrypt part.

```bash
helm install rancher-stable/rancher \
  --name rancher \
  --namespace cattle-system \
  --set hostname=rancher.xyz.net \
  --set ingress.tls.source=secret
```

The importing although needs a token from the rancher. I'd be very interested if there are any additional steps besides running the agent @batthebee .

**Comment by batthebee** [comment]
@strowi  I had a few problems with the ui-node-driver+dockermachine setup, one i could not fix or work around unfortunately. When creating a cluster via terraform I always had the error message: "default-token already in use".

I then switched to setting up the clusters externally and only importing them. That worked right away.

I am currently building a module to set up rancher via terraform. When it's ready, I'll post the link to the repo here. I hope, I am Sunday ready.

**Comment by batthebee** [comment]
@strowi  There was almost nothing else to do. Additionally only the rights for the node kubeconfig must be set (see k3s docs). I hope that I can also make a PR until Sunday.

**Comment by batthebee** [comment]
> Yes, Sir! :) OOTB support for Rancher would be awesome. Why not even an option of automatically deploying it. Do as you see fit, this project needs to support real world scenarios like the ones you are exposing.
@mysticaltech 
Do I understand you correctly that you want to have an optional Rancher installation within the module? My feeling is that this is better off in its own repo. Currently the module does exactly one thing, set up a k3s cluster on top of hetzner, which I personally like.

If you want to support rancher here, I would suggest we do that in a second repo.

In this repo only the read-write to the node kubeconfig necessary for rancher goes.

In the second repo I would build two modules, one that registers a cluster with terraform and a second that sets up terraform on such a cluster (and registers itself at the same time).

What do you think?

**Comment by mysticaltech** [comment]
I did not understand exactly what you meant, but compartmentalizing stuff is a good idea. 

If we can have a second repo that can run rancher to manage a kube-hetzner cluster, it would be awesome!

You have great ideas @batthebee!

**Comment by mysticaltech** [comment]
@batthebee Have invited you to join the org so that you can initiate the second repo for the above if you are inspired.

Welcome to Kube-hetzner ! :)

**Comment by batthebee** [comment]
Thanx! :)

**Comment by mysticaltech** [comment]
Hey folks, just wanted to share that in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/173, we actually deployed a helm chart with a simple YAML `HelmChart` definition. So no need to use the command line cli, that is a major simplifier IMHO!

**Comment by mysticaltech** [comment]
I understand that probably it's not wise to install Rancher on the cluster itself, but just felt I needed to share the above info. It may be useful in another context.

**Comment by mysticaltech** [comment]
Ah, I retract what I said above, as the author of this [video](https://www.youtube.com/watch?v=eKBBHc0t7bc) does, it's pretty nice to have rancher run on the cluster itself too. But definitely not mandatory!

Probably that is a use case different from what you are proposing here @batthebee. Both seem very interesting! 

Probably just deploying Rancher into the cluster can be done very easily with a HelmChart declaration, and a flag variable. Will try that in a separate PR as soon as I can.

**Comment by mysticaltech** [comment]
Finally, will just install it via the helm cli, that way it's easier to get the whole ingress config right. It's not really something that can be automated to the point of an HelmChart YAML file.

Basically, the only thing required here @batthebee is to make this cluster compatible to be imported in a third-party Rancher install. As you said, formatting the kubeconfig well... etc.  That would indeed be awesome!

**Comment by strowi** [comment]
Good work! ;)
Just to clean this up (hopefully) - having worked with rancher for +5y, the the difference between same cluster and extra-cluster is "just" for security and stability issues. 
It is best practice to have a separate management-cluster running only rancher. This prevents high workloads etc, from interfering with it (or developers from deleting the rancher-daemonset :) ).
It might be possible to get the rancher-agent token via the terraform-module (haven't checked this yet) and deploy the agent accordingly.

**Comment by mysticaltech** [comment]
Thanks for clarifying the matter @strowi! That makes perfect sense. 

In that case, the ideal scenario would be a single node cluster for Rancher only (the beauty of single-node clusters is that it uses Klipper as LB, so removes the need for a Hetzner LB, hence dropping the cost even more).

And now that we have support for Longhorn, we can set up an automatic backup of PVCs to any S3 compatible endpoint, and make everything even more robust.

**Comment by strowi** [comment]
@mysticaltech depends on definition of "ideal scenario" ;) In production you'd probably want at least a 3-node rancher cluster for high-availability if this is a developers only access to the downstream clusters. But that setup really wouldn't differ i guess.

Backups of pvcs are neat and definitely useful! Although i've had a lot of trouble with longhorn itself (very high cpu usage for keeping the disks in sync, etc), i think it is very easy to setup. (Otherwise i can recommend restic/velero for backups)

**Comment by mysticaltech** [comment]
Awesome @strowi!! Thanks for sharing your production experience. It's invaluable!

**Comment by strowi** [comment]
happy to help;)

**Comment by mysticaltech** [comment]
@batthebee @strowi Have added the possibility to deploy Rancher locally. Please do not hesitate to suggest changes. https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/176

It does not answer the requirement of that issue, but at least it's great to have Rancher!
