### ISSUE TITLE
[REQ] optionally provide hetzner_ssh_key

### ISSUE THREAD

**Issue by batthebee** [kube-hetzner/terraform-hcloud-kube-hetzner#167]
If I want to create multiple clusters I currently need several different ssh keys, because hcloud does not allow to store multiple keys with the same fingerprint. 

I could create a PR that optionally passes the id of the key used and then does not store a new key in hcloud.

What do you think?

**Comment by mysticaltech** [comment]
Sounds good; the id could help differentiate the keys.

Also, maybe autogenerating the keys with https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key would be an option here, and store them in an array.

For instance, we could do that if both the `public_key` and `private_key` variables are left blank.

Please submit a PR; that's a completely valid use case.

**Comment by mysticaltech** [comment]
That also re-joins your proposal of having the keys as strings. This would indeed be doable; see my answer here https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/161#issuecomment-1109531226.

**Comment by mysticaltech** [comment]
@batthebee In your coming PR(s), please target the `staging` branch 🙏

**Comment by batthebee** [comment]
@mysticaltech you mentioned on #161 for local use, it's easy in bash to makes strings look as files!

How does it Work?

**Comment by mysticaltech** [comment]
Yep, basically you use cat and the string enclosed in EOF. See https://unix.stackexchange.com/questions/505828/how-to-pass-a-string-to-a-command-that-expects-a-file

**Comment by strowi** [comment]
This would be greatly appreciated, since i am currently testing everything in a single project...

**Comment by mysticaltech** [comment]
Done in #204, thanks @batthebee! 👏
