### ISSUE TITLE
Failed to sync network policy chains

### ISSUE THREAD

**Issue by ignasiadell** [kube-hetzner/terraform-hcloud-kube-hetzner#168]
Hello,

I have been testing the kubernetes cluster with the example provided in the folder examples/tls , I apply the yaml files and everything it's ok.

Cluster setup:

module "non-core-kube-hetzner" {
  source  = "kube-hetzner/kube-hetzner/hcloud"

  cluster_name = "non-core-kube-hetzner"
  hcloud_token = "${var.hcloud_api_token}"
  public_key   = "/home/gisystem/.ssh/id_ed25519.pub"
  private_key  =  "/home/gisystem/.ssh/id_ed25519"
  network_region   = "${var.network_region}"

  control_plane_nodepools = [
    {
      name        = "control-plane",
      server_type = "${var.plans["server_control_plane"]}",
      location    = "${var.location}",
      labels      = [],
      taints      = [],
      count       = 3
    }
  ]

  agent_nodepools = [
    {
      name        = "agent",
      server_type = "${var.plans["server_control_agent"]}",
      location    = "${var.location}",
      labels      = [],
      taints      = [],
      count       = 3
    }
  ]

  load_balancer_type     = "${var.plans["lb"]}"
  load_balancer_location = "${var.location}"

}

Cluster information after apply it:

xxx@stg-devops-s1:~$ kubectl get pods
NAME    READY   STATUS    RESTARTS   AGE
nginx   1/1     Running   0          60m

xxx@stg-devops-s1:~$ kubectl get services
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes      ClusterIP   10.43.0.1       <none>        443/TCP   4h39m
nginx-service   ClusterIP   10.43.240.240   <none>        80/TCP    60m

xxx@stg-devops-s1:~$ kubectl get ingress
NAME            CLASS    HOSTS              ADDRESS                              PORTS     AGE
nginx-ingress   <none>   test.gi-stg.site   162.55.155.95,2a01:4f8:1c1d:aea::1   80, 443   60m

When I want to test if I see the nginx server I add the test entry to the domain gi-stg.site with the ip 162.55.155.95

If I try to access it, the result is an error code 404 page not found.

If I access an agent server and do a: lynx 10.43.240.240  It works and I see the nginx welcome page.

As I understand, I have some problem with traefik and routes or how test.gi-stg.site resolves it to the kubernetes cluster.

If I review journal-ctl in agents and control node pools I see this error:

Apr 28 09:01:38 non-core-kube-hetzner-control-plane-jbu k3s[2009]: E0428 09:01:38.288947    2009 network_policy_controller.go:248] Aborting sync. Failed to sync network policy chains: %!v(MISSING)ipset v7.6: Kernel and userspace incompatible: settype hash:ip with revision 5 not supported by userspace.

Apr 28 09:13:27 non-core-kube-hetzner-agent-fmd k3s[1593]: E0428 09:13:27.480241    1593 network_policy_controller.go:248] Aborting sync. Failed to sync network policy chains: %!v(MISSING)ipset v7.6: Kernel and userspace incompatible: settype hash:ip with revision 5 not supported by userspace.

I'm not sure, but I think if I resolve this problem the deployment will work. Any help would be appreciated. Thanks!

Regards

**Comment by ignasiadell** [comment]
Sorry! I'm a new baby in Kubernetes....I see that is working with https://test.gi-stg.site/

Apart from that....why I see this errors:

Apr 28 09:01:38 non-core-kube-hetzner-control-plane-jbu k3s[2009]: E0428 09:01:38.288947 2009 network_policy_controller.go:248] Aborting sync. Failed to sync network policy chains: %!v(MISSING)ipset v7.6: Kernel and userspace incompatible: settype hash:ip with revision 5 not supported by userspace.

Apr 28 09:13:27 non-core-kube-hetzner-agent-fmd k3s[1593]: E0428 09:13:27.480241 1593 network_policy_controller.go:248] Aborting sync. Failed to sync network policy chains: %!v(MISSING)ipset v7.6: Kernel and userspace incompatible: settype hash:ip with revision 5 not supported by userspace.

**Comment by mysticaltech** [comment]
Hello @ignasiadell, glad you solved your ingress issue.

If you do not use the network policy, just disable it by adding this variable `disable_network_policy = true` to your config file. That should completely remove the error you have.

I am not very familiar with network policy myself, but I would guess that it's best to just disable it if it's not used. I will probably change that value to be automatically disabled by default.

**Comment by mysticaltech** [comment]
I'm considering this solved, please do not hesitate to re-open if not.
