### ISSUE TITLE
Calico subnet performance

### ISSUE THREAD

**Issue by HenkVanMaanen** [kube-hetzner/terraform-hcloud-kube-hetzner#169]
Is it a problem that Calico uses 192.168.0.0 subnet instead of the 10.0.0.0 subnet? For example is it faster to go through the private network or are requests always routed over the private hetznet network.

**Comment by mysticaltech** [comment]
Definitely, not supposed to happen! Internal communication should be only private network!

@nupplaphil FYI, maybe Calico needs to be configured to work on the private network only.

**Comment by mysticaltech** [comment]
@HenkVanMaanen Thanks for catching this, and @nupplaphil thanks again for the awesome fix! 🙏✨
