### ISSUE TITLE
Add-on request: Teleport

### ISSUE THREAD

**Issue by anishdcruz** [kube-hetzner/terraform-hcloud-kube-hetzner#177]
Many thanks for your wonderful effort, which is assisting me greatly in my K8s learning :)

I would like to request a Teleport add-on to secure the cluster.

**Comment by mysticaltech** [comment]
@anishdcruz I've decided not to support more addons out of the box for this project, as these can be set up with helm or via the Rancher that we now support (and which also uses helm behind the scenes). Hence closing this issue. Thanks for your understanding.
