### ISSUE TITLE
Terraform stuck at "waiting for reboot"

### ISSUE THREAD

**Issue by 0xbrigles** [kube-hetzner/terraform-hcloud-kube-hetzner#178]
Hey there
i wanted to test the project but I am stuck after the server get provisionized.

what have i done:
1. created the API token in a new project
2. generated a new ED25519 passwordless shh key pair
3. copied and edit the `terraform.tfvars`
4. fired up terraform

Everything seems to run. I saw the created servers but even after 30min. terraform is waiting for MicroOS to reboot.
I've tried this setup a few times (deleted the whole project and started from scratch)

The only message i've got after a few minutes is:
```
module.agents["2-0-storage"].hcloud_server.server: Still creating... [31m40s elapsed]
module.agents["1-0-agent-large"].hcloud_server.server: Still creating... [31m40s elapsed]
module.agents["0-0-agent-small"].hcloud_server.server: Still creating... [31m40s elapsed]
module.control_planes["2-0-control-plane-hel1"].hcloud_server.server (local-exec): Waiting for MicroOS to reboot and become available...
module.agents["0-0-agent-small"].hcloud_server.server (local-exec): Waiting for MicroOS to reboot and become available...
module.control_planes["1-0-control-plane-nbg1"].hcloud_server.server (local-exec): Waiting for MicroOS to reboot and become available...
module.agents["1-0-agent-large"].hcloud_server.server (local-exec): Waiting for MicroOS to reboot and become available...
module.control_planes["2-0-control-plane-hel1"].hcloud_server.server: Still creating... [31m40s elapsed]
module.control_planes["1-0-control-plane-nbg1"].hcloud_server.server: Still creating... [31m40s elapsed]
module.control_planes["0-0-control-plane-fsn1"].hcloud_server.server: Still creating... [31m40s elapsed]
```

Am i doin it wrong or is that a bug?

* Operating System: Arch Linux
* hcloud version:  1.29.0
* terraform version: v1.1.9

**Comment by anish-dcruz** [comment]
@0xbrigles I had the same issue, it because of too many authentication failure by terraform. Eventually after few tries it worked for me.
There should be 60s sleep in terraform after reboot.

https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/174

**Comment by 0xbrigles** [comment]
> 

thanks for your fast reply. thats a good point. will keep trying and report back.

**Comment by mysticaltech** [comment]
@0xbrigles Destroy, make sure you choose the right SSH key, and try again with the latest terraform on a unix shell. Meaning either, mac, linux, or wsl.

**Comment by 0xbrigles** [comment]
thanks for the hint @mysticaltech 
it solved my problem. 
cleared `ssh-agent` > works :100:
