### ISSUE TITLE
[REQ] Directory Layout

### ISSUE THREAD

**Issue by batthebee** [kube-hetzner/terraform-hcloud-kube-hetzner#179]
regarding #164 #167 
I'll try to describe the problem and my thoughts about it:

The changes would change the interface to the outside (vars), making this no longer backward compatible. 

SSH Key:

the actual content should be included in the terraform.tfvars.example instead of the path.

Module Loop:

for this I would have to remove the provider.tf (or rename it to provider.tf.example), because loops only work, if there is no provider definition in the module. 

How do we want to handle this? 

Option 1: 

The easiest way is to adjust it as described above. 
I adjust the tfvars.example, that there is no path but a ssh key directly in it. I rename the provider.tf to provider.tf.example and document it accordingly.

The advantage here is that not much changes to the outside. The user must adjust two instead of one file and can start as usual.

Option 2:

 We move the setup into the example folder and make the module "clean". Could for example then create an example for single-node-custer, ha-cluster and rancher. In the examples then a main.tf is created in each case, which can contain then also again e.g. the ssh path by "file(path/to/ssh)". provider.tf would land then also here. 

I personally like option 2 more, because that separates the module cleanly, but is also more maintenance. 

The great documented "terraform.tf.example" I would either let live in the root or move the infos into the variables.tf (preferred). When moving to the variables.tf we could generate the documentation e.g. via https://github.com/terraform-docs/terraform-docs.

Many questions ;-) What do you think?

**Comment by mysticaltech** [comment]
@phaer What do you think of the above proposals?

**Comment by mysticaltech** [comment]
@batthebee What do you say we give it a shot in another test repo, just to see if terraform recognizes it as a publishable module! What do you say?

**Comment by batthebee** [comment]
yes, good idea. Let's do it like this.

**Comment by mysticaltech** [comment]
@batthebee Option 1 has been shipped! :)
