### ISSUE TITLE
BotKube reports errors for system-upgrade job of storage node

### ISSUE THREAD

**Issue by skriems** [kube-hetzner/terraform-hcloud-kube-hetzner#181]
Hey,

I've added BotKube to my cluster and it constantly reports errors regarding the update Job of the storage node:

```
v1/pods error
Error Occurred in Pod: system-upgrade/apply-k3s-agent-on-k3s-storage-rrz-with-1b39df95bca3c0-5vwh7 in k3s cluster

0/7 nodes are available: 1 node(s) had taint {server-usage: storage}, that the pod didn't tolerate, 3 node(s) didn't match Pod's node affinity/selector, 3 node(s) had taint {[node-role.kubernetes.io/master](http://node-role.kubernetes.io/master): }, that the pod didn't tolerate.
```

I wonder if this is a real error. I could prevent this by disabling upgrades of the storage node, or disabling botkube to report this error on the _system-upgrade_ namespace.

Another question came to mind now that we have longhorn: If enabled, wouldn't it make more sense to have more storage on each node, instead of a big storage node?

**Comment by mysticaltech** [comment]
@skriems Good catch! That is generated by the system upgrade controller, which checks and upgrades Kube's version.

You have two upgrade plans loaded; you can customize them, and change them to tolerate the storage taint. More here https://rancher.com/docs/k3s/latest/en/upgrades/automated/

To list the plans, you can use `kubectl get plan -n system-upgrade`.

About longhorn, we can really choose the size of the disk, just the size of the machine kind, but what we could do, is to create and attach volumes! Maybe that would be useful? But I guess it's simpler to just add these manually, as they might just be a one-off; maybe I am wrong?!

**Comment by skriems** [comment]
@mysticaltech So I shall consider this as being a bug and that it's not intended, right?

via `kubectl -n system-upgrade edit plan k3s-agent` I added

```
spec:
  ...
  tolerations:
  - effect: NoSchedule
    key: server-usage
    operator: Equal
    value: storage
```

and now the error is not reported any more. Definitely the best option as I wouldn't want to ignore the whole system-upgrade namespace. If that's something that should be fixed here I could create a PR (or you just push the 5 lines to prod :P )

Regarding longhorn I think attaching volumes makes perfect sense (if longhorn detects the additional space; haven't tested yet)

**Comment by mysticaltech** [comment]
Awesome! PR to staging if you can! :) Will merge without testing.

**Comment by skriems** [comment]
👍 PR is open

**Comment by mysticaltech** [comment]
Merged! 🙏
