### ISSUE TITLE
It is possible to auto provision Hetzner AX-Line server as worker node?

### ISSUE THREAD

**Issue by yashodhank** [kube-hetzner/terraform-hcloud-kube-hetzner#183]
I am interested in knowing it is possible to also provision Hetzner AX series server as worker node? What would be best way to provision it?
I am new to Kubernetes and still exploring, I find your provisioning solution is really amazing and works really well with hcloud ecosystem. Thank you so much for sharing it..

**Comment by mysticaltech** [comment]
Hello @yashodhank, unfortunately we do not support it as the Hetzner terraform provider does not.

However please look at the dedicated vCPU machine types (like ccx22) in their cloud offering, those are supported and seem to have similar specs and pricing.

**Comment by yashodhank** [comment]
Thanks again! wonderful!
