### ISSUE TITLE
Gihub rate-limit

### ISSUE THREAD

**Issue by strowi** [kube-hetzner/terraform-hcloud-kube-hetzner#185]
Hi,

i took some time this weekend trying to add support for haproxy-ingress (since we're using it currently).
During testing i ran into a nasty problem where terraform plan/apply was stuck.
Running it with `TF_LOG=1 terraform plan` revealed the github-provider was being rate-limited and everything was just idling until...

```
2022-05-15T13:17:25.065+0200 [DEBUG] provider.terraform-provider-github_v4.24.1: 2022/05/15 13:17:25 [DEBUG] Rate limit 60 reached, sleeping for 24m33.934955317s (until 2022-05-15 13:41:59.000000851 +0200 CEST m=+1474.193016208) before retrying`
```

It seems this is only used to get the github_releases for ccm/csi/kured. 
Although 60 seems weirdly low, it seems this is produced by github_release for ccm/csi/kured .
Maybe this could be removed made a static variable (this would also improve reliability, since "latest" is kinda not best-practice similar to docker-tags).

I can provide a MR if you agree with this... ;)

regards,
strowi

**Comment by mysticaltech** [comment]
Hey @strowi, I've heard of this problem before; apparently, just setting the Kured version in the variables will fix this (that's why this variable was added by another member). Try it!

**Comment by strowi** [comment]
Thx @mysticaltech - i didn't see the *_version  variables, sorry. Should've looked closer.;)
