### ISSUE TITLE
LB is not created and waits to get an IP

### ISSUE THREAD

**Issue by cruex-de** [kube-hetzner/terraform-hcloud-kube-hetzner#192]
I have now a few times the cluster destroyed, the locations and the size of the LB's changed or all traefik settings disabled.... Unfortunately still without success, it always comes the same error message. However, the LB is also not created at Hetzner.

Version: v1.1.8

```
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization: Still creating... [3m0s elapsed]
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization: Still creating... [3m10s elapsed]
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization: Still creating... [3m20s elapsed]
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
╷
│ Error: remote-exec provisioner error
│
│   with null_resource.kustomization,
│   on init.tf line 196, in resource "null_resource" "kustomization":
│  196:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_1856610513.sh": Process exited with status 124
```

**terraform.tfvars:**
network_region = "eu-central"
load_balancer_type     = "lb21"
load_balancer_location = "nbg1"
traefik_acme_tls = true
traefik_acme_email = "admin@mail.com"
traefik_enabled = true
traefik_additional_options = []

**Comment by mysticaltech** [comment]
Hey @cruex-de, please try removing those (just delete the line, destroy and redeploy):

traefik_acme_tls = true
traefik_acme_email = "[admin@mail.com](mailto:admin@mail.com)"
traefik_enabled = true
traefik_additional_options = []

For TLS it's best to use cert-manager anyways!

**Comment by cruex-de** [comment]
> traefik_enabled = true

Default is true, so set to false?

**Comment by mysticaltech** [comment]
Ok, just out of curiosity, can you share most of your variables? 

And also try with another location, like fsn1, last but not least, make sure to use the latest version.

**Comment by mysticaltech** [comment]
The way I see it, your agent node pools are all tainted with no schedule, that could be the reason!

**Comment by mysticaltech** [comment]
Try my variables and rebuild towards yours!

hcloud_token = "xxxx"
public_key   = "/home/karim/.ssh/id_ed25519.pub"
private_key  = "/home/karim/.ssh/id_ed25519"

network_region = "eu-central"

control_plane_nodepools = [
  {
    name        = "control-plane",
    server_type = "cx21",
    location    = "fsn1",
    labels      = [],
    taints      = [],
    count       = 3
  }
]

agent_nodepools = [
  {
    name        = "agent",
    server_type = "cx21",
    location    = "fsn1",
    labels      = [],
    taints      = [],
    count       = 2
  }
]


load_balancer_type     = "lb11"
load_balancer_location = "fsn1"

cluster_name = "test12"

extra_firewall_rules = [
  # For Postgres
  {
    direction       = "in"
    protocol        = "tcp"
    port            = "5432"
    source_ips      = ["0.0.0.0/0", "::/0"]
    destination_ips = [] # Won't be used for this rule 
  },
  # To Allow ArgoCD access to resources via SSH
  {
    direction       = "out"
    protocol        = "tcp"
    port            = "22"
    source_ips      = [] # Won't be used for this rule 
    destination_ips = ["0.0.0.0/0", "::/0"]
  }
]

enable_rancher          = false
rancher_install_channel = "latest"
rancher_hostname        = "rancher.domain.dev"

**Comment by cruex-de** [comment]
Thanks, now its working 🥳
