### ISSUE TITLE
Terraform 1.2.0 compatibility

### ISSUE THREAD

**Issue by strowi** [kube-hetzner/terraform-hcloud-kube-hetzner#193]
With 1.2.0 i am getting the following when using it as a module.  Not sure yet how the upgrade-path should look like. Have to investigate..

```
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Module is incompatible with count, for_each, and depends_on
│ 
│   on ../modules/kube-hetzner/control_planes.tf line 4, in module "control_planes":
│    4:   for_each = local.control_plane_nodes
│ 
│ The module at module.rancher is a legacy module which contains its own local provider configurations, and so calls to it may not use the count, for_each, or depends_on arguments.
│ 
```

**Comment by mysticaltech** [comment]
@strowi It's weird. I do not remember we used a module called "rancher". You ran `terraform init -upgrade' correct?

@batthebee What you mentioned in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/179 about removing calls to providers is probably needed for new versions of Terraform. What do you think?

**Comment by mysticaltech** [comment]
That seems to be a far deeper problem; we may need to remove the internal server module, to make the project compatible with Terraform 1.2.0, or maybe there is another way? We publish the server module on Terraform cloud...

@mnencia @phaer, what do you think folks?

**Comment by mysticaltech** [comment]
It would be kind of cool to dissociate the `host` module, and make it public, as it could be used in a non-Kube context. I will attempt that ASAP, but please do not hesitate to attempt it yourself.

We could call it `terraform-hcloud-microos`, which would be a second repo in this project.

**Comment by mysticaltech** [comment]
That would be a great move for our 1.2.0 release!

_FYI, for new PRs, please target the staging branch @strowi._

**Comment by mysticaltech** [comment]
Or we need to investigate why it thinks that it's a legacy module! And upgrade that module! Much simpler.

**Comment by phaer** [comment]
Yes, I think so too. Just was about to psot the same link

**Comment by mysticaltech** [comment]
Ok, I made it work; I will post the PR right away. That is in line with what we previously discussed @batthebee, so our tool should soon become compatible with Terraform cloud 🥳🤞

**Comment by mysticaltech** [comment]
@strowi Please test PR #194; it should work. Note that you have to delete to use the new module format, as described here https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/new-module-format/kube.tf.example.

@batthebee Whenever you have time, please let me know if that did indeed advance #179; I think it takes us at least halfway there!

@phaer, and anyone else on the team, needless to say, your inputs are always appreciated!

**Comment by mysticaltech** [comment]
Fixed in #194.

**Comment by 0xCiBeR** [comment]
Seems to not be working. Following docs leads to terraform asking for vars, and when suppying them manually, you get this
`╷
│ Error: Invalid function argument
│
│   on locals.tf line 69, in locals:
│   69:   control_plane_count    = sum([for v in var.control_plane_nodepools : v.count])
│     ├────────────────
│     │ var.control_plane_nodepools is empty list of dynamic
│
│ Invalid value for "list" parameter: cannot sum an empty list.
╵
╷
│ Error: Invalid function argument
│
│   on locals.tf line 70, in locals:
│   70:   agent_count            = sum([for v in var.agent_nodepools : v.count])
│     ├────────────────
│     │ var.agent_nodepools is empty list of dynamic
│
│ Invalid value for "list" parameter: cannot sum an empty list.`

**Comment by mysticaltech** [comment]
@0xCiBeR Did you upgrade to the latest version, and created a new kube.tf file, as described in the readme? Basically, just copy the kube.tf.example and complete it.

**Comment by strowi** [comment]
It works here with 1.2.0. Maybe add a required_version for terraform to prevent this kind of issue (should work in a module too right?).
That would also allow [tfswitch](https://tfswitch.warrensbox.com/) to decide automatically which terraform-version to use.

**Comment by 0xCiBeR** [comment]
> @0xCiBeR Did you upgrade to the latest version, and created a new kube.tf file, as described in the readme? Basically, just copy the kube.tf.example and complete it.

Using terraform 1.2.0, tried also with 1.1.9 with no luck. I created a new kube.tf file(this is a new setup, and completed it) and i put that file in a new folder

**Comment by 0xCiBeR** [comment]
Found what the issue was, you have to CD into the dir you have kube.tf for it to work. If you run terraform apply from main dir, it breaks.

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.

**Comment by mysticaltech** [comment]
> btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.

@kube-hetzner/core FYI.
