### ISSUE TITLE
[PSA] - Resource Shortage in Falkenstein (fsn1)

### ISSUE THREAD

**Issue by Sudoonym** [kube-hetzner/terraform-hcloud-kube-hetzner#195]
Hello everyone.
I was trying to setup my Cluster with Kuber Hetzner and with 3 Worker nodes. 
One was located in Nuermberg, one in Falkenstein and one in Helsinki.

Somehow I could not deploy the Servers because there was one Server missing everytime and logically the Terraform apply failed.

After a brief call with Hetzner, they told me that they have barely any Servers availible in Falkenstein. 
**This is not listed in the Hetzner Online Status Page**
They've ordered Hardware already and do their best to fix it but there's no ETA on that.

So if you encounter issues while deploying the Servers keep in mind;
**There are currently no Servers availible at datacentre Falkenstein or more known as fsn1**
**The Terraform apply WILL fail if there's either a control-plane or worker node attached to fsn1**

Like I've said there's no ETA on the Fix but logically it will take a while until everything works again.

**Comment by mysticaltech** [comment]
Thanks for the valuable info @Sudoonym! 🙏
