### ISSUE TITLE
Switch to cgroup v1

### ISSUE THREAD

**Issue by mateuszlewko** [kube-hetzner/terraform-hcloud-kube-hetzner#197]
Do you know if it's possible to revert to cgroup V1 on MicroOS? I'm not familiar with MicroOS, but on some other distributions it's doable by setting `systemd.unified_cgroup_hierarchy=0` kernel parameter. This does not seem to work for MicroOS.

**Comment by mysticaltech** [comment]
Hello, it's probably not doable, as the MicroOS system is pretty locked up! It's one of the reasons why we chose it. Please have a look at k-andy, a similar project to ours that uses ubuntu!
