### ISSUE TITLE
Hetzner announcement: No network storage supported in future

### ISSUE THREAD

**Issue by JustinGuese** [kube-hetzner/terraform-hcloud-kube-hetzner#217]
Hi, does the latest press release of Hetzner affect the volumes? Like do we need to switch to internal storage with longhorn or something?
Origininal:

> Bevorstehende Migration Ihrer Cloud Server mit Netzwerk-Speicher (Ceph)
Sehr geehrter Kunde,
lange haben wir Ihnen für unsere Intel-basierten Standard-Server zwei verschiedene Speichertypen angeboten: Lokal (NVMe SSD) und Netzwerk (Ceph). Der lokale Speicher bietet schon immer bei gleicher Stabilität eine höhere IO-Leistung und geringere Latenzen, was diesen zur besten Wahl macht.
Ende letzten Jahres haben Sie daher bereits eine E-Mail mit Informationen darüber erhalten, dass es nicht mehr möglich ist, neue Server mit Netzwerk-Speicher zu erstellen. Bestehende Server mit Netzwerk-Speicher blieben zu diesem Zeitpunkt noch von der Ankündigung unberührt. Nun werden aber auch alle bestehenden Server mit Netzwerk-Speicher migriert. Das bedeutet, dass der Speicher-Typ aller Server mit Netzwerk-Speicher in einen lokalen Speicher geändert wird.
Ab 01. Juli 2022 werden alle Server mit Netzwerk-Speicher zu Servern mit lokalem Speicher migriert.
Bis 01. August 2022 werden voraussichtlich alle Server migriert sein.

Translated:

> Upcoming migration of your cloud servers with network storage (Ceph)
Dear Customer,
For a long time we have offered you two different types of storage for our Intel-based standard servers: Local (NVMe SSD) and Network (Ceph). Local storage has always offered higher IO performance and lower latencies with the same stability, making it the best choice.
Therefore, at the end of last year you already received an email with information that it was no longer possible to create new servers with network storage. Existing servers with network storage were still unaffected by the announcement at that time. Now, however, all existing servers with network storage will also be migrated. This means that the storage type of all servers with network storage will be changed to local storage.
From 01 July 2022, all servers with network storage will be migrated to servers with local storage.
It is expected that all servers will be migrated by 01 August 2022.

**Comment by mysticaltech** [comment]
@JustinGuese , not at all, this just affects the kind of volumes, from now on only NVMe SSD, no more Cepth!

No need to change anything! If you want to continue using Hetzner CSI, you can! :)

**Comment by JustinGuese** [comment]
Awesome @mysticaltech, I wasn't sure but this is good news! Keep up the good work
