### ISSUE TITLE
Exposing additional ports via LoadBalancer

### ISSUE THREAD

**Issue by tmahring** [kube-hetzner/terraform-hcloud-kube-hetzner#218]
Hi
I tried to create an additional service which exposes port 8000 via tcp. However, looking at the hetzner cloud console, i noticed that no service was created on the loadbalncer and kubectl shows my external ip as pending
By manually creating the service in the hetzner ui i managed to access my service from the outside, but kubectl still shows external ip as pending
Am I missing something? Shouldn't the loadbalancer automatically be configured when adding a service with a new port?

**Comment by mysticaltech** [comment]
Hello @tmahring, no need to do that manually. What you need to do is create a HelmChartConfig yaml, you can use this as a starting point and remove the templating logic https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/templates/traefik_config.yaml.tpl.

In it, you need to create new Traefik "entryPoints", when you do that, it will automatically configure the load balancer for your services. By default only `web` (port 80), and `websecure` are added, but you can definitely add as many as you want!

This is the way Traefik works, so not really related to this project. More on the subject here https://doc.traefik.io/traefik/routing/entrypoints/.

**Comment by tmahring** [comment]
Why do i even need traefik in that case? I defined a service, not an ingress rule, shouldn't that go straight to the LB?

**Comment by mysticaltech** [comment]
Nope! The way it works in Kubernetes, your Kubernetes services, talks to your ingress controller, which in turn configures an LB via the cloud controller. That's my understanding at least.

**Comment by mysticaltech** [comment]
Ok, now if you do not want to use Traefik, and want to use a service of the type LoadBalancer directly, you can. In which case you need to configure it as follows, with the Hetzner Load Balancer annotations. See here https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/load_balancers.md. That will not interact with Traefik indeed, just the CCM.

**Comment by mysticaltech** [comment]
And here you can find all the annotations supported by the Hetzner load balancer, so it's through these annotations that you can configure what you want. https://pkg.go.dev/github.com/hetznercloud/hcloud-cloud-controller-manager/internal/annotation#Name

**Comment by tmahring** [comment]
Thank you very much! That was of great help. Both the stuff about helmchartconfig and the loadbalancer.
I'm pretty new to kubernetes so i really appreciate your help!

**Comment by mysticaltech** [comment]
Happy to help!! :)
