### ISSUE TITLE
Feature request: use outputs to provide cluster information

### ISSUE THREAD

**Issue by otavio** [kube-hetzner/terraform-hcloud-kube-hetzner#220]
The module doesn't make use of outputs to provide information for use inside other Terraform modules. Some information I see as useful to provide:

- [ ] cluster IP address
- [ ] kubeconfig used to connect to the cluster
- [ ] load balancer address

**Comment by phaer** [comment]
Isn't https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/output.tf exactly that? What am I missing? :thinking:

**Comment by otavio** [comment]
Cool; I'll close the issue.
