### ISSUE TITLE
Don't set `load_balancer_public_ipv4` if `using_klipper_lb`

### ISSUE THREAD

**Issue by phaer** [kube-hetzner/terraform-hcloud-kube-hetzner#221]
Hello,

I just noticed the following snippet in our outputs.
```
output "load_balancer_public_ipv4" {
  description = "The public IPv4 address of the Hetzner load balancer"
  value = local.using_klipper_lb ? [
    for obj in module.control_planes : obj.ipv4_address
  ][0] : var.traefik_enabled == false ? null : data.hcloud_load_balancer.traefik[0].ipv4
}
```
...and i think that's non-optimal, as `load_balancer_public_ipv4` suggests, well, a load-balancer. It's fine as long as all nodes are up, but if one uses that output to set DNS records and the first control planes goes down (i.e. during upgrades), services will be unavailable due to how klipper works.
Additionally, using just the first node with klipper pushes all traffic through that node, contradicting another reason to use a load-balancer in the first place besides HA.

I think a better approach would be to use `load_balancer_public_ipv4` only if `using_klipper_lb` is false and to `null` otherwise. This would still allow users to i.e. set multiple DNS A records, one for each control plane IP, but would be less surprising.

Otherwise we should at least explicitly document it. What do you think?

**Comment by otavio** [comment]
Providing the list of control plane modes seems better as it would use same output as a unified interface for any module using it.

**Comment by phaer** [comment]
But using a list would break the public interface for IMO little benefit, as the same information is already available in `control_planes_public_ipv4`
