### ISSUE TITLE
Bug: If load balancer is enabled, `terraform destroy` never completes

### ISSUE THREAD

**Issue by otavio** [kube-hetzner/terraform-hcloud-kube-hetzner#228]
To destroy the infra I had to remove the load balancer by hand and the lb wasn't removed as well.

**Comment by mysticaltech** [comment]
That's not up to us, the LB and network sometimes take time to delete. It does complete but sometimes takes up to 20 minutes, so best give it a hand with the cloud command. See the readme https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner#takedown.

**Comment by melalj** [comment]
I had a similar issue, when I detached the LB manually on the subnet, the destruction completes successfully instantly.

**Comment by mysticaltech** [comment]
@melalj Yes exactly, but best to delete it so as to not leave it hanging and billing you for nothing.

**Comment by mysticaltech** [comment]
The command to delete it is:

`hcloud load-balancer delete <cluster-name>`

Or via the UI, but that's too much work IMHO haha.
