### ISSUE TITLE
Connection issues after node restart

### ISSUE THREAD

**Issue by tmahring** [kube-hetzner/terraform-hcloud-kube-hetzner#232]
Hello

To be honest, I'm not even sure if this problem has anything to do with the way this repository creates the cluster, it might be a completely different issue, but I'm running out of ideas.

My problem is, that almost every night, when my nodes are restarted due to updates, some of my pods have problems reconnecting to other pods on different nodes.
I'm running a cluster with 3 worker nodes and I'm using that to run apache kafka, also with 3 nodes (3 broker + 3 zookeeper, both stateful sets). Those zookeeper nodes are the ones usually having the problem.

Here is what happens:
All 3 zk pods are running fine and are connected to each other until a node gets restarted. The restart seems to happen without any problems, but once the zk pod on that node spins back up, it fails to reconnect to the other, still running, pods. The connection attempts fail with "connection refused" and there is no log trace on the pod it's trying to connect to.
The problem goes away as soon as I manually kill the pod which it fails to connect to and that pod gets recreated. Killing and recreating the pod which can't connect makes no difference.

I'm banging my head against this now for almost a week, so if anyone has any ideas they would be greatly appreciated...

**Comment by mysticaltech** [comment]
@tmahring I feel your pain! We'll find a solution!🤞

Are you running in HA, meaning 3 control plane nodes minimum? If not, this is needed for proper operation. Otherwise you need to turn automatic updates off.

Also if your setup needs to use 3 worker nodes, add 1 more (so 4 worker nodes in total) to allow for proper draining and a node update with a concurrency of one.

**Comment by tmahring** [comment]
I do have 3 controll nodes.

The 3 worker nodes are in 3 different hetzner locations, so I think just adding a 4th one propably wont make a difference, as hetzner cant move the volumes between locations and the pods need persistant storage.
But I think I will add 3 more, just for testing, one in each location.

Could it be that somehow the pods start before connectivity between the nodes is ready? Do you have an idea how I could test for this?

Is there a way I can force kured to restart my cluster? Because I can hardly reproduce the issue by manually draining nodes, but it happens almost every night.

**Comment by mysticaltech** [comment]
If you touch (create) this empty file `var/run/reboot-required` on a node, `kured` will detected it after some time and restart it. You can also tweak the kured config, see the templates, and tell it to recheck more often (by default it's 1h if I remember well), you may want to set this to 5 minutes for testing.

Also, you could try using Calico (set it in the cni plugin variable), I think it has good observability solutions, and I think it is more efficient.

I think trying with nodes in the same region is definitely a good idea!

**Comment by tmahring** [comment]
Soo
i have done some more testing and it seems to me that the problem is caused by a network policy that gets created for zookeeper. 
it should limit connections between the zookeeper pods to other zookeeper pods, however it seems to me that it somehow doesn't get updated after the node reboots.
At least the problem goes away once i remove the policy...

Do you know if there is a way i can look at the current state of these policies? so i can see which ips are currently used?

**Comment by mysticaltech** [comment]
I don't, but we have a flag to turn network policy off when deploying the cluster, that should do it. 

Otherwise, try reading this https://rancher.com/docs/k3s/latest/en/installation/network-options/.

And also switching to Calico (which will also disable k3s built it network policies!

**Comment by mysticaltech** [comment]
I know that with Cilium, you can have tons of observability. But we do not support it yet, however I you want to work on a PR to add it (same way as Calico is added) I will help you, as I have previous experience with it.

**Comment by mysticaltech** [comment]
@tmahring I'm considering this problem sorted. But please do not hesitate to share your further experience with the matter, it could be useful to other people! Thanks 🙏

**Comment by tmahring** [comment]
Sry for not replying, the problem isn't really sorted, as it still exists, but for now I can life with the workaround of not using the network policy.
I'm quite sure the problem is somewhere i k3s's kube-router implementation, but I haven't found the time yet to go through their code.
