### ISSUE TITLE
Ingress with TLS - Force https

### ISSUE THREAD

**Issue by boxedcode** [kube-hetzner/terraform-hcloud-kube-hetzner#239]
Hi,

First of all, I'd like to thank you guys for creating this awesome tool for spinning up kubernetes clusters in Hetzner Cloud.

Following your example for `Ingress with TLS` using cert-manager as recommended, how would I force a redirect to https if my ingress host is accessed on non-https?

Thanks

**Comment by mysticaltech** [comment]
Hello @boxedcode, thanks for your nice words. There are many ways to redirect to https, but personally I find that method is the best: https://aqibrahman.com/set-up-traefik-kubernetes-ingress-for-http-and-https-with-redirect-to-https

**Comment by boxedcode** [comment]
> Hello @boxedcode, thanks for your nice words. There are many ways to redirect to https, but personally I find that method is the best: https://aqibrahman.com/set-up-traefik-kubernetes-ingress-for-http-and-https-with-redirect-to-https

Thank you, appreciated!
