### ISSUE TITLE
Rancher installation fail

### ISSUE THREAD

**Issue by AdZoAi** [kube-hetzner/terraform-hcloud-kube-hetzner#248]
Hi,

To let you know that rancher installation with default rancher and k3s channels now fails.

The pod running rancher helm deploy reports an error on current requirement: kubernetes version < 1.24.0

Current latest k3s version is 1.24.3+k3s1

So to deploy rancher you must enforce  initial_k3s_channel = "v1.23", or earlier!.

BR

**Comment by mysticaltech** [comment]
Thanks for letting us know @AdZoAi; let's see if Rancher releases a new compatible chart soon enough!

**Comment by mysticaltech** [comment]
@AdZoAi Support for 1.24 will be added in Rancher 2.6.7, the next release, which hopefully will happen soon. Progress can be seen here https://github.com/rancher/rancher/issues/37727

**Comment by mysticaltech** [comment]
Will close this as when the new Rancher release drops, it will automatically pick it up. There is nothing else we can do here.
