### ISSUE TITLE
Server -> client sync of *_kustomization_backup.yaml a single point of failure?

### ISSUE THREAD

**Issue by leiffoged** [kube-hetzner/terraform-hcloud-kube-hetzner#273]
When using `terraform apply`, the `*_kustomization_backup.yaml` file is fetched from the *first* master node.

`kustomization_backup.tf`:

```
data "remote_file" "kustomization_backup" {
  conn {
    host        = module.control_planes[keys(module.control_planes)[0]].ipv4_address
    port        = 22
    user        = "root"
    private_key = var.ssh_private_key
    agent       = var.ssh_private_key == null
  }
  path = "/var/post_install/kustomization.yaml"

  depends_on = [null_resource.kustomization]
}
```

However, if the `*_kustomization_backup.yaml` is not available on the first master node, `terraform apply` will fail. 

Consider, for example, the case where the first master node fails (while the 2 other master nodes remain running). I would expect to be able to replace that node with a new node via `terraform apply`. However, this will not work because the `terraform apply` will fail when fetching the `*_kustomization_backup.yaml` from the first master node (which is not available).

By contrast, if any of the other two master nodes fail, `terraform apply` will correctly replace that node with a new one and heal the cluster properly.

Ideally, `*_kustomization_backup.yaml` would be generated only once when the cluster is created (or there would be some option to disable fetching it altogether).

-- 

Also, thank you for creating this amazing tool. True game-changer.

**Comment by mysticaltech** [comment]
@leiffoged Thank you! You are absolutely right, I missed that completely. PR welcome to ensure it only runs the first time! 🙏

**Comment by mysticaltech** [comment]
@leiffoged I just thought of this some more. It depends on the null_resource.kustomization, which to my understanding, happens only on the first run. So your worries are already met. @phaer, can you confirm?

**Comment by mysticaltech** [comment]
From my analysis of the logic, the null_ressource.kustomization runs only the first time, as dependent on things that themselves run the first time only. 

https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/061a0eeac28a5222ff19d14fea9f43db99f232fa/init.tf#L272-L277
