### ISSUE TITLE
Use different for SSH

### ISSUE THREAD

**Issue by otavio** [kube-hetzner/terraform-hcloud-kube-hetzner#277]
We would like to provide a service which uses SSH port so we would like to use an alternate port for it.

**Comment by mysticaltech** [comment]
Sounds useful, PR welcome @otavio.

**Comment by otavio** [comment]
No idea where to start. Any pointers?

**Comment by mysticaltech** [comment]
The default SSH port for nodes needs to be conditionally changed at the cloud-init level, so editing the cloud-init template and the var file should be all that is needed, along with a small explanation in the kube.tf.example.
