### ISSUE TITLE
not ready nodes

### ISSUE THREAD

**Issue by arkkanoid** [kube-hetzner/terraform-hcloud-kube-hetzner#285]
Hi, when a server is frozen (too CPU load) the node status changes to "not ready" but it doesn't restart automatically. 
I've to log in to the Hetzner cloud and make a hard reset. 
Is it possible to restart it automatically?

**Comment by mysticaltech** [comment]
@arkkanoid Not that I know of. But in the future (see #235), we should be releasing an autoscaling feature that will bypass that issue automatically.
