### ISSUE TITLE
Expose loadbalancer IPv4 when Traefik disabled.

### ISSUE THREAD

**Issue by otavio** [kube-hetzner/terraform-hcloud-kube-hetzner#293]
### Discussed in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/284

<div type='discussions-op-text'>

<sup>Originally posted by **geraldwuhoo** July  6, 2022</sup>
Currently the code in `output.tf` returns `null` for `load_balancer_public_ipv4` if Traefik is disabled. I can understand the reasoning, because without an ingress controller to provision an IP from the Hetzner LB, there is no LB IP to speak of. However, I'm disabling Traefik to install nginx-ingress instead. I'm sure many others disable Traefik to instead install their own preferred ingress controller.

Since there is no way for the Terraform module to detect whether or not a user will provision an ingress controller *after* Terraform provisioning, I think it makes sense to err on the side of caution, and return proper `load_balancer_public_ipv4` value even when Traefik is disabled.</div>

**Comment by mysticaltech** [comment]
Just FYI future readers, with the new system for managing ingresses in #298, adding new ingresses via HelmChart config is now more or less a piece of cake. So don't hesitate to send us your PRs!

Kong, HAProxy, Caddy... You-name-it Ingress Controller! If it has both a decent user base and a helm chart, we want it! And we can integrate it quite easily, just follow in the footsteps of Nginx-ingress. Issuing a Find "nginx" in your code editor will illuminate the path you need to take to add the Ingress controller of your liking.

**Comment by mysticaltech** [comment]
@geraldwuhoo FYI, the above. We know support Traefik, Nginx, and none - And we also have an easy flow to add more Ingress controllers if someone needs them, and they are popular in the cloud-native community to justify supporting them. This should solve your original issue #254, indirectly at least.
