### ISSUE TITLE
Volume Encryption via Longhorn

### ISSUE THREAD

**Issue by mysticaltech** [kube-hetzner/terraform-hcloud-kube-hetzner#295]
### Discussed in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/287

<div type='discussions-op-text'>

<sup>Originally posted by **JustinGuese** August 29, 2022</sup>
do we have an idea of how to implement volume encryption?
any ideas how we could solve it?</div>

**Comment by mysticaltech** [comment]
@JustinGuese, I will address this ASAP.

**Comment by mysticaltech** [comment]
@JustinGuese We very recently added support for Longhorn volumes and a custom values.yaml file to be added, please see the [kube.tf.example](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/kube.tf.example). 

And this is the [how](https://github.com/longhorn/longhorn/issues/1859#issuecomment-900759320) to add encryption, which is probably already possible now as you have complete flexibility over Longhorn config. 

Please try it, and let me know if all is good so we can close this!

**Comment by mysticaltech** [comment]
Please be aware of #296; it will get fixed soon. This is required for the above to work.

**Comment by mysticaltech** [comment]
I will consider this resolved, but if you tried and it turned out not possible because we are missing something, just let me know, and we will reopen this.

**Comment by JustinGuese** [comment]
@mysticaltech did you have a thought about making this feature donatable?

also: I'm currently stuck at that the nodes need some libraries installed for longhorn and the encryption to work...
How can I do that? does it even work for an existing installation?

` iscsiadm/open-iscsi`
`cryptsetup`
and the `dm_crypt` has to be loaded

Thanks again for your help!
