### ISSUE TITLE
locals merge is missing the longhorn_volume_size attribute

### ISSUE THREAD

**Issue by ifeulner** [kube-hetzner/terraform-hcloud-kube-hetzner#296]
Version 1.4.7

When merging agent node pools into *agent_nodes* in *locals.tf*, the longhorn_volume_size attribute is missing.

**Comment by mysticaltech** [comment]
Thanks for catching this @ifeulner! I completely missed it, and the testing was not sufficiently deep indeed. It would be awesome if you could create a PR to add it. Otherwise, I will try address this ASAP.

**Comment by mysticaltech** [comment]
Now working on it.

**Comment by mysticaltech** [comment]
Thanks again for catching this @ifeulner; it was fixed and released in v1.4.8.
