### ISSUE TITLE
Nginx-Ingress instead of Ingress-Nginx

### ISSUE THREAD

**Issue by mysticaltech** [kube-hetzner/terraform-hcloud-kube-hetzner#305]
### Discussed in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/304

<div type='discussions-op-text'>

<sup>Originally posted by **hariprasadiit** September 13, 2022</sup>
Hello,

Thanks for the awesome project.

I've created a cluster recently by enabling `nginx`. From the helm releases, I can see that the chart version is`0.14` and it's not `ingress-nginx` but `nginx-ingress` chart. 

is `nginx-ingress` is the intended chart here? If so, reference mentioned in the example nginx values file seems to be pointing to kubernetes maintained version.

https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml</div>

**Comment by mysticaltech** [comment]
@hariprasadiit Good catch; I confused the too. The intended one was ingress-nginx! So I will make the change later today.

**Comment by hariprasadiit** [comment]
FYI, nginx maintained chart which was deployed along with the cluster, created issues with `hostPort` when cilium CNI is used with example values. 

LoadBalancer ports were not exposed on 3 out of 4 agent nodes and network was not routed to those nodes from the created LoadBalancer. Deleting that release and installing kubernetes maintained chart fixed the issue for me

**Comment by mysticaltech** [comment]
Ok, thanks for sharing @hariprasadiit. One more reason to do it! On it.

**Comment by mysticaltech** [comment]
@hariprasadiit This was addressed in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/307, and released in v1.5.2. Thanks again for reporting and if you see any improvements PRs are always welcome.
