### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Berndinox** [kube-hetzner/terraform-hcloud-kube-hetzner#309]
`╷
│ Error: Duplicate required providers configuration
│ 
│   on versions.tf line 3, in terraform:
│    3:   required_providers {
│ 
│ A module may have only one required providers configuration. The required providers were previously configured at kube.tf:284,3-21.
╵

I just modified:
- hcloud token line 3
- removed 2 of 3 nodepools
- network = cilum

**Comment by Berndinox** [comment]
"It's important to realize that you do not even need to clone this git repo, as the module by default will be fetched from the Terraform registry. All you need, is to use the [kube.tf.example](https://raw.githubusercontent.com/kube-hetzner/terraform-hcloud-kube-hetzner/master/kube.tf.example) file to make sure you get the format of your kube.tf file right."

Should be: "It's important to realize that you do should not clone this git repo"

When using kube.tf in an empty folder, all is fine...

**Comment by mysticaltech** [comment]
You are right, I just did the changes, thanks!
