### ISSUE TITLE
SSH Key Issue

### ISSUE THREAD

**Issue by Berndinox** [kube-hetzner/terraform-hcloud-kube-hetzner#310]
```
cd /home/bernd/Documents/k8s/
ssh-keygen -t ed25519
./k8s
Enter - Enter - Enter
```
kube.tf

```
  ssh_public_key =  "/home/bernd/Documents/k8s/k8s.pub"
  ssh_private_key = "/home/bernd/Documents/k8s/k8s"
```

terraform apply -auto-approve
```
module.kube-hetzner.hcloud_ssh_key.k3s[0]: Creating...
╷
│ Error: invalid input in field 'public_key' (invalid_input): [public_key => [SSH key type is invalid (supported types: ssh-ed25519, ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, ssh-dss, sk-ssh-ed25519, sk-ecdsa-sha2-nistp256, sk-ecdsa-sha2-nistp384, sk-ecdsa-sha2-nistp521]]
│ 
│   with module.kube-hetzner.hcloud_ssh_key.k3s[0],
│   on .terraform/modules/kube-hetzner/main.tf line 6, in resource "hcloud_ssh_key" "k3s":
│    6: resource "hcloud_ssh_key" "k3s" {
│ 
```

cat k8s.pub
`ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBhZVBDSoDVSS5xAEqmFfjht+MG422xi4KoA2yTn4muz bernd@thinkpad`

i also tried: `ssh-keygen -t dsa` (=dss key) , `ssh-keygen -t ecdsa -b 521`

So, for me no key seems to be valid, however they should according to the message... Any sugestion? Thanks, Bernd

**Comment by Berndinox** [comment]
Well, i should stop opening issues and self-closing them... sorry guys.

  ssh_public_key =  **file(**"/home/bernd/Documents/k8s/k8s.pub"**)**

**Comment by mysticaltech** [comment]
Haha, no worries @Berndinox, it's good learning for others! And it's also good content for Google!  😇 Thanks.
