### ISSUE TITLE
Support for External-DNS

### ISSUE THREAD

**Issue by codeagencybe** [kube-hetzner/terraform-hcloud-kube-hetzner#312]
@mysticaltech 

Do you happen to know if and how it could add support for external DNS from https://github.com/kubernetes-sigs/external-dns ? 

This can help automating the DNS part for the custom domains set, and hence improve the SSL part from cert manager via DNS01 resolved (instead of HTTP01).
https://github.com/ixoncloud/cert-manager-webhook-cloudns

**Comment by codeagencybe** [comment]
@mysticaltech 

Sure that is understandable. I was just looking for a way to easy link the base domain and rancher domain directly to my DNS provider. 
In case we want to spin up a new cluster, it's easier because you don't know in advance which IP Hetzner is giving you for the LB so you can't pre-configure your DNS to point A record to the IP. 
Having this in place at the time of deploying, automatically, would make it a bit easier. 

I already found some terraform module for my DNS provider, so I'm looking into this route. 
Then I can add just another TF module, handle config in there and call it at some point during the process when the LB is generated so it links the A record with my DNS provider (ClouDNS)

**Comment by mysticaltech** [comment]
@codeagencybe Awesome; if you can make this work in a configurable way, I would be happy to review a PR if that's a route you would like to take. Or share your extra module in the examples folder if you are willing to make it open source.

**Comment by mysticaltech** [comment]
@codeagencybe Also moving this one to discussions, as that's where I prefer to have enhancement proposals that are not super urgent.
