### ISSUE TITLE
Longhorn shared storage

### ISSUE THREAD

**Issue by codeagencybe** [kube-hetzner/terraform-hcloud-kube-hetzner#313]
@mysticaltech 

I have been testing out the Longhorn parts and switched to node storage. There is a performance difference between node storage and Hetzner BLock storage volumes that is noticeable. 
So I went for node storage. 

Now I'm trying to deploy a simple workload like Wordpress and this requires to use a "shared" storage. 
I've been reading up on Longhorn and they keep mentioning to use NFS for this, and I was assuming your Terraform setup already install this but I think it's not? 
At least, when I run kubectl get pods -A, I can see several results for pods running Longhorn things like CSI so Longhorn is definetly installed. 
But is this enough to handle a "shared" storage for applications like Wordpress? 
Am I missing something or am I misunderstanding? 

Any pointers you can give or maybe somebody else in the community who can help me? 

Thanks!

**Comment by mysticaltech** [comment]
@codeagencybe Thanks for sharing your findings that node storage is indeed faster.

For WordPress, forget about NFS; Longhorn, the way it is installed, has everything you need. But I believe you need to read more about [PV and PVCs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/), which can be shared between pods.

I believe that's a good resource to revisit your flow to make sure it's optimized: https://medium.com/@vivekksonar2000/creating-a-wordpress-application-using-kubernetes-fb6827f4445c

**Comment by mysticaltech** [comment]
@codeagencybe Also, check this out, a 2 hours Longhorn training from the rancher folks https://www.youtube.com/watch?v=BnHMAJ8azBU.
