### ISSUE TITLE
Rancher not accessible using nginx as ingress controller

### ISSUE THREAD

**Issue by timowevel1** [kube-hetzner/terraform-hcloud-kube-hetzner#317]
Hey, 

I stumbled across this and wanted to try it. I had set the rancher hostname to rancher.mydomain.com and enabled rancher, the pods also get deployed. I use nginx as ingress controller.

I pointed then the DNS to the IP of the Hetzner LB, but when I access the domain it gives me a 404.

cattle-system               rancher-58b9c7b76d-2txsx                                          1/1     Running     0          2m25s
cattle-system               rancher-58b9c7b76d-4bl4n                                          1/1     Running     0          2m25s
cattle-system               rancher-58b9c7b76d-t4f29                                          1/1     Running     0          2m25s
cattle-system               rancher-webhook-576c5b6859-hdvsx                                  1/1     Running     0          23s
cert-manager                cert-manager-877fd747c-n5jnr                                      1/1     Running     0          2m25s
cert-manager                cert-manager-cainjector-bbdb88874-pf2b8                           1/1     Running     0          2m25s
cert-manager                cert-manager-webhook-5774d5d8f7-c82jf                             1/1     Running     0          2m25s
kube-system                 coredns-b96499967-7crwm                                           1/1     Running     0          3m39s
kube-system                 hcloud-cloud-controller-manager-947cccf88-jrc44                   1/1     Running     0          2m25s
kube-system                 hcloud-csi-controller-0                                           5/5     Running     0          2m25s
kube-system                 hcloud-csi-node-2xwv4                                             3/3     Running     0          5m1s
kube-system                 hcloud-csi-node-6xjp5                                             3/3     Running     0          5m1s
kube-system                 hcloud-csi-node-82chj                                             3/3     Running     0          5m1s
kube-system                 hcloud-csi-node-96sqt                                             3/3     Running     0          5m1s
kube-system                 hcloud-csi-node-9xh8n                                             3/3     Running     0          5m1s
kube-system                 hcloud-csi-node-gpzbx                                             3/3     Running     0          5m1s
kube-system                 helm-install-ngx-64k47                                            0/1     Completed   0          5m1s
kube-system                 kured-75vms                                                       1/1     Running     0          4m45s
kube-system                 kured-frd9h                                                       1/1     Running     0          4m42s
kube-system                 kured-jqq6z                                                       1/1     Running     0          4m41s
kube-system                 kured-mqbvz                                                       1/1     Running     0          4m44s
kube-system                 kured-v22cm                                                       1/1     Running     0          4m50s
kube-system                 metrics-server-668d979685-knqhl                                   1/1     Running     0          3m39s
kube-system                 ngx-ingress-nginx-controller-59cbbf49b8-jtnqr                     1/1     Running     0          2m25s

 kubectl get service -A
NAMESPACE             NAME                                     TYPE           CLUSTER-IP      EXTERNAL-IP                           PORT(S)                      AGE
cattle-fleet-system   gitjob                                   ClusterIP      10.43.109.140   <none>                                80/TCP                       9m36s
cattle-system         rancher                                  ClusterIP      10.43.69.148    <none>                                80/TCP,443/TCP               12m
cattle-system         rancher-webhook                          ClusterIP      10.43.40.126    <none>                                443/TCP                      9m17s
cattle-system         webhook-service                          ClusterIP      10.43.20.178    <none>                                443/TCP                      9m17s
cert-manager          cert-manager                             ClusterIP      10.43.33.177    <none>                                9402/TCP                     13m
cert-manager          cert-manager-webhook                     ClusterIP      10.43.74.189    <none>                                443/TCP                      13m
default               kubernetes                               ClusterIP      10.43.0.1       <none>                                443/TCP                      14m
kube-system           hcloud-csi-controller-metrics            ClusterIP      10.43.197.16    <none>                                9189/TCP                     13m
kube-system           hcloud-csi-node-metrics                  ClusterIP      10.43.129.117   <none>                                9189/TCP                     13m
kube-system           kube-dns                                 ClusterIP      10.43.0.10      <none>                                53/UDP,53/TCP,9153/TCP       14m
kube-system           metrics-server                           ClusterIP      10.43.139.102   <none>                                443/TCP                      14m
kube-system           ngx-ingress-nginx-controller             LoadBalancer   10.43.213.38    167.235.218.40,2a01:4f8:c01e:228::1   80:30237/TCP,443:31984/TCP   13m
kube-system           ngx-ingress-nginx-controller-admission   ClusterIP      10.43.124.126   <none>                                443/TCP                      13m

 kubectl get ingress -A
NAMESPACE       NAME      CLASS    HOSTS                 ADDRESS   PORTS     AGE
cattle-system   rancher   <none>   cluster.mydomain.de             80, 443   13m

It seems like it doesnt get an address. This may be related to it? https://github.com/rancher/rancher/issues/35887

Any ideas on this? Thank you.

**Comment by timowevel1** [comment]
Yes, that fixed it https://github.com/rancher/rancher/issues/35887 
You may consider adding it anywhere?

**Comment by mysticaltech** [comment]
@

**Comment by mysticaltech** [comment]
The Rancher helm installer was giving me this error :

`INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.tls[0].hosts):`

It turned out it was just the `rancher_hostname` missing.

**Comment by mysticaltech** [comment]
Actually it works out of the box, just make sure to set the `rancher_hostname`.

**Comment by timowevel1** [comment]
@mysticaltech But am I missing something? Isnt it required to deploy the ingress controller on each node if you point the load balancer on all nodes? Or what happens if I access the ports for the controller and there is no controller deployed on it? Will the request be forwarded to a node with the controller on it?

**Comment by mysticaltech** [comment]
You need to read more on how Ingress controllers work. The request enters via the LB and is routed to the active instance; it does not matter which host it runs on. And itself will route it to the right service via ingress definitions.

**Comment by timowevel1** [comment]
Okay, thats what I thought too. I was just curious because I deployed it a few hours ago, and received a "Service not available" and then saw one rancher pod died and restarted multiple times. It also happened when I try to install Longhorn. Do you have an idea why this happens? I did 2 fresh installs and it happend on both, so it wont be a problem to reproduce it later.
