### ISSUE TITLE
Error when uncommenting longhorn_volume_size in line 128

### ISSUE THREAD

**Issue by timowevel1** [kube-hetzner/terraform-hcloud-kube-hetzner#320]
I receive this error when uncommenting line 128 in kube.tf:

terraform apply -auto-approve
╷
│ Error: Invalid value for input variable
│
│   on kube.tf line 97, in module "kube-hetzner":
│   97:   agent_nodepools = [
│   98:     {
│   99:       name        = "agent-small",
│  100:       server_type = "cpx11",
│  101:       location    = "fsn1",
│  102:       labels      = [],
│  103:       taints      = [],
│  104:       count       = 1
│  105:     },
│  106:     {
│  107:       name        = "agent-large",
│  108:       server_type = "cpx21",
│  109:       location    = "nbg1",
│  110:       labels      = [],
│  111:       taints      = [],
│  112:       count       = 1
│  113:     },
│  114:     {
│  115:       name        = "storage",
│  116:       server_type = "cpx21",
│  117:       location    = "fsn1",
│  118:       # Fully optional, just a demo
│  119:       labels = [
│  120:         "node.kubernetes.io/server-usage=storage"
│  121:       ],
│  122:       taints = [
│  123:         "server-usage=storage:NoSchedule"
│  124:       ],
│  125:       count = 1
│  126:       # In the case of using Longhorn, you can use Hetzner volumes instead of using the node's own storage by specifying a value from 10 to 10000 (in GB)
│  127:       # It will create one volume per node in the nodepool, and configure Longhorn to use them.
│  128:       longhorn_volume_size = 20
│  129:     }
│  130:   ]

The given value is not suitable for module.kube-hetzner.var.agent_nodepools declared at .terraform/modules/kube-hetzner/variables.tf:71,1-27: all list elements must have the same type.

When I comment it, it runs fine.

**Comment by mysticaltech** [comment]
@timowevel1 This was tried and tested, it works fine, the only thing that could have gone wrong is in your kube.tf file.  Ideally, just use it as shared in kube.tf.example. To deal with this, please share your kube.tf and I will help you debug it.

**Comment by mysticaltech** [comment]
Please note that the longhorn_volume_size is not a variable; it's an attribute of the agent nodepool definition. So you can add it to any nodepool definition when you have enable_longhorn true, and it will use volumes of the defined size instead of node storage. More info in the kube.tf.example. But please share yours without the sensitive values!

**Comment by mysticaltech** [comment]
Ah, just remembered this was addressed in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/303. Please, it's essential to search past issues before posting a new one. Good luck!

**Comment by timowevel1** [comment]
Sorry for that, you are right. 
[kube.tf.txt](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/files/9634002/kube.tf.txt)
