### ISSUE TITLE
No public IP output if load balancer is disabled

### ISSUE THREAD

**Issue by captnCC** [kube-hetzner/terraform-hcloud-kube-hetzner#332]
Currently there are only IP(v4/v6) outputs if the external load balancer from Hetzner is used. 
For single-node clusters, the IPs need to extracted from the `control_planes_public_ipv4` output (and no IPv6).

To make the usage of the Ingress IPs more consistent down the line, they should have a consistent output for both v4 and v6.

The implementation is fairly simple, just one decision needs to be done: should the behaviour of the existing `load_balancer_public_ipv4`|`load_balancer_public_ipv6` be extended to include the kilpper-lb IP or should new outputs `ingress_public_ipv4`|`ingress_public_ipv6` be added?

**Comment by mysticaltech** [comment]
@captnCC Not sure I follow you all the way here. The problem with Klipper is that it gives many IPs, so it's an array, with the external IPs of all the nodes, as it's an on-metal LB provider.

**Comment by mysticaltech** [comment]
You are right; for a single node cluster, it should be outputted! Please don't hesitate to take this on.

**Comment by captnCC** [comment]
@mysticaltech Yes especially the single-node where my main point. For dev/prod-setups this is very useful (when the dev cluster is a dev-cluster is single node, and prod a full-blown cluster with load balancer). Then there is no need for extra logic to set DNS records for the cluster! 

As usual, the PR will follow soon!

**Comment by mysticaltech** [comment]
"No need for extra logic", exactly @captnCC !! 🙏🏻
