### ISSUE TITLE
Customise reboot schedule with kured.

### ISSUE THREAD

**Issue by mateuszlewko** [kube-hetzner/terraform-hcloud-kube-hetzner#334]
How can I customise kured configuration within terraform, after deploying the cluster? Modifying `kustomized/kured.yaml` doesn't seem to display any terraform diff.

**Comment by mysticaltech** [comment]
@mateuszlewko There is a kustomization backup that gets created at the root of your your folder, next to your kube.tf file during setup! You can use that to add the changes you want and apply it again.

**Comment by mysticaltech** [comment]
This exact same method applies https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner#individual-components-upgrade
