### ISSUE TITLE
Error on create single node cluster

### ISSUE THREAD

**Issue by panakour** [kube-hetzner/terraform-hcloud-kube-hetzner#338]
I try to create a single node cluster using the count of 0 to nodepools:

```
  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cpx31",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]

  agent_nodepools = [
    {
      name        = "agent-small",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 0
    }
  ]
```

But i get this error
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/12927166/194012070-576a394d-30f7-4a72-b0b2-e7d5295454fb.png">

In the past it was working

**Comment by mysticaltech** [comment]
@panakour Please try again recreating the cluster with `hetzner_ccm_version="v1.12.1"`, which will ensure that workloads can be executed on the control plane and ensure your setup works. 

More on the matter here https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/311

**Comment by panakour** [comment]
@mysticaltech Thanks a lot now its working

**Comment by otavio** [comment]
@mysticaltech the version could be fixed when using single node cluster, automatically.

**Comment by mysticaltech** [comment]
@otavio The above is just a temporary patch. If you know of a real fix, please explain or PR, thank you! 🙏
