### ISSUE TITLE
Is it possible to add dedicated server as worker?

### ISSUE THREAD

**Issue by Danielss89** [kube-hetzner/terraform-hcloud-kube-hetzner#344]
As the headline says, i would like to run a cluster on Hetzner cloud, but be able to add additional worker nodes from my dedicated servers in Hetzner robot.

**Comment by phaer** [comment]
Please search for existing issues and discussions before opening new ones :)

https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/283

**Comment by Aubermean** [comment]
Discussion on this topic has been opened here: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/1311
