### ISSUE TITLE
After a few tries, stuck ad reading...

### ISSUE THREAD

**Issue by renich** [kube-hetzner/terraform-hcloud-kube-hetzner#411]
Hello,

After a few tries, I got stuck at reading hetzner_ccm, kured and hetzner_csi.

I may have been ratelimited. Is it like that? I've tried deploying maybe 3-5 times. 

![image](https://user-images.githubusercontent.com/225115/201546013-098c2891-e698-4a3a-8aae-5cafdfc50e46.png)

**Comment by mysticaltech** [comment]
@renich I have never seen this issue, please share your full kube.tf, just strip it of comments and sensitive values please.

**Comment by ifeulner** [comment]
Hm, if you did many tests it could be that you're running into rate limits by GitHub... I did a small test with running `terraform plan` twice, with this result:

```bash
❯ curl \
  -H "Accept: application/vnd.github+json" \
  https://api.github.com/rate_limit
{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 45,
      "reset": 1668448863,
      "used": 15,
      "resource": "core"
    },
    "graphql": {
      "limit": 0,
      "remaining": 0,
      "reset": 1668452110,
      "used": 0,
      "resource": "graphql"
    },
    "integration_manifest": {
      "limit": 5000,
      "remaining": 5000,
      "reset": 1668452110,
      "used": 0,
      "resource": "integration_manifest"
    },
    "search": {
      "limit": 10,
      "remaining": 10,
      "reset": 1668448570,
      "used": 0,
      "resource": "search"
    }
  },
  "rate": {
    "limit": 60,
    "remaining": 45,
    "reset": 1668448863,
    "used": 15,
    "resource": "core"
  }
}
```

For unauthenticated requests the limit seems to be 60 requests / hour... 
Maybe you can verify this by waiting an hour and retry then?

**Comment by renich** [comment]
[kube.tf.txt](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/files/10006893/kube.tf.txt)

**Comment by renich** [comment]
FWIW, it did work after like 20 minutes (and re-trying).

**Comment by mysticaltech** [comment]
@renich @ifeulner You are right, it's the github limit! Glad it ended up working for you, next time you can just use the provided variables to set the version of those two packages, that way, it completely bypasses the need to hit the Github API.

**Comment by renich** [comment]
Thank you. :)
