### ISSUE TITLE
nginx annotation labels on ingress when Traefik only is deployed? 

### ISSUE THREAD

**Issue by codeagencybe** [kube-hetzner/terraform-hcloud-kube-hetzner#412]
Hello @mysticaltech 

We just stumbled upon this weird thing where the Rancher ingress is showing nginx annotation labels while we never installed NGINX and it also is not installed or deployed anywhere. 
We have set it to false and only Traefik is running. 

But while validating some small issues, we stumbled upon this where it seems to set NGINX annotation labels for Traefik services?? 

Any idea where/which is causing this? 

<img width="784" alt="image" src="https://user-images.githubusercontent.com/7568546/201623725-a33caae3-274f-4cc5-95e6-69f37741c7a8.png">

**Comment by mysticaltech** [comment]
@codeagencybe I believe it must be Rancher's default ingress definition, it's coming from them, not us. Probably you can use `rancher_values` to give it a custom ingress definition, see the `kube.tf` and the link is given in there to the rancher helm values file so that you know all your options.
