### ISSUE TITLE
terraform output --raw kubeconfig_file > Error: Output "kubeconfig_file" not found

### ISSUE THREAD

**Issue by wombelix** [kube-hetzner/terraform-hcloud-kube-hetzner#421]
Hi,

I set `create_kubeconfig = false` and tried to get the kubeconfig file afterwards by running `terraform output --raw kubeconfig_file` as described in the README and the kube.tf.example, which throws the error `Error: Output "kubeconfig_file" not found`, the Output get registered as `kubeconfig` and not `kubeconfig_file`, so running `terraform output --raw kubeconfig` works as expected.

I think either the example file or the Readme should be adjusted? I can create a PR for this, just want to confirm that my assumption is correct.

Cheers
Dominik

**Comment by mysticaltech** [comment]
@wombelix You are right! PR welcome, will merge ASAP.

**Comment by mysticaltech** [comment]
@wombelix Your fix was good, thanks! But for backward compatibility decided just to change the docs, the new command is indeed `terraform output --raw kubeconfig`  as you found out above.
