### ISSUE TITLE
Close SSH and kube api to the world

### ISSUE THREAD

**Issue by danackerson** [kube-hetzner/terraform-hcloud-kube-hetzner#436]
Is it possible to lock down the SSH and kube api access to the world? Overriding files works until you run a `terraform init --upgrade` then all files under .terraform are discarded and recreated.

**Comment by ifeulner** [comment]
What do you mean with "lock down"? What about just adjusting the firewall rules if you want to avoid access?

**Comment by danackerson** [comment]
[`locals.tf`](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/2acaf6c259da6c2f863cedfda89b620aa4cbede4/locals.tf#L142) explicitly opens SSH to the world. Overriding `base_firewall_rules` works with an *_override.tf file parallel to it, but `terraform init --upgrade` discards and refetches all the files from this repo effectively eliminating the override.

Otherwise, I wasn't able to see how (in hcloud terraform) to explicitly *deny* ports? Any other suggestions would be much appreciated!

**Comment by mysticaltech** [comment]
@danackerson My approach would be to, first deploy with the default firewall state in kube.tf (for instance). When your cluster is up, change those firewall rules in your kube.tf and apply! That would just update the Hetzner firewall rules and you would have reached the state you want. Please try it!

**Comment by danackerson** [comment]
But those base firewall rules are in the [`locals.tf`](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/2acaf6c259da6c2f863cedfda89b620aa4cbede4/locals.tf#L142) file - not my kube.tf?

If I change them in locals.tf, they'll just be overridden by the next `init --upgrade` cmd.

**Comment by andinger** [comment]
I think, what @mysticaltech means is, to set the `base_firewall_rules` from `locals.tf` explicitly in the `kube.tf` after you created your cluster initially. The ports are necessary for the initial boostrap and any changes to be applied in your cluster lifecycle. Nevertheless you can open the ports manually if you want to maintain your cluster.

**Comment by mysticaltech** [comment]
@danackerson @andinger Nope! Sorry, I should have made it more obvious. You have an `extra_firewall_rules`, please see the `kube.tf.example` file. This is what you need to change after the cluster is up. 

And why not, also set the `ssh_port` from the get-go (before the first apply) to something other than 22, ideally > 1000. That way, you can later block that with the `extra_firewall_rules` variable, after the cluster has successfully deployed (so with a second terraform apply).

![ksnip_20221129-152931](https://user-images.githubusercontent.com/518555/204557399-73ffb72a-a677-4a9b-ad30-c6f8d4f57476.png)

**Comment by andinger** [comment]
hmm i know this setting und and used it already ... but i'd also like (in the near future) to edit the default firewalls (static ips for kube api and ssh and not open world). so if the above `base_firewall_rules` trick won't work, i have to use https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/firewall after kube-hetzner to manipulate the firewall settings. maybe this is a nice way to open ssh ports automatically to the nodes before reconfiguring them and closing it afterwards ... 🤔

**Comment by danackerson** [comment]
I tried copy/pasta with `base_firewall_rules` but have to then copy over a lot of it's referenced local vars as well - then it blew up at `var.ssh_port` because this isn't known to my `kube.tf`.

With `extra_firewall_rules`, I can only do just that manage *extra* rules. This doesn't allow me to override/deny any rules coming from the `base` file.

I believe a quick fix for all this would be just putting "0.0.0.0/0" into the kube.tf.example as a local var to be overridden just like the ssh_port?

```
# Customize the allowed IP range for accessing SSH and kubelet APIs 
# NOTE: do not adjust this for the initial cluster creation unless you know what you're doing!
ip_range_access = ["0.0.0.0/0", "::/0"]
```

And then using `var.ip_range_access` for those 2 rulesets w/i `base_firewall_rules`.

**Comment by mysticaltech** [comment]
Folks, I don't understand, what are you trying to do? If it's closing SSH and Kube API you can do it via the extra firewall rule, this will override the other default rules. Please forget the base rules, it's not the way to proceed IMHO.

**Comment by danackerson** [comment]
Aha, then it's probably just a bug:
```extra_firewall_rules = [
     {
      direction = "in"
      protocol  = "tcp"
      port      = "6443"
      source_ips = [
        "80.152.209.254/32"
      ]
    },

    # Allow all traffic to the ssh ports
    {
      direction = "in"
      protocol  = "tcp"
      port      = "22"
      source_ips = [
        "80.152.209.254/32"
      ]
    },
  ]
```

results in:
![appliedRules](https://user-images.githubusercontent.com/177846/204729855-58eff494-8c75-450c-affc-2d9fd114e6f6.png)

Shall I open an issue for this then?

**Comment by mysticaltech** [comment]
@danackerson Your above extra_ssh_rules definition is wrong, please try again with the `destination_ips = []` present, this is required, as per the example.

Also, keep in mind the priority of application of the rules, from top to bottom, the first one matched is the one taken into account. Source https://docs.hetzner.com/robot/dedicated-server/firewall/.

![ksnip_20221130-134121](https://user-images.githubusercontent.com/518555/204800025-39ab5ff1-bcb8-46e9-8793-08dff8c1397c.png)

**Comment by ifeulner** [comment]
Hi @mysticaltech after looking at the code I don't see how a "deny" could be implemented currently. 

There is a "concat" used, that means the `base_firewall_rules` and `extra_firewall_rules` are added, not merged. 
Even worse, with a different action in `extra_firwall_rules` are at the end of the chain, meaning the first the `base_firewall_rules` will be evaluated. And therefore ssh access allowed. To achieve this, the ssh rule needs actually to be deleted (as there is no explicit deny possible).

Or I am missing something? 

This is the relevant code: 
```
resource "hcloud_firewall" "k3s" {
  name = var.cluster_name

  dynamic "rule" {
    for_each = concat(local.base_firewall_rules, var.extra_firewall_rules)
    content {
      direction       = rule.value.direction
      protocol        = rule.value.protocol
      port            = lookup(rule.value, "port", null)
      destination_ips = lookup(rule.value, "destination_ips", [])
      source_ips      = lookup(rule.value, "source_ips", [])
    }
  }
}
```

**Comment by mysticaltech** [comment]
@ifeulner Yes, you are right, I implemented this logic myself. The reason why it works, and I have explained it above to @danackerson, is that Hetzner uses priorities, so if a ban is added (port 22 with source_ips = []) it will be matched first and used. 

The way Hetzner sees it at least, the order is reversed, so first extra rules, then base ones (see the screenshot from @danackerson, at least that is the order for the extra SSH rule).

So in the end, it works because of the Hetzner priorities in the rules, from top to down (the first rule matched is used), but perhaps not esthetically nice to see "duplicate" rules in the UI. But a working solution nonetheless (from my previous testing at least). 

Still, indeed if we can properly merge, it would definitely be more elegant! 🚀

**Comment by mysticaltech** [comment]
To everyone involved, PRs welcome to tweak this logic and implement proper merging.

**Comment by ifeulner** [comment]
> @ifeulner Yes, you are right, I implemented this logic myself. The reason why it works, and I have explained it above to @danackerson, is that Hetzner uses priorities, so if a ban is added (port 22 with source_ips = []) it will be matched first and used.
> 
> The way Hetzner sees it at least, the order is reversed, so first extra rules, then base ones (see the screenshot from @danackerson, at least that is the order for the extra SSH rule).
> 
> So in the end, it works because of the Hetzner priorities in the rules, from top to down (the first rule matched is used), but perhaps not esthetically nice to see "duplicate" rules in the UI. But a working solution nonetheless (from my previous testing at least).
> 
> Still, indeed if we can properly merge, it would definitely be more elegant! 🚀

Actually, it works only for additional "accepts", as there is no way to say "deny ssh-port", deny is the default, every rule is an accept. Right?

**Comment by mysticaltech** [comment]
Exactly! :)

**Comment by ifeulner** [comment]
So this rule should work with the current implementation:
```
  extra_firewall_rules = [
      # SSH Deny
    {
      direction       = "in"
      protocol        = "tcp"
      port            = "22"
      source_ips      = [] # no source IPs allowed
      destination_ips = [] # Won't be used for this rule
    }
  ]
```

**Comment by mysticaltech** [comment]
Yes! 

And if we want to tweak things, it's probably possible to use merge, as we can make it so that the extra rules take precedence during the merge. https://developer.hashicorp.com/terraform/language/functions/merge

**Comment by mysticaltech** [comment]
But @ifeulner, it will not work on first deploy of course! This "deny" change needs to be done on a second apply.

**Comment by danackerson** [comment]
Unfortunately, I now run into:
```
...
module.kube-hetzner.local_sensitive_file.kubeconfig[0]: Creation complete after 0s [id=cb302fea21e86d442bff62562fae794b7dfe08c9]
module.kube-hetzner.hcloud_firewall.k3s: Modifying... [id=616621]
╷
│ Error: invalid input in field 'rules' (invalid_input): [rules.source_ips => [source_ips needs to have at least one entry]]
│ 
│   with module.kube-hetzner.hcloud_firewall.k3s,
│   on .terraform/modules/kube-hetzner/main.tf line 36, in resource "hcloud_firewall" "k3s":
│   36: resource "hcloud_firewall" "k3s" {
```

with:
```
extra_firewall_rules = [
    # Allow all traffic to the ssh ports
    {
      direction       = "in"
      protocol        = "tcp"
      port            = "22"
      source_ips      = [] # no source IPs allowed
      destination_ips = [] # Won't be used for this rule
    }
  ]
```

**Comment by ifeulner** [comment]
@danackerson ah ok, I just did a `terraform plan` which didn't issue that error. Not the best way then, but obviously you have to set at least one IP address. If that one is secure/under your control, it should provide the same result - not accessible by all other IPs.

**Comment by danackerson** [comment]
Yep, this results in my orig. report above: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/436#issuecomment-1331725221 --> two rules for SSH access: "AnyIPv4" & "<my static ip>".

**Comment by mysticaltech** [comment]
Exactly... I missed that. So your original setup should work, please use a VPN to try @danackerson. Anyways, will be working on simplifying this with a proper merge this week-end, if no one jumps in to do it before.

**Comment by mysticaltech** [comment]
Or one could give a completely bogus IP too, like 255.255.255.254 for instance. But not pretty!

**Comment by mysticaltech** [comment]
@danackerson Did you try with a VPN to see if other IPs are really closed? What's your status on this?

**Comment by danackerson** [comment]
I've tried several times, but unluckily my extra rules are being merged *after* the defaults:

![Screenshot 2022-12-03 at 11 53 09](https://user-images.githubusercontent.com/177846/205437773-59950e52-a750-4ba2-af28-b6fa1c4f5322.png)

**Comment by mysticaltech** [comment]
@danackerson It's now fixed. The two rules set are now deduplicated succesfully. For instance, if you want to block SSH, just give it a dummy IP, like:
```

  extra_firewall_rules = [
    # Allow all traffic to the ssh ports
    {
      direction       = "in"
      protocol        = "tcp"
      port            = "22"
      source_ips      = ["255.255.255.254/32"] # no source IPs allowed
      destination_ips = []                     # Won't be used for this rule
    }
  ]
```
