### ISSUE TITLE
no Load Balancer found with name k3s

### ISSUE THREAD

**Issue by JustinGuese** [kube-hetzner/terraform-hcloud-kube-hetzner#444]
I am trying to upgrade from kube-hetzner 1.3 to 1.6.8, but I am getting this error on terraform plan
`no Load Balancer found with name k3s`

I tried setting the cluster name to something else, but the same error appears...

```
│ Error: no Load Balancer found with name k3s
│ 
│   with module.kube-hetzner.data.hcloud_load_balancer.cluster[0],
│   on .terraform/modules/kube-hetzner/data.tf line 20, in data "hcloud_load_balancer" "cluster":
│   20: data "hcloud_load_balancer" "cluster" {
```

**Comment by JustinGuese** [comment]
temporary fix:
replacing the "hcloud_load_balancer" name in 
`./.terraform/modules/kube-hetzner/data.tf` with the actual name of your load balancer in the existing cluster

**Comment by mysticaltech** [comment]
Exactly @JustinGuese! Happy you managed to make this work.

**Comment by JustinGuese** [comment]
is there a better way to upgrade the version btw?

**Comment by mysticaltech** [comment]
@JustinGuese For minor version changes, I believe that is the best way. But whenever we move major versions with massive breaking changes, then it would be best to use Velero to backup the cluster state and restore it on a new cluster deployed with the new version. 

If you are curious, please search the project, we have had a few discussions confirming that it works well.
