### ISSUE TITLE
Default loadbalancer for nginx ingress also targets control plane nodes

### ISSUE THREAD

**Issue by mysticaltech** [kube-hetzner/terraform-hcloud-kube-hetzner#447]
### Discussed in https://github.com/orgs/kube-hetzner/discussions/446

<div type='discussions-op-text'>

<sup>Originally posted by **MariusSchiffer** December  7, 2022</sup>
I have created a fresh cluster with 5 agent nodes and 3 control plane nodes.  
Unfortunately, the ingress loadbalancer not only targets the agent nodes, but also the control plane nodes.

Do you have any idea what influences this?</div>

**Comment by KaiGrassnick** [comment]
This Comment might help with this issue: https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/331#issuecomment-1344451969

TL;DR; - Set kubernetes label on Control-Plane Nodes:
```
labels:
  node.kubernetes.io/exclude-from-external-load-balancers: "true"
```

**Comment by mysticaltech** [comment]
@KaiGrassnick Thanks a lot for sharing this, appreciate it!

**Comment by captnCC** [comment]
@mysticaltech Should this be set by default for control planes? 🤔

**Comment by mysticaltech** [comment]
@captnCC It should be disabled for the control plane by default unless we enable scheduling on it. We need to open a PR, will do it ASAP.
