### ISSUE TITLE
Unable to destroy - Unsupported attribute

### ISSUE THREAD

**Issue by mandeepbrar** [kube-hetzner/terraform-hcloud-kube-hetzner#453]
I am trying to destroy resources created by terraform as they failed on ssh. 
I invoke `terraform destroy -auto-approve`
Receive this error
```

on .terraform/modules/kube-hetzner/kubeconfig.tf line 15, in locals:
│   15:   kubeconfig_external = replace(replace(data.remote_file.kubeconfig.content, "127.0.0.1", var.use_control_plane_lb ? hcloud_load_balancer.control_plane.*.ipv4[0] : module.control_planes[keys(module.control_planes)[0]].ipv4_address), "default", var.cluster_name)
│     ├────────────────
│     │ module.control_planes is object with 3 attributes
│ 
│ This object does not have an attribute named "ipv4_address".
```

**Comment by mysticaltech** [comment]
@mandeepbrar Your best bet is to delete the Hetzner project and try again. And for SSH, we have a doc just for that in the docs folder.

**Comment by mysticaltech** [comment]
@mandeepbrar There is a fix for that in the PRs that will be released on the week-end, please watch the releases to get a notification.
