### ISSUE TITLE
Failed server creation is not detected

### ISSUE THREAD

**Issue by TP-timecount** [kube-hetzner/terraform-hcloud-kube-hetzner#457]
As of writing this issue due to maintenance you cannot create a CX type server in location fsn1.

When deploying a new cluster with the config provided in /kube.tf.example using e.g. a CX21 for a control-planes with location fsn1 like:
```yml
{
      name        = "control-plane-hel1",
      server_type = "cx21",
      location    = "hel1",
      labels      = [],
      taints      = [],
      count       = 1
}
```
the failed/missing creation of this server is not detected until ca. 7 minutes into the deployment process.

```bash
module.kube-hetzner.module.agents["0-0-agent"].hcloud_server.server: Creation complete after 6m46s [id=26545131]
module.kube-hetzner.module.agents["0-0-agent"].hcloud_server_network.server: Creating...
module.kube-hetzner.module.agents["0-0-agent"].hcloud_server_network.server: Creation complete after 3s [id=26545131-2304008]

│ Error: error during placement (resource_unavailable)
│ 
│   with module.kube-hetzner.module.control_planes["0-0-control-plane-fsn1"].hcloud_server.server,
│   on ../kubehetzner/modules/host/main.tf line 22, in resource "hcloud_server" "server":
│   22: resource "hcloud_server" "server" {
│ 

```

**Comment by mysticaltech** [comment]
@TP-timecount Yes, this is how it works for now, as all nodes deploy in parallel, and it will retry until it timeouts. Thanks for pointing it out, but there is nothing we can do at this moment, and hopefully it is happening very rarely.
