### ISSUE TITLE
Custom TLS-SAN array

### ISSUE THREAD

**Issue by maaft** [kube-hetzner/terraform-hcloud-kube-hetzner#467]
It would be great to be able to add custom tls-san entries.

Use-case:
- if primary cp node goes down, you don't want to edit any IPs in your kubeconfig

Solution:
- have multiple A records `cp.cluster.my.org` pointing to all cp nodes
- add `cp.cluster.my.org` to tls-san in `/etc/rancher/k3s/config.yaml`

**Comment by mysticaltech** [comment]
This is quite easy, will do ASAP.
