### ISSUE TITLE
Pods and Deployments get recreated after 16h

### ISSUE THREAD

**Issue by cur1ou5soul** [kube-hetzner/terraform-hcloud-kube-hetzner#471]
I have a strange phenomenon -> my Pods inside my replicas get recreated ca. all 24h. 

I could not manage to find any answers on inside any log files. Only that I have a lot of restarts on my nodes.

**Comment by cur1ou5soul** [comment]
![1A289FBA-D9F9-44C7-B10C-42CEACA3028F](https://user-images.githubusercontent.com/57013347/209660953-e28b1aaf-7d1f-40b5-a817-dac767fb1078.jpeg)

**Comment by mysticaltech** [comment]
This is due to the automatic upgrade of each node. But since it does it node by node by properly draining it (done by kured), it is completely clean and expected.

**Comment by cur1ou5soul** [comment]
Alright so this would be daily? -> Just while I’m here is it possible to switch from traefik to nginx? Cause just setting enable_nginx enable_traefik nothing will change with terraform plan. - -Am 27.12.2022 um 14:53 schrieb Karim Naufal ***@***.***>:﻿
This is due to the automatic upgrade of each node. But since it does it node by node by properly draining it (done by kured), it is completely clean and expected.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
Yannick LangerDRUMS | BOOKING | LABEL📞 +49 9872 9566511 | 📱 +49 151 40152865📨 ***@***.*** |siskaselement.com
