### ISSUE TITLE
Use Autoscaling pool ONLY

### ISSUE THREAD

**Issue by Berndinox** [kube-hetzner/terraform-hcloud-kube-hetzner#474]
```
Error: Invalid function argument
on .terraform/modules/kube-hetzner/locals.tf line 72, in locals:
  agent_count            = sum([for v in var.agent_nodepools : v.count])
while calling sum(list)
var.agent_nodepools is empty list of dynamic
Invalid value for "list" parameter: cannot sum an empty list.
```
Of course i can create a static pool with the min worker number and create a autoscaling pool with a range from 0-_N_
But would be easier to allow autoscaling only pool

**Comment by mysticaltech** [comment]
@ifeulner What do you think about that request?

@berndinox @maaft, that should theoretically work IF and only if you allow scheduling on the control plane, for the autoscaler and other necessary pods to run.

**Comment by maaft** [comment]
@mysticaltech  good point about the autoscaler-node. there should at least one control-plane-node with scheduling enabled.

**Comment by Berndinox** [comment]
Hej, oh i totaly forgot about the "must have pods"....
Its not that important, but a "scale to zero" feature may be interesting for testing environemtns..?!

**Comment by mysticaltech** [comment]
@Berndinox This actually already works, but you just keep one agent nodepool and give it a count of 0.
