### ISSUE TITLE
Clarification of Certmanager with nginx-ingress

### ISSUE THREAD

**Issue by zypriafl** [kube-hetzner/terraform-hcloud-kube-hetzner#482]
The Readme states that 
"an additional step of adding this annotation load-balancer.hetzner.cloud/hostname to the Nginx service definition" is needed.

Can you help us to understand where exactly this annotation needs to be added?

Can this be done on an existing cluster or can this only be done on cluster creation?

Thanks for your help

**Comment by mysticaltech** [comment]
@zypriafl This discussion will answer your question https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/413.

**Comment by mysticaltech** [comment]
You can do it after cluster creation by creating an helmchartconfig yaml, please search the project for that, to understand how to do so. It's just one small yaml file that you need to apply. Basically first pull down the helmchart from the cluster, and create the helmchartconfig from it. Search the project for the full methodology!

**Comment by zypriafl** [comment]
Thanks for the hint. We have figured out now how to do this.
