### ISSUE TITLE
Changing SSH port causes endless waiting

### ISSUE THREAD

**Issue by Wuppie007** [kube-hetzner/terraform-hcloud-kube-hetzner#484]
In the kube.tf file I changed the (default) ssh port to something else. Now the terraform process (first run) is stuck at 

` Waiting for MicroOS to reboot and become available...`

When I use the console, I can see that OpenSSH is failing:
![afbeelding](https://user-images.githubusercontent.com/23653628/210398618-31c1326c-2e69-4ce0-8ced-0491fb45d3d3.png)

Now the created instances are stuck:

![afbeelding](https://user-images.githubusercontent.com/23653628/210398770-1d584ab4-4134-45f7-a135-9e8d4f058fa2.png)

**Comment by mysticaltech** [comment]
@Wuppie007 Your current IP must have been banned on the nodes. The best way is to change back the SSH port in Terraform and apply again via a VPN.

Ideally, the SSH port only can be changed on the first run.

**Comment by Wuppie007** [comment]
Sorry for not mentioning, but it was the first run.

**Comment by Wuppie007** [comment]
I also catched another error (maybe related) It appears while boothing opensuse for the first time:
![afbeelding](https://user-images.githubusercontent.com/23653628/210414775-aa51782c-6a26-4ee7-bc9f-b98e4cf997cb.png)

after that I can login " static login:"

![afbeelding](https://user-images.githubusercontent.com/23653628/210415571-84ffb510-e6d8-4c41-b44e-7c3725875cd7.png)

**Comment by mysticaltech** [comment]
@Wuppie007 I honestly do not know what could be happening. Could you please share your kube.tf, and also my advice is not to look at the Hetzner console, just look at the terraform output, that is what is needed here.

**Comment by Wuppie007** [comment]
Apperently port 2600 was not a suitable port for ssh. I changed to another random port with 5 digits and it worked.

so I close the issue :)

**Comment by mysticaltech** [comment]
Great to hear! Yes, as a rule of thumb, custom ports are best chosen in the range of 49152 through 65535, as they are unassigned and can hence be used for custom services.
