### ISSUE TITLE
The default HA

### ISSUE THREAD

**Issue by aleksasiriski** [kube-hetzner/terraform-hcloud-kube-hetzner#495]
I'm a beginner in Kubernetes, but I have one question.

> #### When this is enabled, rather than the first node, all external traffic will be routed via a control-plane loadbalancer, allowing for high availability.
> The default is false.
> use_control_plane_lb = true

What does it accomplish to, by default, you have 3 master nodes but don't create a LB for them? Does that mean the etcd and the likes are still HA but K8S API is potentionally unavailable if the first master goes down (unless you manually change the IP of the master in your kubectl config to the second or third master)?

**Comment by captnCC** [comment]
Yes, you got it right. The only purpose of the LB is high availability of the kube-api itself for external access. All other HA-features should be managed by k3s itself if there are 3 control planes in the cluster
