### ISSUE TITLE
Pods and Deployments get recreated after 16h 

### ISSUE THREAD

**Issue by zypriafl** [kube-hetzner/terraform-hcloud-kube-hetzner#509]
Hello,

Following up on #471, is there way to deactivate this behavior or set it to a longer period?
We have some long running tasks >24hours, that are retried when a pods get terminated, creating an endless loop.

**Comment by mysticaltech** [comment]
@zypriafl You have two upgrade processes that happen.

The OS and k3s. In your case, you may need to turn both off!

You can turn both off using different methods, see https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner#turning-off-automatic-upgrade

**Comment by zypriafl** [comment]
Thanks for your help.
