### ISSUE TITLE
Using Hetzner Load Balancer

### ISSUE THREAD

**Issue by digitalbuddha** [kube-hetzner/terraform-hcloud-kube-hetzner#512]
Hello and thank you for this wonderful project. I am new to the world of k8s and terraform.  I was able to follow your instructions and created a cluster successfully when I set `enable_klipper_metal_lb` to true

If I instead run without this line, I get an error that load balancer with name k3s does not exist. I think I should create the LB manually in hetzner console but was not sure. Is that a necessary step or did I miss something?

Thank you for your help.

**Comment by digitalbuddha** [comment]
update - once I started a new project it worked fine, I think it was because I was in an older project

**Comment by mysticaltech** [comment]
Exactly, see the destroy section in the readme, when destroying you have the delete the old Hetzner LB manually via the hcloud command or the UI.
