### ISSUE TITLE
Containers can't start with outbound - Is there a toggle to just disable the default outbound rules

### ISSUE THREAD

**Issue by aleksasiriski** [kube-hetzner/terraform-hcloud-kube-hetzner#513]
Ever since I switched from hetzner-k3s to this script I've had nothing but constant crashes and weird behaviour (with the same yaml files). 3 masters and 2 workers, containers just randomly died (not OOM) and now they're stuck at `Init:0/1` or `Pending` for no reason. I'm open that it may be my configs but this also happens with bitname postgres helm chart and it didn't happen on hetzner-k3s with Ubuntu hosts.

**Comment by aleksasiriski** [comment]
Ok I fixed containers being stuck by deleting all outbound rules that this script sets, I will look if any containers crash again

**Comment by aleksasiriski** [comment]
Are these outbound rules even useful for protection?? I literally have to allow all tcp and udp traffic over all IPv4 and IPv6 adresses for my containers to even start for some reason. I added this:
```
extra_firewall_rules = [
    # Disable firewall
    {
      direction       = "out"
      protocol        = "tcp"
      port            = "any"
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    },
    {
      direction       = "out"
      protocol        = "udp"
      port            = "any"
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    },
    {
      direction       = "out"
      protocol        = "icmp"
      port            = ""
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    }
  ]
```

**Comment by mysticaltech** [comment]
Your containers being constantly replaced is expected behavior. As both the node and k3s version upgrade, and almost daily for the former.

However you can turn this behavior off, search for "upgrade" in the readme.

For th e firewall rules, use our latest version, and with that the extra firewall rules take precedence over the default ones.

**Comment by aleksasiriski** [comment]
> Your containers being constantly replaced is expected behavior.
I know that and that's not what is happening. The crashes actually happened because I firstly deleted all outbound rules, then started all of my containers and then rerun the script which readded the outbound rules.

Having the default outbound rules that this script makes results in these docker images to not start up:
1. autoscan
2. radarr
3. bazarr
4. jellyfin
5. authelia
probably more...

Once I added this to kube.tf:
```
extra_firewall_rules = [
    # Disable firewall
    {
      direction       = "out"
      protocol        = "tcp"
      port            = "any"
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    },
    {
      direction       = "out"
      protocol        = "udp"
      port            = "any"
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    },
    {
      direction       = "out"
      protocol        = "icmp"
      port            = ""
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    }
  ]

```

I effectively disabled the outbound firewall which fixes those issues for me. My question now is, why are those outbound rules even used, I can't be the only one that has issues with them?

**Comment by ifeulner** [comment]
Well, most important: Know your images / containers you are running within your cluster and what they do / require. 
The out-of-the-box firewall rules allow connections from within the cluster only to basic services (DNS, HTTP(S), ICMP) for security reasons.

Your mentioned images are for implementing a media center or something like that  if I get it right, that's not the most common use case for a kubernetes cluster... but anyway, it's possible if you adjust the firewall settings according to the needed connectivity.
