### ISSUE TITLE
Three letters getting added to the end of the name

### ISSUE THREAD

**Issue by harrisonratcliffe** [kube-hetzner/terraform-hcloud-kube-hetzner#515]
Hello, does anyone know how to disable the three random letters being added at the end of each server name? What are they added for?

Examples:

- k3s-a-agent-1-qsr
- k3s-a-agent-2-xil

**Comment by harrisonratcliffe** [comment]
Sorry! This probably should have been created under discussions.

**Comment by aleksasiriski** [comment]
If you have a pool with more than 1 nodes then they will all be named `k3s-a-agent-1` and so the three letters at the end are required to distinguish between multiple nodes of the same pool.

**Comment by harrisonratcliffe** [comment]
@aleksasiriski Ah yes, I have the count set to 1 so didn't take that into account. Thank you.

Please close.

**Comment by aleksasiriski** [comment]
I'm not the dev nor do I have access to this repo, but you can close your own issues.
