### ISSUE TITLE
Increase Traefik replicas

### ISSUE THREAD

**Issue by aleksasiriski** [kube-hetzner/terraform-hcloud-kube-hetzner#518]
Is there a way to make Traefik HA? As I can see the default install only makes a single replica, which results in downtime when a node that has Traefik drains for updates.

**Comment by mysticaltech** [comment]
Traefik HA is only available if you use their premium version, however you still can have it run in daemonset mode it seems. You need to either configure the traefik_values variable before deploy, or edit the Traefik helmchartconfig after deploy! https://forums.rancher.com/t/ha-traefik-ingress/39331

For more flexible options, best use ingress-nginx that you can activate in kube.tf before launch, while turning off traefik.

**Comment by aleksasiriski** [comment]
Damn that's sad to hear, but thanks! I'll switch back to ingress nginx.

**Comment by aleksasiriski** [comment]
Traefik docs say that if you want to use multiple replicas you can't use integrated acme, but if you use cert-manager you can have multiple replicas (without switching to enterprise).

Is there a way to set replica count to 3 in kube.tf?

I can see that there is `traefik_ingress_values` that is loaded from kube.tf (although it's missing from example), but it would be nicer if it was a seperate option, like it is for longhorn.

**Comment by mysticaltech** [comment]
@aleksasiriski Traefik works the same way as Longhorn, it uses rancher helmchart/helmchartconfig definition behind the scene (please search this project to learn more about those).

Basically, as mentioned in kube.tf, go to the traefik values yaml, search replicas, and reproduce the path in yaml in your custom values variable and set the replicas count of the deployment to 3.

Or for clusters already running, you can `kubectl edit helmchatconfig traefik` (or just list the names if that is not found), and edit the values there.
