### ISSUE TITLE
access a pod as a root user

### ISSUE THREAD

**Issue by digitalbuddha** [kube-hetzner/terraform-hcloud-kube-hetzner#520]
Hi folks, I am using the hetzner kube with a mastodon helm chart which installs a few pods. In one of the pods I need to run exec a shell script after install.  I thought I would be able to `exec` but keep getting a permission denied error. I am assuming it is because the script was installed by root and not my no name user. 

My question is whether there is a way to run a bash shell as root within this setup?

**Comment by mysticaltech** [comment]
Yes, you can execute as root. Actually, we do not have another user. Just SSH into the node, see the readme, and you can run any commands you want.

**Comment by mysticaltech** [comment]
On the control plane nodes, you will also have access to kubectl.
