### ISSUE TITLE
Snapshot of MicroOS

### ISSUE THREAD

**Issue by aleksasiriski** [kube-hetzner/terraform-hcloud-kube-hetzner#521]
Why is autoscaler using snapshot for promptly bringing up nodes but the script itself installs MicroOS manually on all nodes? Wouldn't it be more logical and faster to create a single snapshot and use that for installing every node and afterwards continue to use it or just delete it?

**Comment by mysticaltech** [comment]
@aleksasiriski Yes, good observation, and that is something we will be launching in v2.0, maybe in a month or two. Make sure to follow the releases.

**Comment by mysticaltech** [comment]
@aleksasiriski While I have you on the line. Just invited you to join the team! Please feel free to accept. I will give you access to our internal team discussion, and move sway on the future of that project. I like your ideas and you have been helping a lot lately, so welcome to the club if you accept!

We have a few members, but some of them don't show up for a long time. It doesn't matter. At least we have a few active ones as you have seen!

**Comment by mysticaltech** [comment]
@aleksasiriski Now that you are part of the team, that's the vision we have for v2.0. https://github.com/orgs/kube-hetzner/teams/core/discussions/5/comments/23
