### ISSUE TITLE
Question: Why is K3S set to not use SELinux?

### ISSUE THREAD

**Issue by aleksasiriski** [kube-hetzner/terraform-hcloud-kube-hetzner#522]
Question: Why is K3S set to not use SELinux?

**Comment by mysticaltech** [comment]
Yes, it does use SELinux, but that is activated after the installation. We just ask the script to not install it for us, as we do this sooner followed by a reboot to activate the new snapshot after installing the SELinux rules. Then, after the k3s were installed, we apply the rules ourselves. So it's using it!

https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/29bfaf0210883946174bab2cef51c81c3f20feb1/locals.tf#L25

**Comment by mysticaltech** [comment]
@aleksasiriski If it's not a real issue, please use discussions as we have a Q&A section there, and don't hesitate to tag me directly.
