### ISSUE TITLE
HCloud CSI having errors after draining and rebooting the cluster

### ISSUE THREAD

**Issue by aleksasiriski** [kube-hetzner/terraform-hcloud-kube-hetzner#524]
![image](https://user-images.githubusercontent.com/31509435/213202913-a2d5b1d2-a282-4f1a-b090-940815c4db83.png)
![image](https://user-images.githubusercontent.com/31509435/213203075-66d5f539-00a1-4042-98b0-99f7130ac251.png)

**Comment by aleksasiriski** [comment]
Both the `csi-controller` and the single failing `csi-node` pods are running on the same Hetzner VPS

**Comment by aleksasiriski** [comment]
```Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  24s                default-scheduler  Successfully assigned kube-system/hcloud-csi-node-zr5cp to tmina-agent-main-fsn1-sas
  Normal   Pulled     24s                kubelet            Container image "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.2.0" already present on machine
  Normal   Created    24s                kubelet            Created container csi-node-driver-registrar
  Normal   Started    24s                kubelet            Started container csi-node-driver-registrar
  Normal   Pulled     23s                kubelet            Successfully pulled image "hetznercloud/hcloud-csi-driver:2.1.0" in 723.705456ms
  Normal   Created    23s                kubelet            Created container hcloud-csi-driver
  Normal   Started    23s                kubelet            Started container hcloud-csi-driver
  Normal   BackOff    22s (x2 over 23s)  kubelet            Back-off pulling image "registry.k8s.io/sig-storage/livenessprobe:v2.3.0"
  Warning  Failed     22s (x2 over 23s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    9s (x2 over 23s)   kubelet            Pulling image "registry.k8s.io/sig-storage/livenessprobe:v2.3.0"
  Warning  Failed     9s (x2 over 23s)   kubelet            Error: ErrImagePull
  Warning  Failed     9s (x2 over 23s)   kubelet            Failed to pull image "registry.k8s.io/sig-storage/livenessprobe:v2.3.0": rpc error: code = Unknown desc = failed to pull and unpack image "registry.k8s.io/sig-storage/livenessprobe:v2.3.0": failed to resolve reference "registry.k8s.io/sig-storage/livenessprobe:v2.3.0": pulling from host registry.k8s.io failed with status code [manifests v2.3.0]: 403 Forbidden
  Normal   Pulling    4s (x2 over 24s)   kubelet            Pulling image "hetznercloud/hcloud-csi-driver:2.1.0"
  Warning  Unhealthy  4s (x5 over 12s)   kubelet            Liveness probe failed: Get "http://10.42.6.69:9808/healthz": dial tcp 10.42.6.69:9808: connect: connection refused
  Normal   Killing    4s                 kubelet            Container hcloud-csi-driver failed liveness probe, will be restarted
  Normal   Pulled     3s                 kubelet            Successfully pulled image "hetznercloud/hcloud-csi-driver:2.1.0" in 759.968433ms```

**Comment by aleksasiriski** [comment]
Scaling the pool from 2 nodes to 1 removed the troubling node, but then after scaling from 1 to 2 and creating a completely new node it results in the same behavior, as if hcloud-csi is rate limiting me...

**Comment by mysticaltech** [comment]
@aleksasiriski Glad, you fixed it the way you did, but there was another way. This explains what was happening, and the fix! https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/505

**Comment by aleksasiriski** [comment]
This happened to me and the fix.sh script didn't work.. I had to delete my cluster project, then create new one, buy 10 IPs so that I got all of the old ones, create a new cluster which FINALLY got all new IPs and only after that delete the reserved IPs that were blacklisted...

**Comment by mysticaltech** [comment]
@aleksasiriski What do you mean buy 10 IPs? What was the exact process? Are you talking about Hetzner cloud-fixed IPs?  And do those get used when making the requests to the container registry, it seems unlikely. Please explain!

**Comment by aleksasiriski** [comment]
> @aleksasiriski What do you mean buy 10 IPs? What was the exact process? Are you talking about Hetzner cloud-fixed IPs? And do those get used when making the requests to the container registry, it seems unlikely. Please explain!

I went into IP interface and got 10 static IPs from Hetzner that weren't assigned to any servers, so I got all of my previous rate limited IPs and then went to create the cluster which finally got all new IPs I never had and they weren't rate limited.

The issue for me was always getting same IPs

**Comment by mysticaltech** [comment]
@aleksasiriski Thanks for clarifying. Super smart haha, well done!
