### ISSUE TITLE
Hetzner Cloud Networks

### ISSUE THREAD

**Issue by shyblower** [kube-hetzner/terraform-hcloud-kube-hetzner#527]
You write in your feature list:
"Proper use of the Hetzner private network to minimize latency and remove the need for encryption."

But the Hetzner FAQ (https://docs.hetzner.com/cloud/networks/faq) state this:
Q: "Is traffic inside Hetzner Cloud Networks encrypted?"
A: "Traffic between cloud servers inside a Network is private and isolated, but not automatically encrypted. We recommend you use TLS or similar protocols to encrypt sensitive traffic."

So Hetzner Cloud private networks are assumably isolated from from other Hetzner networks but obviously not encrypted, which might pose a security risk, particularly when nodes are connected over the "private network" between different Hetzner data centers which is probably just tunneled over the internet, but as they say, unencrypted.

It should be possible to configure the CNI to use e.g. Flannel with the Wireguard backend for encryption as they do here:
https://github.com/StarpTech/k-andy/pull/15

**Comment by mysticaltech** [comment]
@shyblower You are right! Thanks for bringing this to our attention. @kube-hetzner/core FYI.

Please feel free to submit a PR adding support for wireguard with flannel (the k3s config happens in control_planes.tf, agents.tf, and init.tf), otherwise, we will do it ASAP.

**Comment by ifeulner** [comment]
Hi @shyblower I didn't test it yet but it should work with some additional settings "out-of-the-box" I think:

- Add `wireguard-tools` to `extra_packages_to_install ` variable
- add  `flannel-backend=wireguard-native` to `control_planes_custom_config` variable (also see [k3s docs](https://docs.k3s.io/reference/server-config#networking) )
- create the cluster

That *should* work, but as said, not tested yet. Maybe you can give it a try?

**Comment by shyblower** [comment]
Thank you, I will try and report back, but it will probably take some time. I'm not sure that I can do it today.

**Comment by valkenburg-prevue-ch** [comment]
> * Add `wireguard-tools` to `extra_packages_to_install ` variable
> * add  `flannel-backend=wireguard-native` to `control_planes_custom_config` variable (also see [k3s docs](https://docs.k3s.io/reference/server-config#networking) )
> * create the cluster

I tested it now and it seems to work exactly this way. For full transparency though, I am right now running with a modified locals.tf as per [this issue](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/528) . I hope this has no relevance.

**Comment by ifeulner** [comment]
> > * Add `wireguard-tools` to `extra_packages_to_install ` variable
> > * add  `flannel-backend=wireguard-native` to `control_planes_custom_config` variable (also see [k3s docs](https://docs.k3s.io/reference/server-config#networking) )
> > * create the cluster
> 
> I tested it now and it seems to work exactly this way. For full transparency though, I am right now running with a modified locals.tf as per [this issue](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/528) . I hope this has no relevance.

Cool, great to see that the customization options are used and do work.

Will check the other issue you addressed.
