### ISSUE TITLE
Disable ingress loadbalancer creation

### ISSUE THREAD

**Issue by dictvm** [kube-hetzner/terraform-hcloud-kube-hetzner#531]
I started using this project for a new venture I'm working on. It's a great start for ramp up some infrastructure. However, I'd love to have a binary toggle for the loadbalancer because I prefer to have my loadbalancer managed by the ingress controller I'm spinning up with flux after cluster creation.

From what I gathered I can only control the creation of the HA-loadbalancer for the control plane but not the one meant for ingress.

**Comment by aleksasiriski** [comment]
> # If you want to enable the Nginx ingress controller (https://kubernetes.github.io/ingress-nginx/) instead of Traefik, you can set this to "nginx". Default is "traefik".
>  # By the default we load optimal Traefik and Nginx ingress controller config for Hetzner, however you may need to tweak it to your needs, so to do,
> # we allow you to add a traefik_values and nginx_values, see towards the end of this file in the advanced section.
> # After the cluster is deployed, you can always use HelmChartConfig definition to tweak the configuration.
> # If you want to disable both controllers set this to "none"
> # ingress_controller = "nginx"

So just set ```ingress_controller = "none"``` and there would be no ingress controller deployed which results in no creating of LB. Or if you already made the cluster just delete the namespace `traefik` or `nginx` and that should remove the ingress controller and all of it's resources.

**Comment by dictvm** [comment]
I missed that, thanks so much!
