### ISSUE TITLE
Error: remote-exec provisioner error

### ISSUE THREAD

**Issue by jhelbling** [kube-hetzner/terraform-hcloud-kube-hetzner#534]
╷
│ Error: remote-exec provisioner error
│
│   with module.kube-hetzner.null_resource.first_control_plane,
│   on .terraform/modules/kube-hetzner/init.tf line 43, in resource "null_resource" "first_control_plane":
│   43:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_80786990.sh": Process exited with status 1

  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "control-plane-nbg1",
      server_type = "cpx11",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "control-plane-fns1",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]

  agent_nodepools = [
    {

    {
      name        = "agent-small",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 3
    },
    {
      name        = "agent-large",
      server_type = "cpx21",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 3
    },
    {
      name        = "storage",
      server_type = "cpx21",
      location    = "fsn1",
      # Fully optional, just a demo.
      labels      = [
        "node.kubernetes.io/server-usage=storage"
      ],
      taints      = [],
      count       = 3

**Comment by vesurbag** [comment]
I have the same error. I found that `/sbin/semodule -v -i /usr/share/selinux/packages/k3s.pp` returns
```
Ok: return value of 0.
Committing changes:
Conflicting name type transition rules
Binary policy creation failed at /var/lib/selinux/targeted/tmp/modules/400/k3s/cil:135
Failed to generate binary
/sbin/semodule:  Failed!
```

**Comment by aleksasiriski** [comment]
Duplicate:
https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/528#issuecomment-1402984128

**Comment by mysticaltech** [comment]
@vesurbag @jhelbling Just run "terraform init -upgrade" to update to the latest module!
