### ISSUE TITLE
403s on MicroOS download causing deployment failure

### ISSUE THREAD

**Issue by sandrinr** [kube-hetzner/terraform-hcloud-kube-hetzner#535]
If there is an error setting up a control plane node, rectifying that error state does not seem to be obvious.

In may case, when deploying a new cluster, the download of `openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2` failed with `ERROR 403: Forbidden.` on one of the nodes.

Terraform correctly terminated the apply with:
```
│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.module.control_planes["1-0-control-plane-nbg1"].hcloud_server.server,
│   on .terraform/modules/kube-hetzner/modules/host/main.tf line 64, in resource "hcloud_server" "server":
│   64:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_1335984070.sh": Process exited with status 8
```

Running `terraform apply` again correctly identifies the node that has to be replaced:
```
  # module.kube-hetzner.module.control_planes["1-0-control-plane-nbg1"].hcloud_server.server is tainted, so must be replaced
+/- resource "hcloud_server" "server" {
      + backup_window              = (known after apply)
      ~ datacenter                 = "nbg1-dc3" -> (known after apply)
      ~ id                         = "27970132" -> (known after apply)
      ~ ipv4_address               = "redacted" -> (known after apply)
      ~ ipv6_address               = "redacted" -> (known after apply)
      ~ ipv6_network               = "redacted" -> (known after apply)
        name                       = "k3s-control-plane-nbg1-yhf"
      ~ status                     = "running" -> (known after apply)
        # (15 unchanged attributes hidden)
    }
```

However, the application of the plan then exists with:
```
module.kube-hetzner.module.control_planes["1-0-control-plane-nbg1"].hcloud_server.server: Creating...
╷
│ Error: server name is already used (uniqueness_error)
│ 
│   with module.kube-hetzner.module.control_planes["1-0-control-plane-nbg1"].hcloud_server.server,
│   on .terraform/modules/kube-hetzner/modules/host/main.tf line 22, in resource "hcloud_server" "server":
│   22: resource "hcloud_server" "server" {
```

Is this expected behavior? Is further manual intervention expected/needed in such situations?

<details>
<summary>Version details</summary>

[terraform-hcloud-kube-hetzner](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner) version: 1.8.1
```
$ terraform version
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hetznercloud/hcloud v1.36.2
+ provider registry.terraform.io/integrations/github v5.16.0
+ provider registry.terraform.io/tenstad/remote v0.1.1
```
</details>

**Comment by aleksasiriski** [comment]
Just delete the aforementioned server from the Hetzner web interface and then rerun the script.

**Comment by mysticaltech** [comment]
@sandrinr In the kube.tf, you have an variable called `opensuse_microos_mirror_link`, just uncomment it! It is already said with a known good mirror that will not return a 403.

Then, "terraform destroy" and "terraform apply" again!

**Comment by sandrinr** [comment]
Thank you for you answer. I was aware that I can manually set the image download link or destroy the server. My point with this ticket is whether this is expected behavior. From a terraform point of view the resource replacement should "just work" as far as I understand it.

If it is expected for `terraform apply` to fail in this circumstance, then let's just close this issue.

**Comment by aleksasiriski** [comment]
Well most of the time it does work, but I also encountered the "bug" you're describing, it's just happens sometimes but rarely..

**Comment by mysticaltech** [comment]
@sandrinr I changed the link just yesterday, to the automatic mirror selection one, but if we see more 403s, I will revert to the known working link. The reason, I did the switch is the speed of download was not always amazing!

In the near future, we will also move to a snapshot-based deployment, by adding `packer` in the loop! Initial work on this was already done here if you want to have a look https://github.com/kube-hetzner/packer-hcloud-microos

**Comment by mysticaltech** [comment]
@aleksasiriski Just for clarity, it's not really a bug from us, but apparently some of the mirrors have blacklisted some Hetzner IPs. But the upcoming packer approach does the download on localhost so it solves this whole issue and is super elegant.

**Comment by aleksasiriski** [comment]
> @aleksasiriski Just for clarity, it's not really a bug from us, but apparently some of the mirrors have blacklisted some Hetzner IPs. But the upcoming packer approach does the download on localhost so it solves this whole issue and is super elegant.

Can't wait for that MR (:

**Comment by ifeulner** [comment]
> > @aleksasiriski Just for clarity, it's not really a bug from us, but apparently some of the mirrors have blacklisted some Hetzner IPs. But the upcoming packer approach does the download on localhost so it solves this whole issue and is super elegant.
> 
> Can't wait for that MR (:

Working on it... :)
