### ISSUE TITLE
Cant get IP from LB, timeout

### ISSUE THREAD

**Issue by bulnv** [kube-hetzner/terraform-hcloud-kube-hetzner#539]
Hey! I am trying to spin up new cluster on 1.8.2 module but facing this error

```module.kube-hetzner.null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
module.kube-hetzner.null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
module.kube-hetzner.null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...

│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.null_resource.kustomization,
│   on .terraform/modules/kube-hetzner/init.tf line 246, in resource "null_resource" "kustomization":
│  246:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_1613767178.sh": Process exited with status 124
╵
╷
│ Error: attach server to network: provided IP is not available (ip_not_available)
│ 
│   with module.kube-hetzner.module.agents["1-0-agent-large"].hcloud_server_network.server,
│   on .terraform/modules/kube-hetzner/modules/host/main.tf line 214, in resource "hcloud_server_network" "server":
│  214: resource "hcloud_server_network" "server" {```

my config is pretty simple

`
module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = local.hcloud_token
  source = "kube-hetzner/kube-hetzner/hcloud"
  version = "1.8.2"
  ssh_public_key  = file("./id_ed25519_k8s.pub")
  ssh_private_key = file("./id_ed25519_k8s")
  network_region  = "eu-central" # change to us-east if location is ash
  control_plane_nodepools = local.env == "staging" ? local.staging_control_plane_nodepools : local.production_control_plane_nodepools
  agent_nodepools = local.env == "staging" ? local.staging_agent_nodepools : local.production_agent_nodepools
  load_balancer_type     = "lb11"
  load_balancer_location = "fsn1"
  autoscaler_nodepools = [
    {
      name        = "autoscaler"
      server_type = "cpx21" # must be same or better than the control_plane server type (regarding disk size)!
      location    = "fsn1"
      min_nodes   = 0
      max_nodes   = 5
    }
  ]
  etcd_s3_backup = {
    etcd-s3-endpoint   = "***"
    etcd-s3-access-key = "k8s-backups"
    etcd-s3-secret-key = "***"
    etcd-s3-bucket     = "k8s-backups"
  }

  automatically_upgrade_k3s = false
  automatically_upgrade_os = false
  cluster_name = format("%s-%s-k8s", local.project, local.env)
  restrict_outbound_traffic = false
  disable_network_policy = true

  `

from the console I can see that one of worker cannot obtain private IP

**Comment by aleksasiriski** [comment]
How many masters and workers do you have?

**Comment by bulnv** [comment]
> How many masters and workers do you have?

1 master cpx11 and 2 workers cpx11 and cpx21

**Comment by aleksasiriski** [comment]
@mysticaltech Isn't in case of 1 master KlipperLB used instead of Hetzner LB? In that case it shouldn't even wait for an IP

**Comment by mysticaltech** [comment]
@aleksasiriski KlipperLB is only used by default on a single node cluster, 1 control-plane & 0 agents.

@bulnv Please try to run the terraform apply directly again.

And also post the output of kubectl get pods -A, and kubectl get svc -A.

**Comment by vesurbag** [comment]
I had the same error when used `nginx` ingress controller. This is because script is trying to get service `ngx-ingress-nginx-controller` (https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/locals.tf#L291) but service has name `nginx-ingress-nginx-controller`

**Comment by aleksasiriski** [comment]
> I had the same error when used `nginx` ingress controller. This is because script is trying to get service `ngx-ingress-nginx-controller` (https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/locals.tf#L291) but service has name `nginx-ingress-nginx-controller`

That's my mistake, will fix it ASAP

**Comment by aleksasiriski** [comment]
@mysticaltech I pushed to staging, but I forgot about the wireguard additions in there.. should I make the same commit directly to master since it's just a small change, or will we merge staging to master soon?

**Comment by bulnv** [comment]
> 

```❯ kubectl get pods -A
NAMESPACE        NAME                                               READY   STATUS    RESTARTS   AGE
kube-system      cluster-autoscaler-74dc887cdb-89wnl                1/1     Running   0          17m
kube-system      coredns-597584b69b-rhmwv                           1/1     Running   0          18m
kube-system      hcloud-cloud-controller-manager-7b7f9d4455-tdntb   1/1     Running   0          18m
kube-system      hcloud-csi-controller-57f546df64-4tbj2             0/5     Pending   0          18m
kube-system      hcloud-csi-node-svmsg                              3/3     Running   0          18m
kube-system      helm-install-cert-manager-gcpsg                    0/1     Pending   0          18m
kube-system      helm-install-traefik-5zpg5                         0/1     Pending   0          18m
kube-system      kured-h7ftv                                        1/1     Running   0          17m
kube-system      metrics-server-5f9f776df5-lr6pr                    1/1     Running   0          18m
system-upgrade   system-upgrade-controller-6cb5bf6fb8-jmvdn         1/1     Running   0          18m
❯ kubectl get svc -A
NAMESPACE     NAME                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes                      ClusterIP   10.43.0.1       <none>        443/TCP                  18m
kube-system   hcloud-csi-controller-metrics   ClusterIP   10.43.156.176   <none>        9189/TCP                 18m
kube-system   hcloud-csi-node-metrics         ClusterIP   10.43.246.16    <none>        9189/TCP                 18m
kube-system   kube-dns                        ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP   18m
kube-system   metrics-server                  ClusterIP   10.43.48.237    <none>        443/TCP      ```

**Comment by aleksasiriski** [comment]
> > @mysticaltech
> 
> ```
> NAMESPACE        NAME                                               READY   STATUS    RESTARTS   AGE
> kube-system      cluster-autoscaler-74dc887cdb-89wnl                1/1     Running   0          17m
> kube-system      coredns-597584b69b-rhmwv                           1/1     Running   0          18m
> kube-system      hcloud-cloud-controller-manager-7b7f9d4455-tdntb   1/1     Running   0          18m
> kube-system      hcloud-csi-controller-57f546df64-4tbj2             0/5     Pending   0          18m
> kube-system      hcloud-csi-node-svmsg                              3/3     Running   0          18m
> kube-system      helm-install-cert-manager-gcpsg                    0/1     Pending   0          18m
> kube-system      helm-install-traefik-5zpg5                         0/1     Pending   0          18m
> kube-system      kured-h7ftv                                        1/1     Running   0          17m
> kube-system      metrics-server-5f9f776df5-lr6pr                    1/1     Running   0          18m
> system-upgrade   system-upgrade-controller-6cb5bf6fb8-jmvdn         1/1     Running   0          18m
> ❯ kubectl get svc -A
> NAMESPACE     NAME                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
> default       kubernetes                      ClusterIP   10.43.0.1       <none>        443/TCP                  18m
> kube-system   hcloud-csi-controller-metrics   ClusterIP   10.43.156.176   <none>        9189/TCP                 18m
> kube-system   hcloud-csi-node-metrics         ClusterIP   10.43.246.16    <none>        9189/TCP                 18m
> kube-system   kube-dns                        ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP   18m
> kube-system   metrics-server                  ClusterIP   10.43.48.237    <none>        443/TCP      ```
> ```

This isn't related to nginx bug since you're using Traefik, I'll look into it now

**Comment by aleksasiriski** [comment]
That may be related to the cluster autoscaler.

**Comment by aleksasiriski** [comment]
Could you paste your node pool definitions? Since I can't tell much from `agent_nodepools = local.env == "staging" ? local.staging_agent_nodepools : local.production_agent_nodepools`

**Comment by bulnv** [comment]
> n't tell much from `agent_nodepools = local.env == "staging" ? local.staging_agent_nodepools : local.production_agent_nodepools`

```  staging_control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]

  staging_agent_nodepools = [
    {
      name        = "agent-large",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "agent-large",
      server_type = "cpx21",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]

**Comment by aleksasiriski** [comment]
My best guess would be to try without your `local` file from which it reads those definitions, it may intervene with the script's `locals.tf` but not 100% sure on that..

**Comment by mysticaltech** [comment]
@aleksasiriski Thanks for taking care of this so rapidly. Let's do a quick PR from a branch, and you can merge it to master directly and i will issue a release immediately, so that we do not have an empty release (without mention of any PRs).

**Comment by mysticaltech** [comment]
@bulnv You cannot have the same name for two nodepools, just change that, destroy, and redeploy. 

![ksnip_20230126-184050](https://user-images.githubusercontent.com/518555/214909592-51431157-3f6d-48fb-bf1b-22d9583eb5ab.png)

And if using nginx for ingress (the default is traefik), wait a few minutes so we publish the fix, while making sure to run `terraform init -upgrade` to fetch the new updated module.

Wait for our signal (if using nginx).

**Comment by aleksasiriski** [comment]
@mysticaltech Pushed to master, and updated staging so it's not behind. Hope I did it the way you wanted, never really played much with branches.

**Comment by mysticaltech** [comment]
Ok, it's good. Will do a patch release then!

**Comment by bulnv** [comment]
@mysticaltech  @aleksasiriski update from me (TS) the issue seems to be in the exported kubekonfig file. I used relative path like "~/.kube.blah" which has created '~' subdirectory in TF folder. When I used an absolute path module started working fine. So I guess the issue can be closed. Thanks for lighting fast help and jumping in!

**Comment by Keyruu** [comment]
I have the exact opposite problem here. I just upgraded from 1.6.5 to 2.1.5 and my service name is `ngx-ingress-nginx-controller` but it tries to search for `nginx-ingress-nginx-controller`. How do I fix this?

**Comment by mrclrchtr** [comment]
> @bulnv You cannot have the same name for two nodepools, just change that, destroy, and redeploy.
> 
> ![ksnip_20230126-184050](https://user-images.githubusercontent.com/518555/214909592-51431157-3f6d-48fb-bf1b-22d9583eb5ab.png)
> 
> And if using nginx for ingress (the default is traefik), wait a few minutes so we publish the fix, while making sure to run `terraform init -upgrade` to fetch the new updated module.
> 
> Wait for our signal (if using nginx).

Thx @mysticaltech. I had the same problem at the end of the cluster creation and found this post here. 

The Error:
```
Error: attach server to network: provided IP is not available (ip_not_available)
│ 
│   with module.kube-hetzner.module.agents["5-0-agent-arm-small"].hcloud_server_network.server,
│   on .terraform/modules/kube-hetzner/modules/host/main.tf line 129, in resource "hcloud_server_network" "server":
│  129: resource "hcloud_server_network" "server" {
```
Could it be a good idea and is it possible to validate that each name exists only once and throw an error at the start already if one exists multiple times?

**Comment by mysticaltech** [comment]
> > @bulnv You cannot have the same name for two nodepools, just change that, destroy, and redeploy.
> > 
> > ![ksnip_20230126-184050](https://user-images.githubusercontent.com/518555/214909592-51431157-3f6d-48fb-bf1b-22d9583eb5ab.png)
> > 
> > And if using nginx for ingress (the default is traefik), wait a few minutes so we publish the fix, while making sure to run `terraform init -upgrade` to fetch the new updated module.
> > 
> > Wait for our signal (if using nginx).
> 
> Thx @mysticaltech. I had the same problem at the end of the cluster creation and found this post here. 
> 
> The Error:
> ```
> Error: attach server to network: provided IP is not available (ip_not_available)
> │ 
> │   with module.kube-hetzner.module.agents["5-0-agent-arm-small"].hcloud_server_network.server,
> │   on .terraform/modules/kube-hetzner/modules/host/main.tf line 129, in resource "hcloud_server_network" "server":
> │  129: resource "hcloud_server_network" "server" {
> ```
> Could it be a good idea and is it possible to validate that each name exists only once and throw an error at the start already if one exists multiple times?

@mrclrchtr This does not seem related to LBs, it's about IPs. Just make sure you change the cluster name if you have other clusters in the same project, also make sure to destroy not only with terraform destroy but also with cleanupkh (see readme) when the latter starts to end. Finally do chech Hetzner status over at status.hetzner.com.

**Comment by mrclrchtr** [comment]
@mysticaltech changing the nodepool-names fixed it for me. Without the steps you described. But thank you very much for your support.
