### ISSUE TITLE
Is there an option to copy file to control-plane nodes while cluster creating?

### ISSUE THREAD

**Issue by vesurbag** [kube-hetzner/terraform-hcloud-kube-hetzner#544]
I need to pass `authentication-token-webhook-config-file` to kube-apiserver arguments in my configuration:
```
control_planes_custom_config = {
    kube-apiserver-arg = "authentication-token-webhook-config-file=/etc/webhook.yaml"
}
```
But it's too tiring to copy `webhook.yaml` file manually to the server when script is running. 

Is it possible to copy from local file or create file with content to the control-panel via `kube.tf`?

**Comment by mysticaltech** [comment]
@vesurbag Yes! I believe we do these kinds of operations in the project already. Search for "file" in the code my give you what you need.

**Comment by vesurbag** [comment]
@mysticaltech Got it, thanks a lot for the detailed answer!
