### ISSUE TITLE
Is touch /var/run/reboot-required wiser then systemctl restart k3s? 

### ISSUE THREAD

**Issue by valkenburg-prevue-ch** [kube-hetzner/terraform-hcloud-kube-hetzner#548]
https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/cf2ef6bbac78097015cd969c71882145b534df68/modules/host/main.tf#L199

The docs at https://docs.k3s.io/installation/private-registry state:
"In order for the registry changes to take effect, you need to restart K3s on each node."

if we replace 
```
touch /var/run/reboot-required
```
with
```
if systemctl status k3s > /dev/null; then 
  systemctl restart k3s; 
elif systemctl status k3s-agent > /dev/null; then 
  systemctl restart k3s-agent; 
fi      
```

would this change be a good or a bad idea?

**Comment by mysticaltech** [comment]
@valkenburg-prevue-ch It's unwise because we need to node to be drained properly before restarting k3s on it. So by touching reboot-required, kured does all that magic for us.

**Comment by mysticaltech** [comment]
There is another possibility, maybe we can create another [system-upgrade-controller plan](https://github.com/rancher/system-upgrade-controller), just for that, and activate it via labels. And it is extremely suited for working safely with a k3s/rke2 node.

**Comment by valkenburg-prevue-ch** [comment]
Thanks for explaining, I thought so much! 

I would hope that workloads continue even if the k3s service is restarting for a few seconds. I mean, k3s is the orchestrator, but hopefully is not involved in every bit of communication of the cluster? I don't know what I'm talking about, this is just my story-telling understanding of k8s.

**Comment by valkenburg-prevue-ch** [comment]
I cannot find info about this so quickly. Surely someone with more expertise knows the way to the answer.

**Comment by mysticaltech** [comment]
Actually, the system-upgrade-controller has the possibility to execute commands, but we must double-check with their team if it's safe to just restart k3s. Also, it is very important to use it to make sure it does one node at a time, starting with control planes of course.

**Comment by mysticaltech** [comment]
We would basically force a k3s upgrade to the same version (if possible), and that would cause the system upgrade controller to do all the magic, including the draining and k3s restart for us. 

An interesting starting point could be https://docs.k3s.io/upgrades/automated and our own current mechanism to upgrade based on checking the version channel https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/templates/plans.yaml.tpl

**Comment by mysticaltech** [comment]
> https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/cf2ef6bbac78097015cd969c71882145b534df68/modules/host/main.tf#L199
> 
> The docs at https://docs.k3s.io/installation/private-registry state: "In order for the registry changes to take effect, you need to restart K3s on each node."
> 
> if we replace
> 
> ```
> touch /var/run/reboot-required
> ```
> 
> with
> 
> ```
> if systemctl status k3s > /dev/null; then 
>   systemctl restart k3s; 
> elif systemctl status k3s-agent > /dev/null; then 
>   systemctl restart k3s-agent; 
> fi      
> ```
> 
> would this change be a good or a bad idea?



> https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/cf2ef6bbac78097015cd969c71882145b534df68/modules/host/main.tf#L199
> 
> The docs at https://docs.k3s.io/installation/private-registry state: "In order for the registry changes to take effect, you need to restart K3s on each node."
> 
> if we replace
> 
> ```
> touch /var/run/reboot-required
> ```
> 
> with
> 
> ```
> if systemctl status k3s > /dev/null; then 
>   systemctl restart k3s; 
> elif systemctl status k3s-agent > /dev/null; then 
>   systemctl restart k3s-agent; 
> fi      
> ```
> 
> would this change be a good or a bad idea?

@valkenburg-prevue-ch, coming full circle here, [this](https://docs.k3s.io/upgrades/killall) shows that your proposed method is actually safe, as is. PR welcome! 🚀

![ksnip_20230127-171431](https://user-images.githubusercontent.com/518555/215136821-1701ec14-1e75-475d-a797-882f17da119e.png)

**Comment by mysticaltech** [comment]
> Thanks for explaining, I thought so much!
> 
> I would hope that workloads continue even if the k3s service is restarting for a few seconds. I mean, k3s is the orchestrator, but hopefully is not involved in every bit of communication of the cluster? I don't know what I'm talking about, this is just my story-telling understanding of k8s.



> Thanks for explaining, I thought so much!
> 
> I would hope that workloads continue even if the k3s service is restarting for a few seconds. I mean, k3s is the orchestrator, but hopefully is not involved in every bit of communication of the cluster? I don't know what I'm talking about, this is just my story-telling understanding of k8s.

You were right! That seems to be the way it actually works... I had no idea myself lol 🎯

**Comment by valkenburg-prevue-ch** [comment]
So the orchestra keeps on playing when the conductor goes to the bathroom to ...

**Comment by mysticaltech** [comment]
Exactly lol

**Comment by captnCC** [comment]
> There is another possibility, maybe we can create another [system-upgrade-controller plan](https://github.com/rancher/system-upgrade-controller), just for that, and activate it via labels. And it is extremely suited for working safely with a k3s/rke2 node without requiring a reboot.
> 
> FYI @captnCC, if we can remove the need for reboot, it would be awesome!

@mysticaltech While working on the helm transition for v2, I was already thinking about consolidating the upgrade behaviours for k3s and the system with `system-upgrade-controller` plans, to make it all a cohesive configuration

**Comment by mysticaltech** [comment]
@captnCC I understand the idea, but for the system kured does it automatically and has a whole system to do it well, it came from them, even the interaction with kured. So best left independent.

The beauty of the system upgrade controller upgrade of k3s is that it doesn't need a reboot. But for the OS, a reboot is needed to apply the new snapshot.
