### ISSUE TITLE
[Bug]: Replacing existing nodes due to changes does not work

### ISSUE THREAD

**Issue by ifeulner** [kube-hetzner/terraform-hcloud-kube-hetzner#558]
If a node needs replacement (e.g. if the image changes) a uniqueness error occurs:

```
module.kube-hetzner.module.control_planes["0-0-control-plane-fsn1"].hcloud_server.server: Creating...
module.kube-hetzner.module.agents["0-0-agent-small"].hcloud_server.server: Creating...
╷
│ Error: server name is already used (uniqueness_error)
│
│   with module.kube-hetzner.module.control_planes["0-0-control-plane-fsn1"].hcloud_server.server,
│   on ../kube-hetzner/modules/host/main.tf line 22, in resource "hcloud_server" "server":
│   22: resource "hcloud_server" "server" {
│
╵
╷
│ Error: server name is already used (uniqueness_error)
│
│   with module.kube-hetzner.module.agents["0-0-agent-small"].hcloud_server.server,
│   on ../kube-hetzner/modules/host/main.tf line 22, in resource "hcloud_server" "server":
│   22: resource "hcloud_server" "server" {
│
```

This is because of lifecycle `create_before_destroy` but the calculated server_name is the same as the old one.

**Comment by mysticaltech** [comment]
@ifeulner Did you take down the node with `terraform destroy -target` ? 

Indeed, create_before_destroy does not seem compatible. Let's just remove it.

**Comment by mysticaltech** [comment]
@ifeulner Please, let me know how you proceeded, that's an important issue, and if you see a quick fix, don't hesitate to push it, otherwise I will take care of it. Thanks 🙏

**Comment by ifeulner** [comment]
@mysticaltech the obvious quick fix is to adjust the server name based on a image change. But if that at the end really results in a still-working cluster? I doubt it... 
Anyways, I I will push the quick fix later...

**Comment by mysticaltech** [comment]
@ifeulner Yes, but what I wanted to know is, what how are you tested, is it with `terraform destroy -target` ?

It is not the first time we tried this, and in my previous testing, it was working. But it might have been before we create implemented the create_before_destroy. So the quick fix will be to remove that!

It is imperative that we are left with a fully working cluster of course!

**Comment by mysticaltech** [comment]
@ifeulner Yes, but what I wanted to know is how did you test, is it with `terraform destroy -target` ?

It is not the first time we tried this, and in my previous testing, it was working. But it might have been before we implemented the `create_before_destroy`. So the quick fix will be to remove that!

Of course, it is imperative that we are left with a fully working cluster!

**Comment by mysticaltech** [comment]
@ifeulner PR most welcome, I believe just removing create_before_destroy will work, because it is a more or less recent addition and before it worked like a charm when a node was drained, destroyed with target, and terraform re-applied.
