### ISSUE TITLE
Add to instance name info about number index in list

### ISSUE THREAD

**Issue by jidckii** [kube-hetzner/terraform-hcloud-kube-hetzner#559]
Right now the instance name is calculated like this,

modules/host/locals.tf:
```
  # the hosts name with its unique suffix attached
  name = "${var.name}-${random_string.server.id}"
```

if I want to reduce the number of nodes in the pool, I need to know the hostnames in tf state to drain the correct nodes.
I suggest adding information about the sequence number in the pool to the generated name.
For example, with 3 nodes, I would know to drain host number 3, then lower the count, and run terraform apply.

**Comment by mysticaltech** [comment]
@jidckii Doing like you are proposing would mess up the sequence when you kill a node. BUT

The sequence info is already available in the terraform state, just run `terraform state` and grep your node pool name. It should give you the correct info. If not, let me know, and we will include the randomly generate sequence in there.

**Comment by aleksasiriski** [comment]
Has this been solved?
