### ISSUE TITLE
How to upgrade existing non HA cluster

### ISSUE THREAD

**Issue by ermalguni** [kube-hetzner/terraform-hcloud-kube-hetzner#561]
I have a non HA cluster with 1 control plane node and 3 worker nodes. Would I be able to upgrade this cluster if I create 3 control plane nodes and set `automatically_upgrade_os = true` and `automatically_upgrade_k3s = true`?

**Comment by mysticaltech** [comment]
@ermalguni Yes! You can increase the control-plane node count and set these variables to `true`. Then apply. But that will not be enough. But set these variables before scaling up!

And for "old" nodes, to enable upgrades, you have to SSH into each one of them (see readme), and execute: `systemctl --now enable transactional-update.timer`.

Also for "old" nodes, to enable k3s upgrades, you need to run ` kubectl label node <node-name> k3s_upgrade=true` for each "old" node.

When you do that, each node will upgrade the OS one at a time, and also each k3s will also update to match the `initial_k3s_channel` (you can set that at any time if you want to fix it to v1.25 for instance, you can). All of this, automagically!

**Comment by aleksasiriski** [comment]
@ermalguni Has this been solved?

**Comment by ermalguni** [comment]
Sorry for the late reply. Yes, it is solved.
