### ISSUE TITLE
How to update node pool or nodes 

### ISSUE THREAD

**Issue by digitalbuddha** [kube-hetzner/terraform-hcloud-kube-hetzner#565]
Hello folks thank you for the wonderful project. It has been a lifesaver for someone like me who wasn't sure how to work with terraform or kubernetes.

I am able to successfully deploy to hetzner but was wondering how do I update? For example if I want to increase the count of the node pool or nodes, what command should I run locally?

Thank you for your help and apologies for the naive question ♥️

**Comment by aleksasiriski** [comment]
Increase the number of nodes or add new node pools to the kube.tf and then rerun `terraform apply`

**Comment by digitalbuddha** [comment]
Got it, thank you. I think my issue was more nuanced then - if I go from a single node cluster 
```control_plane_nodepools = [
    {
      name        = "control-plane",
      server_type = "cpx31",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1,
      longhorn_volume_size = 0
    }
  ]

  agent_nodepools = [
    {
      name        = "agent",
      server_type = "cpx21",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 0,
      longhorn_volume_size = 0
    }
  ]
```
Then change the agent count to 1, I get a load balancer not found error. I will try for a larger cluster, thanks!

**Comment by aleksasiriski** [comment]
Hmm, you can try at start with a larger cluster but that shouldn't affect much (in case of 1 master and 0 workers that uses the control-plane as LB instead of Hetzner, so that may be erroring out when switching to 1+ masters and 1+ workers). Feel free to reopen this and add logs.
