### ISSUE TITLE
ERROR: while calling sum(list) var.control_plane_nodepools & var.agent_nodepoolsis empty list of dynamic  (pls. check README.md "Installation" section)

### ISSUE THREAD

**Issue by adaptunit** [kube-hetzner/terraform-hcloud-kube-hetzner#566]
+ copy cloned repo to a new folder without "kube.tf.example"
+ copy "kube.tf.example" to "kube.tf"
+ edir "kube.tf" (see below)
+ using the commands from the "Installation" section according to the instructions
---

```
~$> terraform init --upgrade
```
Upgrading modules...
- agents in modules/host
- control_planes in modules/host
Downloading registry.terraform.io/kube-hetzner/kube-hetzner/hcloud 1.9.0 for kube-hetzner...
- kube-hetzner in .terraform/modules/kube-hetzner
- kube-hetzner.agents in .terraform/modules/kube-hetzner/modules/host
- kube-hetzner.control_planes in .terraform/modules/kube-hetzner/modules/host
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Duplicate output definition
│ 
│   on output.tf line 37:
│   37: output "kubeconfig" {
│ 
│ An output named "kubeconfig" was already defined at kube.tf:564,1-20. Output names must be
│ unique within a module.
╵

╷
│ Error: Duplicate required providers configuration
│ 
│   on versions.tf line 3, in terraform:
│    3:   required_providers {
│ 
│ A module may have only one required providers configuration. The required providers were
│ previously configured at kube.tf:556,3-21.

>>> LINE: kube.tf:554:
terraform {
  required_version = ">= 1.3.3"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.35.2"
    }
  }
}

>>> LINE: kube.tf:564:
output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}

---
###### Start again:
```
~$> terraform apply -auto-approve
```
var.hcloud_token
  Hetzner Cloud API Token.

  Enter a value:

var.ssh_private_key
  SSH private Key.

  Enter a value: 

var.ssh_public_key
  SSH public Key.

  Enter a value: 

module.kube-hetzner.data.github_release.hetzner_ccm[0]: Reading...
data.github_release.hetzner_csi[0]: Reading...
module.kube-hetzner.data.github_release.kured[0]: Reading...
module.kube-hetzner.data.github_release.hetzner_csi[0]: Reading...
data.github_release.kured[0]: Reading...
data.github_release.hetzner_ccm[0]: Reading...
module.kube-hetzner.data.github_release.hetzner_ccm[0]: Read complete after 1s [id=79020566]
data.github_release.hetzner_csi[0]: Read complete after 1s [id=89711362]
module.kube-hetzner.data.github_release.kured[0]: Read complete after 1s [id=86062001]
data.github_release.hetzner_ccm[0]: Read complete after 2s [id=79020566]
module.kube-hetzner.data.github_release.hetzner_csi[0]: Read complete after 2s [id=89711362]
data.github_release.kured[0]: Read complete after 2s [id=86062001]
╷
│ Error: Invalid function argument
│ 
│   on locals.tf line 90, in locals:
│   90:   control_plane_count    = sum([for v in var.control_plane_nodepools : v.count])
│     ├────────────────
│     │ while calling sum(list)
│     │ var.control_plane_nodepools is empty list of dynamic
│ 
│ Invalid value for "list" parameter: cannot sum an empty list.
╵
╷
│ Error: Invalid function argument
│ 
│   on locals.tf line 91, in locals:
│   91:   agent_count            = sum([for v in var.agent_nodepools : v.count])
│     ├────────────────
│     │ while calling sum(list)
│     │ var.agent_nodepools is empty list of dynamic
│ 
│ Invalid value for "list" parameter: cannot sum an empty list.

---

### ISSUEs:
1. "terraform apply -auto-approve" : will ask me to manually enter "Hetzner Cloud API Token" & "SSH private Key" 
2. I end up seeing an ERROR: while calling sum(list) var.control_plane_nodepools &  var.agent_nodepoolsis empty list of dynamic

--- 
##### !!! "kube.tf" parts, everything else is unchanged, from "kube.tf.example"

here for illustration random string as command result  : 
`cat /dev/urandom | tr -dc '[:alpha:]' | fold -w ${1:-64} | head -n 5`
of course in real "kube.tf" i use real API token...

```
locals {
  hcloud_token = "WbfARyGgwCAjykqNwhewaCvXKdcKyYcKDyVnWPxBeNqFWrqxQQlOwfIzlVUxXQkw"
}

ssh_public_key = file("~/.ssh/id_rsa_hcloud_ed25519_dev.pub")
ssh_private_key = file("~/.ssh/id_rsa_hcloud_ed25519_dev"
```

---
---
### QUESTION:
tell me please, 
??? what i'm doing wrong

Thanks!

**Comment by aleksasiriski** [comment]
Please don't clone the repo, you only need an empty folder with kube.tf and then run the installation commands.

**Comment by adaptunit** [comment]
pls. add magic word "...need ONLY kube.tf needs to reside in a (EMPTY) NEW " ;-)  ...in this paragraph: 

It's important to realize that your kube.tf needs to reside in a NEW folder, not a clone of this git repo (the module by default will be fetched from the Terraform registry). All you need, is to re-use the [kube.tf.example](https://raw.githubusercontent.com/kube-hetzner/terraform-hcloud-kube-hetzner/master/kube.tf.example) file to make sure you get the format right

Best regards!
