### ISSUE TITLE
Getting really slow OS download speeds

### ISSUE THREAD

**Issue by AlexProgrammerDE** [kube-hetzner/terraform-hcloud-kube-hetzner#568]
Hello! I've been trying to deploy more machines and it seems like the OS download speed is extremely slow. It takes around 20 minutes till a OS image is fully downloaded.
![image](https://user-images.githubusercontent.com/40795980/217018349-78df89f0-1dec-4830-870b-1064731d2178.png)
On a hetzner cloud VM of the same type (even the same DC), I get it downloaded in 20 seconds.
![image](https://user-images.githubusercontent.com/40795980/217018506-929f9572-b644-4f85-8708-cc1f6cf9168c.png)
Is there anything I can do to increase the download speed in the OS download phase? It's really weird that it works really fast on normal machines and on the ones I deploy it is really slow.

**Comment by mysticaltech** [comment]
@AlexProgrammerDE You can change the `opensuse_microos_mirror_link` in your kube.tf, please have a look at the explanations given in the comments.

**Comment by AlexProgrammerDE** [comment]
Both machines are in nbg1-dc3, so it shouldn't make a difference, I'll try the auto selecting mirror anyway.

**Comment by aleksasiriski** [comment]
The default mirror never has any faults but is usually slow, as you can see. other mirrors (even the official one) sometimes error out but if that doesn't happen it is MUCH faster to download.

Another option would be to try out snapshot usage which @ifeulner is currently working on, just set this in your config:

```terraform
source = github.com/kube-hetzner/terraform-hcloud-kube-hetzner/tree/packer-integration
```

**Comment by AlexProgrammerDE** [comment]
Yeah, just gave me a 403.
![image](https://user-images.githubusercontent.com/40795980/217021703-88d23d87-715f-4f58-bfa2-2130dd79d6ba.png)
I'll try searching for a mirror. I am just confused that the main mirror is fast on a VM and slow in rescue. 🤷🏻

**Comment by aleksasiriski** [comment]
> Yeah, just gave me a 403. ![image](https://user-images.githubusercontent.com/40795980/217021703-88d23d87-715f-4f58-bfa2-2130dd79d6ba.png) I'll try searching for a mirror. I am just confused that the main mirror is fast on a VM and slow in rescue. 🤷🏻

Try the Dogado one I mentioned above.

**Comment by mysticaltech** [comment]
@AlexProgrammerDE Try the one given above by @aleksasiriski.

**Comment by AlexProgrammerDE** [comment]
![image](https://user-images.githubusercontent.com/40795980/217023190-92264ae3-178a-49e9-9fa1-56d6a5e8b008.png)
Is faster I guess, thanks! Looking forward to that PR. 👍🏻

**Comment by mysticaltech** [comment]
@aleksasiriski Sounds good, go ahead if you want! 🙏
