### ISSUE TITLE
[Feature-request]: Customize IP-Range of Network

### ISSUE THREAD

**Issue by zypriafl** [kube-hetzner/terraform-hcloud-kube-hetzner#572]
Hello,

Is there a way to set the IP-Range on the network in the kube.tf before the Cluster creation? Currently its 10.0.0.0/8.

We want to add a separatly-managed VM to the Cluster network so the Pods can directly access a service installed on this VM. However, this VM is already attached to a 10.0.0.0/8 network.

Thanks for you help.

**Comment by mysticaltech** [comment]
@zypriafl I'm sorry, but at this moment we do not support that, as the IP ranges are hard coded at multiple locations and used for subnet generation.

However, propose that feature, it's probably doable, but at the moment we do not have the resources to dedicate to this.

**Comment by zypriafl** [comment]
@mysticaltech Alright, I changed this already successfully in the local source directly. If I find the time and can try to make it a variable in the kube.tf

**Comment by mysticaltech** [comment]
Good to hear, it could be very useful to others! 🙏

**Comment by aleksasiriski** [comment]
> @mysticaltech Alright, I changed this already successfully in the local source directly. If I find the time and can try to make it a variable in the kube.tf

I can do that easily now.

**Comment by vladimir-petukhov-sr** [comment]
> @mysticaltech Alright, I changed this already successfully in the local source directly. If I find the time and can try to make it a variable in the kube.tf

Hey! Maybe you can share your solution "as-is" right here, cause I'm also into this issue. It will be great, if you can!:)
