### ISSUE TITLE
[Bug]: Rancher fails to install with default channels

### ISSUE THREAD

**Issue by thomasprade** [kube-hetzner/terraform-hcloud-kube-hetzner#583]
### Description

When creating a new cluster with the config below, the rancher helm chart fails to install with the error seen below (output of kubectl describe -n kube-system pods/helm-rancher...)

Using rancher-install-channel latest and stable, both don't work.

The cluster doesn't have an agent on purpose, since for testing purposes I am fine with the klipper lb scheduling on the CPs as well.

Also adding one agent to the deploy doesn't fix the problem with the rancher install.

Downgrading the initial_k3s_channel to v1.24 and completley recreating the cluster also doesn't work and results in the same error.

With k3s channel v1.24 the helm-install-rancher-xxxxx pod outputs the following error:
```
Error: INSTALLATION FAILED: YAML parse error on rancher/templates/ingress.yaml: error converting YAML to JSON: yaml: line 18: mapping values are not allowed in this context
```

With k3s channel v1.25 the following:
```
Error: INSTALLATION FAILED: chart requires kubeVersion: < 1.25.0-0 which is incompatible with Kubernetes v1.25.6+k3s1
```

Also as Issue in [Rancher-Repo 40510](https://github.com/rancher/rancher/issues/40510)

### Kube.tf file

```terraform
control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cx21",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "control-plane-nbg1",
      server_type = "cx21",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "control-plane-hel1",
      server_type = "cx21",
      location    = "hel1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]

  agent_nodepools = [
    {
      name        = "agent-small",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 0
    }
  ]

  enable_longhorn = true  

  enable_klipper_metal_lb = "true"

  enable_rancher = true

  rancher_hostname = "rancher-testing.timecount.cloud"

  rancher_install_channel = "stable"
```

### Screenshots

```
Containers:
  helm:
    Container ID:  containerd://6c1b2ca792e27419e13318cea7b5c34d76d5346062d844cbdeeaf472db1c6719
    Image:         rancher/klipper-helm:v0.7.4-build20221121
    Image ID:      docker.io/rancher/klipper-helm@sha256:0fa01dbbb61412742bbf4fb8ebee2167ea4658796f372f01b604c9aca7c9381f
    Port:          <none>
    Host Port:     <none>
    Args:
      install
      --namespace
      cattle-system
      --repo
      https://releases.rancher.com/server-charts/stable
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   Installing helm_v3 chart

      Exit Code:    1
      Started:      Mon, 13 Feb 2023 10:07:33 +0100
      Finished:     Mon, 13 Feb 2023 10:07:34 +0100
    Ready:          False
    Restart Count:  5
    Environment:
      NAME:              rancher
      VERSION:           
      REPO:              https://releases.rancher.com/server-charts/stable
      HELM_DRIVER:       secret
      CHART_NAMESPACE:   kube-system
      CHART:             rancher
      HELM_VERSION:      
      TARGET_NAMESPACE:  cattle-system
      NO_PROXY:          .svc,.cluster.local,10.42.0.0/16,10.43.0.0/16
      FAILURE_POLICY:    reinstall
    Mounts:
      /chart from content (rw)
      /config from values (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2clhc (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
```

### Platform

Linux

**Comment by mysticaltech** [comment]
@thomasprade Are you sure you did not use a custom `rancher_values`  in your kube.tf, or mistakenly uncommented it?

**Comment by thomasprade** [comment]
@mysticaltech Those settings were all left default, i.e. commented out.

The only changes made to the kube.tf are the ones documented in the issue.

Currently my suspicion lies with the helm-controller shipped with k3s.

When inspecting the pod "helm-install-rancher-xxxxx" created by the corresponding job the log output is:
```
+ echo 'Installing helm_v3 chart'
+ helm_v3 install --namespace cattle-system --repo https://releases.rancher.com/server-charts/stable rancher rancher --values /config/values-01_HelmChart.yaml
Error: INSTALLATION FAILED: YAML parse error on rancher/templates/ingress.yaml: error converting YAML to JSON: yaml: line 18: mapping values are not allowed in this context
```

But when executing the same command, i.e.:
```
helm install --namespace cattle-system --repo https://releases.rancher.com/server-charts/stable rancher rancher --set hostname=my.domain.xyz --set replicas=3
```
from a local helm instance with the freshly created cluster, rancher is successfully installed without any problems.

**Comment by mysticaltech** [comment]
@thomasprade I suspect, something is up with /config/values-01_HelmChart.yaml or our own rancher default values in locals.tf. I will check, but don't hesitate to do so too!

**Comment by thomasprade** [comment]
@mysticaltech The `values-01_HelmChart.yaml` is mapped into the pod via a ConfigMap created by the helm chart.
This came with the default values:
```yaml
hostname: "my.domain.xyz ? my.domain.xyz : " #so two times the rancher_hostname set in kube.tf and empty, because i didn't set lb_hostname
replicas: 3
bootstrapPassword: "RandomlyGeneratedPassword"
```

My locals.tf is completley stock, since I cloned the repo freshly for testing.

Did you try to reproduce a deployment with my provided config and, if so, could reproduce the problem?

**Comment by mysticaltech** [comment]
@thomasprade That's the issue then, the value for hostname is wrong. I did not try to reproduce it, and the lb_hostname is new logic. So it's a genuine problem coming from our side.

A quick patch for now, is to use the correct values by setting `rancher_values` in your kube.tf.

Also, don't hesitate to submit a quick PR with the fix if it's obvious what when wrong at the hostname level.

**Comment by thomasprade** [comment]
@mysticaltech ah, I just edited my comment and didn't see you already replied :sweat_smile: 

Great, so the problem is found :+1:

**Comment by mysticaltech** [comment]
The fix is quick, all the inner brackets it } ? ${var.rancher_hostname} : ${ must be removed! PR is most welcome!

Yes, the problem is found, thanks for helping with that.

**Comment by thomasprade** [comment]
So resulting in:
`hostname: "${var.rancher_hostname ? var.rancher_hostname : var.lb_hostname}"` in line 458?

And thank you for the help also.

Should I still create a PR, or are you going to fix it yourself?

**Comment by mysticaltech** [comment]
Yes, exactly, that's the correct version! Please do create a PR, it's easier for me to just approve.

**Comment by mysticaltech** [comment]
@thomasprade Even better:

`${var.rancher_hostname != "" ? var.rancher_hostname : var.lb_hostname}`

**Comment by thomasprade** [comment]
I noticed when testing the fix.
I used `length(var.rancher_hostname) == 0` like with the bootstrap_password.

And I just noticed, I accidentally flipped the eval.

Anyways PR is open.
