### ISSUE TITLE
[Feature Request]: Specify Egress IP/NAT

### ISSUE THREAD

**Issue by zypriafl** [kube-hetzner/terraform-hcloud-kube-hetzner#622]
### Description

Hello,

I am looking for a way to have a predictable IP for outgoing requests made from Pods (to whitelist them in the firewall of an exernal API). This is especially an issue for us, when using Cluster Auto-Scaling, as new Nodes are continously creating and destroyed (resulting in the use of various IPs).

In general this should be able to be solved using ""egress IPs"or NAT-as-a-Service" (see https://stackoverflow.com/questions/41133755/static-outgoing-ip-in-kubernete). 

Is there a way to implement this using this project?

**Comment by mysticaltech** [comment]
@zypriafl You are lucky, we are going to merge this very feature soon! https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/611
