### ISSUE TITLE
[Bug]: When using klipper lb proxy protocol for nginx should be turned off

### ISSUE THREAD

**Issue by thecodeassassin** [kube-hetzner/terraform-hcloud-kube-hetzner#643]
### Description

When enabling klipper lb and you don't manually patch the nginx values to disable proxy protocol the services will not be reachable through ingress. Disabling proxy protocol when using klipper needs to be done automatically when klipper is enabled and nginx is used as the ingress controller.

When you manually specify the nginx_values it works but this should be done by default.

### Kube.tf file

```terraform
nginx_values = <<EOT
controller:
  watchIngressWithoutClass: "true"
  kind: "DaemonSet"
  config:
    "use-forwarded-headers": "true"
    "compute-full-forwarded-for": "true"
    "use-proxy-protocol": "false"
  service:
    annotations: {}
  EOT
```

### Platform

Mac

**Comment by mysticaltech** [comment]
Thanks for noticing that @thecodeassassin! Please do not hesitate to submit a PR, it's always appreciated.
