### ISSUE TITLE
[Bug]: unclear intention with ssh_private_key and ssh_public_key

### ISSUE THREAD

**Issue by kingphil** [kube-hetzner/terraform-hcloud-kube-hetzner#674]
### Description

`ssh_private_key` and `ssh_public_key` are listed in variables.tf. The kube.tf file, on the other hand, directly references files on the filesystem. Even when you generate a key pair with filenames as kube.tf wants them (namely ~/.ssh/id_ed25519[.pub]), when you run `terraform plan`, you are queried for this pair, as these are defined in variables.tf with no default value.

So, what is the intent here? Is the intent that there are two keypairs? That the file(...) listed in kube.tf and the one you were asked to generate and upload in `bulb [Do not skip] Creating your kube.tf file` are different?

No matter what, once you have applied the fixed I mention in #672 and #673, and even when you have two different SSH keypairs, a `terraform apply` still gives you:

```
hcloud_network_subnet.agent[1]: Creation complete after 1s [id=2677925-10.1.0.0/16]
hcloud_network_subnet.agent[3]: Creation complete after 2s [id=2677925-10.3.0.0/16]
hcloud_network_subnet.control_plane[0]: Creation complete after 2s [id=2677925-10.255.0.0/16]
hcloud_network_subnet.control_plane[2]: Creation complete after 2s [id=2677925-10.253.0.0/16]
hcloud_network_subnet.agent[2]: Creation complete after 4s [id=2677925-10.2.0.0/16]
╷
│ Error: SSH key name is already used (uniqueness_error)
│ 
│   with hcloud_ssh_key.k3s[0],
│   on main.tf line 6, in resource "hcloud_ssh_key" "k3s":
│    6: resource "hcloud_ssh_key" "k3s" {
│ 
╵
╷
│ Error: name is already used (uniqueness_error)
│ 
│   with hcloud_placement_group.control_plane[0],
│   on main.tf line 55, in resource "hcloud_placement_group" "control_plane":
│   55: resource "hcloud_placement_group" "control_plane" {
│ 
╵
╷
│ Error: name is already used (uniqueness_error)
│ 
│   with hcloud_placement_group.agent[0],
│   on main.tf line 62, in resource "hcloud_placement_group" "agent":
│   62: resource "hcloud_placement_group" "agent" {
│ 
╵
╷
│ Error: name is already used (uniqueness_error)
│ 
│   with module.kube-hetzner.hcloud_network.k3s,
│   on .terraform/modules/kube-hetzner/main.tf line 13, in resource "hcloud_network" "k3s":
│   13: resource "hcloud_network" "k3s" {
│ 
╵
╷
│ Error: name is already used (uniqueness_error)
│ 
│   with module.kube-hetzner.hcloud_firewall.k3s,
│   on .terraform/modules/kube-hetzner/main.tf line 38, in resource "hcloud_firewall" "k3s":
│   38: resource "hcloud_firewall" "k3s" {
```

When I remove the pubkey I was asked to upload in the "[do not skip]" section noted above, I get further passed this hurdle. Resources are created (in this case, 3 cp, 2 agents, the storage one, and the egress one), etc. The end result is the same, however.

```
module.kube-hetzner.module.agents["1-0-agent-large"].null_resource.registries (remote-exec): Connected!
module.kube-hetzner.module.agents["1-0-agent-large"].hcloud_server_network.server: Creation complete after 5s [id=30400260-2677954]
module.kube-hetzner.module.agents["1-0-agent-large"].null_resource.registries (remote-exec): No update required to the registries.yaml file
module.kube-hetzner.module.agents["1-0-agent-large"].null_resource.registries: Creation complete after 7s [id=7546137719110369793]
╷
│ Error: SSH key name is already used (uniqueness_error)
│ 
│   with hcloud_ssh_key.k3s[0],
│   on main.tf line 6, in resource "hcloud_ssh_key" "k3s":
│    6: resource "hcloud_ssh_key" "k3s" {
│ 
╵
╷
│ Error: name is already used (uniqueness_error)
│ 
│   with hcloud_network.k3s,
│   on main.tf line 13, in resource "hcloud_network" "k3s":
│   13: resource "hcloud_network" "k3s" {
│ 
╵
╷
│ Error: name is already used (uniqueness_error)
│ 
│   with hcloud_firewall.k3s,
│   on main.tf line 38, in resource "hcloud_firewall" "k3s":
│   38: resource "hcloud_firewall" "k3s" {
│ 
╵
╷
│ Error: name is already used (uniqueness_error)
│ 
│   with hcloud_placement_group.agent[0],
│   on main.tf line 62, in resource "hcloud_placement_group" "agent":
│   62: resource "hcloud_placement_group" "agent" {
│ 
╵
╷
│ Error: name is already used (uniqueness_error)
│ 
│   with module.kube-hetzner.hcloud_placement_group.control_plane[0],
│   on .terraform/modules/kube-hetzner/main.tf line 55, in resource "hcloud_placement_group" "control_plane":
│   55: resource "hcloud_placement_group" "control_plane" {
```

That you can get further by removing the pubkey you were asked to upload in the preliminary step is odd, but hopefully a useful clue.

### Kube.tf file

```terraform
My kube.tf is as close to stock as possible, with the exception of the fixes I needed to get past the hurdles of bug #673 and #674.

# grep -v -E '^\s*(#|$)' kube.tf
My kube.tf is as close to stock as possible, with the exception of the fixes I needed to get past the hurdles of bug #673 and #674.

# grep -v -E '^\s*(#|$)' kube.tf
locals {
  hcloud_token = "[redacted]"
}
module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
  source = "kube-hetzner/kube-hetzner/hcloud"
  ssh_public_key = file("~/.ssh/id_ed25519.pub")
  ssh_private_key = file("~/.ssh/id_ed25519")
  network_region = "eu-central" # change to `us-east` if location is ash
  control_plane_nodepools = var.control_plane_nodepools
  agent_nodepools         = var.agent_nodepools
  load_balancer_type     = "lb11"
  load_balancer_location = "fsn1"
}
provider "hcloud" {
  token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
}



### Screenshots

_No response_

### Platform

Linux

**Comment by mysticaltech** [comment]
@kingphil I see you opened and closed a bunch of issue, what was the main learnings, please do not hesitate to share so we can improve our readme. Thanks!

**Comment by kingphil** [comment]
Thank you for reaching out. All of the problems I had yesterday were caused by my missing the words "in a new folder" in this sentence:

`Prepare the module by copying `kube.tf.example` to `kube.tf` **in a new folder** which you cd into, then replace the values from steps 1 and 2.`

Meaning, long story short, if you create the kube.tf in the root directory of the repository, you can replicate the cascade of issues I saw.

To improve the README, I would recommend moving the kube.tf.example in to the examples/ folder, and then change the README to reflect that the user should cd to that directory, copy, and run from there. Similarly, consider changing the source line in kube.tf.example to be `source = "../"`. (The leftover mention of `source = "../../"` was the clue that set me straight.)

Thank you for the quick turn-around on that selinux bug today. Once I figured out the above, I was also stuck there.

I have been working with this repository today, and getting much further. I was going to eventually do a Pull Request for the above, but I didn't want to until I had gained a more complete mastery of the tools here. This is a really great package!

**Comment by kingphil** [comment]
I have been keeping a list of small improvements I have seen along the way. I intended to eventually contribute a Pull Request, but there is no reason not to list them here:
* Clarify that the API token is "Read & Write" (I have not confirmed this, but I imagine everything would explode if just "Read".)
* Clarify that the generated SSH pubkey should *not* be uploaded to the Hetzner account, otherwise you get the "uniqueness_error". The README does not say you should, but the previous step has you upload a credential just one tab over on the UI, so it was easy to assume that should be done.
* I noticed on a node's /root/.ssh/authorized_keys, the pubkey is listed twice.
* Consider removing "metal" from enable_klipper_metal_lb; it seems to imply this setting has something to do with MetalLB.

**Comment by mysticaltech** [comment]
Thanks @kingphil, good info and advice! Appreciate it very much. About the kube.tf, don't worry about that, we are working on a new bash script to get started more easily, will roll that out soon. But about the rest, yes definitely PR is welcome to clarify the info.
