### ISSUE TITLE
Feature Request: Add Support for Hetzner's New ARM Servers - CAX11, CAX21, CAX31, CAX41

### ISSUE THREAD

**Issue by urashidmalik** [kube-hetzner/terraform-hcloud-kube-hetzner#716]
### Description

Request to add new feature in kube-hetzner.  

Support for Hetzner's newly released **ARM** server lineup: **CAX11, CAX21, CAX31, and CAX41.** I believe that incorporating support for these new servers will greatly benefit the community and enhance the overall user experience.

**Comment by urashidmalik** [comment]
Looks like Hcloud just added support in terraform for ARM API
https://github.com/hetznercloud/terraform-provider-hcloud/commit/2654d819f147dbe8367089d2dcea98d1e89d5564

**Comment by mysticaltech** [comment]
@urashidmalik This is completely doable, we will address it when this bug is fixed https://github.com/hetznercloud/terraform-provider-hcloud/issues/655

**Comment by mysticaltech** [comment]
@ifeulner FYI [MicroOS](https://download.opensuse.org/ports/aarch64/tumbleweed/appliances/openSUSE-MicroOS.aarch64-OpenStack-Cloud.qcow2) and k3s both support ARM, and [RKE2 support is coming very soon](https://github.com/rancher/rke2/issues/817).

**Comment by mysticaltech** [comment]
This is really super interesting, the price savings for ressource intensive clusters will be huge, basically half the price for 16 vCPUs with 32GB of RAM.

![ksnip_20230413-035724](https://user-images.githubusercontent.com/518555/231627155-87385d37-8933-4224-beb3-9e64bf785cb2.png)

**Comment by apricote** [comment]
Moved the upstream bug to hetznercloud/terraform-provider-hcloud#656

**Comment by mysticaltech** [comment]
Thank you @apricote!

**Comment by mysticaltech** [comment]
Perfect @aleksasiriski, don't hesitate to tag me in the PR, happy to play ping pong! 🙏 

The link for MicroOS aarch64 is [here](https://download.opensuse.org/ports/aarch64/tumbleweed/appliances/openSUSE-MicroOS.aarch64-OpenStack-Cloud.qcow2).

**Comment by korewaChino** [comment]
https://github.com/hetznercloud/terraform-provider-hcloud/commit/3f20c141293e7927166544026a115d6eef828ca4 just got pushed, images should no longer be an issue

**Comment by apricote** [comment]
> images should no longer be an issue

Well, that would require a new release that includes that commit. Is this blocking you?

**Comment by mysticaltech** [comment]
@apricote All good on our end, thanks! 🙏

**Comment by mysticaltech** [comment]
Achieved in v2.1.0! Thanks again @aleksasiriski for the good work! 🚀

**Comment by urashidmalik** [comment]
Man you guys rock 🎸 
Thank you for quick turnaround 🙏  @mysticaltech @apricote @korewaChino @aleksasiriski

**Comment by valkenburg-prevue-ch** [comment]
I have to echo @urashidmalik , this is really impressively fast, all! I'm super happy with these new arm chips and cheaper RAM!
