### ISSUE TITLE
[Feature Request]: annotations for agents

### ISSUE THREAD

**Issue by pschiffe** [kube-hetzner/terraform-hcloud-kube-hetzner#718]
### Description

Currently it's possible to define labels and taints for agents, but some features (like in [longhorn best practices](https://gist.github.com/ifeulner/d311b2868f6c00e649f33a72166c2e5b)) requires annotations for agents. This is possible to do post-cluster-creation, but having everything ready in `.tf` files is more practical.
Ideally this would work for agents, autoscaler agents and control plane. (Looking at [the doc file](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/docs/terraform.md), it seems that it's not currently possible to specify labels and taints for autoscaler agents as well.)

**Comment by mysticaltech** [comment]
@pschiffe Please have a look at the k3s agent config guide, it's not currently possible to set annotations from the get go, I do not know why they did not add support for this. https://docs.k3s.io/cli/agent

However, this could be pulled off via `kubectl` provider. @kube-hetzner/core What do you think about the above, it would be useful no?

About the latter part, for tains and labels for autoscaler, yes, that could be done and is on the roadmap. Will do ASAP.

In any case, PRs are always welcome!

**Comment by HendrikLevering** [comment]
Stumbled on this thread and just wanted to mention, that @kube-hetzner/core is just normal text and not a tagging. Just wanted to mention this in case you are wondering why nobody replied.
