### ISSUE TITLE
[Feature Request]: Private API Server

### ISSUE THREAD

**Issue by hypery2k** [kube-hetzner/terraform-hcloud-kube-hetzner#725]
### Description

I currently evaluating this project for production usage and want to keep the kube api private.

So i was thinking about adding a OpenVPN server to the TF setup and make the kube api server only accessible via VPN.

Anyone else would be interested? If so I can file a PR for that.

Any thoughts about that?

**Comment by otavio** [comment]
ZeroTier or Headscale might be an option. I am using OpenVPN for bother use cases and planning to replace it.

**Comment by mysticaltech** [comment]
@hypery2k That seems like a nice feature to have. I have been chatting with GPT-4, here is what it says:

![ksnip_20230416-035457](https://user-images.githubusercontent.com/518555/232261980-9e1c19e1-bb08-4bbf-ade3-20d4efd976a6.png)

![ksnip_20230416-035523](https://user-images.githubusercontent.com/518555/232261985-3306ee05-5ebf-4a1d-9cf9-2209fc60a981.png)

Based on that, I agree with @otavio that ZeroTier or Headscale seem like slightly better options, but taking into account the licenses, it seems [Headscale](https://github.com/juanfont/headscale) is more suitable, at it uses a friendly BSD-3 license.

PR is most welcome! 🙏

**Comment by hypery2k** [comment]
okay, I will try to fill a PR with headscale next week. Seems promising and less hassle then OpenVPN :D

**Comment by otavio** [comment]
My understanding about the license allows us to use it but not make a SaaS offering that competes with ZeroTier.  

Headscale doesn't allow for multiple subnets or ephemeral builders to join (for Jenkins, for example) to access a specific cluster service. ZeroTier might be used for other things and even to create different subnets to replace existing VPNs and reuse the cluster one. Another nice ZeroTier feature is the public subnets. So ephemeral builder can join seamlessly. 

One option I should have researched more is Nebula. It mIt would be worth checking too.

**Comment by mysticaltech** [comment]
Yes, ZeroTierOne is GPL 3.0 and that would be ok in our case. So up to you @hypery2k, choose what you think is best and makes more sense to you.

**Comment by ifeulner** [comment]
ZeroTier works very well, used that in the past.
But maybe the easiest way is to use a dedicated server and adjust the firewall settings to allow access just from that server to the API - not exactly the same but a lot more secure already.

**Comment by mysticaltech** [comment]
@hypery2k @otavio @kube-hetzner/core What about supporting teleport instead? Any experience with it? https://github.com/gravitational/teleport

**Comment by mysticaltech** [comment]
FYI a user experience with it, seems awesome and simpler! https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/733#discussioncomment-5650345

**Comment by ifeulner** [comment]
> @hypery2k @otavio @kube-hetzner/core What about supporting teleport instead? Any experience with it? https://github.com/gravitational/teleport

Not exactly the same use cases... we should now which requirements / use cases we want to provide.

**Comment by mysticaltech** [comment]
Up to you @hypery2k, choose and implement what you need please.

**Comment by aleksasiriski** [comment]
I would vote for Wireguard over OpenVPN if possible. But ofcourse, choose whatever suits you and implement it. More features are always welcome.

**Comment by ifeulner** [comment]
OpenVPN should not be any option at all... Wireguard or ZeroTier, depends on requirements...

**Comment by pschiffe** [comment]
Teleport provides secure proxy to access k8s api, so it can be used as an VPN alternative:
https://goteleport.com/how-it-works/secure-kubernetes-access/

Plus it has much more features; for me it makes sense to add teleport to this project instead of an VPN. And it should support k3s natively: https://goteleport.com/integrations/k3s/

**Comment by hypery2k** [comment]
I will go with Headscale. Thanks for your input. I really like Teleport, but for the use case in small SMB area to "just" secure the Kube API server do be not available from the outside, it's to costly.

If interested I can add a PR here to make it available for others ...

**Comment by aleksasiriski** [comment]
Teleport costs? I thought it was free and FOSS

**Comment by hypery2k** [comment]
ah yes, I will try if I'm able to setup a teleport cluster ...

**Comment by aleksasiriski** [comment]
Whatever floats your boat, both options seem great! If you implement one of them, probably someone else (maybe even me) will implement the other (:

**Comment by aleksasiriski** [comment]
I'll look into implementing Teleport as well now: https://goteleport.com/docs/kubernetes-access/introduction/

Since I've read [this](https://www.reddit.com/r/kubernetes/comments/12u6u0p/firstever_attack_leveraging_kubernetes_rbac_to/) I've become a little paranoid about my cluster

**Comment by ifeulner** [comment]
> I'll look into implementing Teleport as well now: https://goteleport.com/docs/kubernetes-access/introduction/
> 
> Since I've read [this](https://www.reddit.com/r/kubernetes/comments/12u6u0p/firstever_attack_leveraging_kubernetes_rbac_to/) I've become a little paranoid about my cluster

Well, if you leave the door open (unauthenticated API server...) then such things happen. 
As said, question is what should be achieved. Therefore requirements are needed. Having a more restricted API server can be achieved in many ways, some of them do not need much work, some more.

**Comment by mysticaltech** [comment]
Closing this for now, as it's being explored further in the related PR https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/752
