### ISSUE TITLE
[Bug]: /bin/bash not available

### ISSUE THREAD

**Issue by schlichtanders** [kube-hetzner/terraform-hcloud-kube-hetzner#745]
### Description

I am running on NixOS and here /bin/bash is not set.
However the create.sh script has a shebang referring to the hard coded path /bin/bash

The recommended shebang would be 
```
#!/usr/bin/env bash
```

can this be changed?

### Kube.tf file

```terraform
I haven't reached this stage yet
```

### Platform

Linux, NixOS

**Comment by valkenburg-prevue-ch** [comment]
You mean like this? https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/commit/622ac987c0a48b7fd36e7b8a9e2239d2924391c3

**Comment by valkenburg-prevue-ch** [comment]
@schlichtanders Please let is know here or in PR https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/749 if this solves your situation.
