### ISSUE TITLE
[Feature Request]: Ask for private and public key in the create.sh script

### ISSUE THREAD

**Issue by schlichtanders** [kube-hetzner/terraform-hcloud-kube-hetzner#747]
### Description

Currently, the create.sh script plainly assumes that the private key and public key are at a specific place with a specific name. That is quite surprising for the user, as the quick-start documentation does not state this.

An option would be to name the hardcoded paths in the documentation, but even better would be to ask for the paths in the create.sh script (you can also give defaults when asking).

I think asking for it is very intuitive, because the script also asks for the HCLOUD TOKEN (step 1), but currently does not ask for the private/public keys from step 2 of the 3-step quickstart.

**Comment by Gh0stRocket** [comment]
To clarify, the "create.sh" script does not actually require the private and public keys to be configured during the quick-start process. The script initializes the kube-hetzner terraform plan and builds openSUSE images with Packer on Hetzner servers, which are temporarily rented. Therefore, the configurable SSH keys are not needed for this process. Instead temporary SSH keys are generated for the image building process, and deleted afterwards.

Once the "create.sh" script is completed, you can configure everything in your kube.tf file as described in the GitHub readme [init section](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner#-do-not-skip-creating-your-kubetf-file-and-the-opensuse-microos-snapshot) sub section 4 and [installation section](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner#-installation).
