### ISSUE TITLE
[Bug]: Autoscaler Node group immediately starts the first node, even though min_nodes = 0

### ISSUE THREAD

**Issue by schlichtanders** [kube-hetzner/terraform-hcloud-kube-hetzner#756]
### Description

I would like to have a simple autoscaler group setup, so that my agents node can grow.

For kube-hetzner to correctly setup a hetzner load balancer it seems that I really need to start things with at least one node in `agent_nodepools`, hence I would like to have the autoscaling group to only get active in case this `agent_nodepool` is somehow full.

But it seems things are working differently. Despite having set `min_nodes = 0`, a first node of the autoscaling group gets started immediately after the `terraform apply -auto-approve` completes. I.e. on the agent_nodepool there is definitely enough cpu and space so that autoscaling does not need to trigger.

### Kube.tf file

```terraform
locals {
  hcloud_token = "xxxxxxxxxxx"
}

module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
  source = "kube-hetzner/kube-hetzner/hcloud"
  ssh_public_key = file("~/.ssh/hetzner_id_ed25519.pub")
  ssh_private_key = file("~/.ssh/hetzner_id_ed25519")
  network_region = "eu-central" # change to `us-east` if location is ash

  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cax11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },
  ]

  agent_nodepools = [
    {
      name        = "agent-arm-largest",
      server_type = "cax41",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1,
    }
  ]
  enable_wireguard = true

  load_balancer_type     = "lb11"
  load_balancer_location = "fsn1"

  base_domain = "cloud.jolin.io"

  autoscaler_nodepools = [
    {
      name        = "autoscaled-arm-largest"
      server_type = "cax41"
      location    = "fsn1"
      min_nodes   = o  # somehow one is also deployed if min_nodes is set to 0
      max_nodes   = 4
    }
  ]
  etcd_s3_backup = {
    etcd-s3-endpoint        = "https://gateway.storjshare.io"
    etcd-s3-access-key      = var.etcd_s3_access_key
    etcd-s3-secret-key      = var.etcd_s3_secret_key
    etcd-s3-bucket          = "jolincloud-k3s-etcd-backup"
  }
  automatically_upgrade_os = false
  cluster_name = "jolin"
  use_control_plane_lb = false
  lb_hostname = "cloud.jolin.io"

}

provider "hcloud" {
  token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
}

terraform {
  required_version = ">= 1.3.3"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.38.2"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}

variable "hcloud_token" {
  sensitive = true
  default   = ""
}

variable "etcd_s3_access_key" {
  sensitive = true
  default   = ""
}

variable "etcd_s3_secret_key" {
  sensitive = true
  default   = ""
}
```

### Platform

Linux

**Comment by ifeulner** [comment]
This is a cluster-autoscaler behavior that happens especially during the init phase of the cluster, I see this also in some of my test setups. But it scales down after some time (10 minutes I think is the standard time) if no additional load comes up.

As our script just writes the autoscaler-configuration, this is nothing we can change.

**Comment by schlichtanders** [comment]
that is good to know, of I haven't waited that long. Probably it is the same for me, I will keep an eye on it.

On the other hand, I would be happy to start the autoscaler right away with `min_nodes = 1`, however then I also like to make the `agent_nodepools` empty, however this won't start a proper hetzner load balancer

might there be a way to improve this behaviour, so that the cluster starts with hetzner load balancer if the autoscaler group has  `min_nodes >= 1`?

**Comment by mysticaltech** [comment]
> that is good to know, I haven't waited that long yet. Probably it is the same for me, I will keep an eye on it.
> 
> On the other hand, I would be happy to start the autoscaler right away with `min_nodes = 1`, however then I also like to make the `agent_nodepools` empty, however this won't start a proper hetzner load balancer
> 
> might there be a way to improve this behaviour, so that the cluster starts with hetzner load balancer if the autoscaler group has `min_nodes >= 1`?

@schlichtanders When the total main node count is 1 (for 1 control plane node), we do not use hcloud load-balancer instead use klipper-lb as it makes more sense. 

So currently you would have access to autoscaling nodes with proper Hetzner LB if you have at least 2 control planes. Otherwise please do not hesitate to submit a PR modifying the behavior of `var.enable_klipper_metal_lb`, especially around:

https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/488e107b599d538a732b8d7134b85197c967de38/locals.tf#L99
