### ISSUE TITLE
[Feature Request]: Add branch protection rules for master (main)

### ISSUE THREAD

**Issue by aleksasiriski** [kube-hetzner/terraform-hcloud-kube-hetzner#776]
### Description

1. Require a pull request before merging 
1. Require approvals (1)
1. Dismiss stale pull request approvals when new commits are pushed 
1. Require status checks to pass before merging 
1. Require branches to be up to date before merging
1. Require conversation resolution before merging

**Comment by mysticaltech** [comment]
@aleksasiriski Good practice indeed! Will do the changes ASAP.

**Comment by aleksasiriski** [comment]
Also maybe look into switching to "main" instead of "master", but that's really just cosmetic

**Comment by mysticaltech** [comment]
@aleksasiriski About that last point, I'm just used to "master", and don't really understand why some folks in tech (mainly woke folks from Silicon Valley maybe) made such a big deal out of naming git branch, due to associating the name with slavery. Just a bit too far-fetched IMHO lol.

**Comment by aleksasiriski** [comment]
> @aleksasiriski About that last point, I'm just used to "master", and don't really understand why some folks in tech (mainly woke folks from Silicon Valley maybe) made such a big deal out of naming git branches, due to associating the name with slavery. Just a bit too far-fetched IMHO lol.

Fair enough, I'm okay with both but started using git (and Github) about a year ago and got used to `main`. After you add those branch protection rules (since I don't have the perms) this can be closed.

**Comment by mysticaltech** [comment]
@aleksasiriski No worries, eventually we can move to "main" if more team members are used to that, I can adapt. 

Between, just gave you and @ifeulner admin rights to the repo, please try to do the changes if you want, hopefully it will let you. Otherwise let me know and will do ASAP.

**Comment by aleksasiriski** [comment]
I've added the branch protection rules mentioned above, in summary this is now needed to merge to master:

Commits on another branch or fork MUST pass the Terraform Validate action and only after someone else approves the PR it can be merged to master, also the PR must use the latest version of that branch and all of the conversations to be concluded.
