### ISSUE TITLE
k3s service file missing

### ISSUE THREAD

**Issue by wejdross** [kube-hetzner/terraform-hcloud-kube-hetzner#790]
### Description

I receive error during terraform run:
```
module.kube-hetzner.null_resource.first_control_plane (remote-exec): Unit k3s.service could not be found.
module.kube-hetzner.null_resource.first_control_plane (remote-exec): Failed to start k3s.service: Unit k3s.service not found.
(...)
╷
│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.null_resource.first_control_plane,
│   on .terraform/modules/kube-hetzner/init.tf line 49, in resource "null_resource" "first_control_plane":
│   49:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_823370768.sh": Process exited with status 124
```

I have recreated Snapshots to have them all fresh, but issue looks like persistent for me

### Kube.tf file

```terraform
locals {

  hcloud_token = ""
}

module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token

  source = "kube-hetzner/kube-hetzner/hcloud"

  ssh_public_key = file("~/.ssh/id_ed25519.pub")
  ssh_private_key = file("~/.ssh/id_ed25519")

  control_plane_nodepools = [
    {
      name        = "control-plane-hel1",
      server_type = "cpx11",
      location    = "hel1",
      labels      = [],
      taints      = [],
      count       = 1

    },
    {
      name        = "control-plane-hel2",
      server_type = "cpx11",
      location    = "hel1",
      labels      = [],
      taints      = [],
      count       = 1

    },
    {
      name        = "control-plane-hel3",
      server_type = "cpx11",
      location    = "hel1",
      labels      = [],
      taints      = [],
      count       = 1

    }
  ]

  agent_nodepools = [
    {
      name        = "agent1",
      server_type = "cpx21",
      location    = "hel1",
      labels      = [],
      taints      = [],
      count       = 3

    },

      

    {
      name        = "egress",
      server_type = "cpx11",
      location    = "hel1",
      labels = [
        "node.kubernetes.io/role=egress"
      ],
      taints = [
        "node.kubernetes.io/role=egress:NoSchedule"
      ],
      floating_ip = true
      count = 1
    },
  ]
  enable_wireguard = false
  load_balancer_type     = "lb11"
  load_balancer_location = "hel1"
  base_domain = "k8s.veidly.com"
  ingress_controller = "nginx"
  dns_servers = ["hydrogen.ns.hetzner.com", "helium.ns.hetzner.de", "oxygen.ns.hetzner.com"]
}

provider "hcloud" {
  token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
}

terraform {
  required_version = ">= 1.3.3"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.38.2"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}

variable "hcloud_token" {
  sensitive = true
  default   = ""
}
```

### Platform

Mac

**Comment by mysticaltech** [comment]
@wejdross Make sure to run `terraform init -upgrade`, and follow the upgrade steps laid out in the readme and the announcement discussion.

**Comment by mysticaltech** [comment]
@wejdross Any updates on this, were you able to make it work? Another think I can think of is make sure you are on a linux command line, so if you are on windows, you need to use WSL2.

**Comment by wejdross** [comment]
Hello,

i'm gonna try to fix it during weekend, I might need to clean up better or something. 
I'll for sure keep You updated, please keep the issue until monday night CEST
Best regards, Łukasz

**Comment by wejdross** [comment]
I can reproduce issue each time and I found a root bug:
- setting custom DNS breaks stuff :)

**Comment by mysticaltech** [comment]
@wejdross Glad you found the root problem. Just move to IPs, it shoudl work. Probably you know, but just in case you can grab the IPs with "dig a ....".

**Comment by mysticaltech** [comment]
If that doesn't fix the root issue, just follow the debug steps I laid out above, SSH to the server... etc.

**Comment by mysticaltech** [comment]
Ah.... If dns is broken, k3s cannot install, that's why the service is not found. Replace your custom dns with IPs and you really should be good to go. Good luck!

**Comment by wejdross** [comment]
setting IP addresses is also broken, the problem is that I can't find service file at all on server (when I ssh), it has /etc/rancher config files, but service file is missing (find+ grep in both /etc and /usr dirs), also there is zero journal entries about issue

**Comment by mysticaltech** [comment]
@wejdross By setting IP addresses, I actually mean:

1. Destroy fully (see readme on destroy section)
2. In your kube.tf, change old dns servers config to `dns_servers = ["213.133.100.98", "193.47.99.5", "88.198.229.192"]`
3. Run terraform init -upgrade
4. Then terraform apply again

No way it doesn't work, I do not see how, unless you are not on a proper Unix command line.

**Comment by wejdross** [comment]
It doesn't work as well for me
/etc/resolv.conf has correct addresses (templating works), but it looks like Hetzner DNS doesn't like me:
```
k3s-control-plane-hel1-lzu:~ # nslookup google.com
;; Got recursion not available from 213.133.100.98, trying next server
;; Got recursion not available from 193.47.99.5, trying next server
Server:         88.198.229.192
Address:        88.198.229.192#53

** server can't find google.com: REFUSED
```

Worth mentioning is:
- setting different 3 dns servers - everything works
- setting 2 of 3 dns servers - it doesn't work again
- working with default ones  set by maintainers - everything works


I think we can close it here, nothing to add more from my side

**Comment by mysticaltech** [comment]
Ok, thanks for info @wejdross!

**Comment by mysticaltech** [comment]
@wejdross Just FYI (for others too), the correct Hetzner DNS servers are 185.12.64.1 and 185.12.64.2 according to https://docs.hetzner.com/cloud/servers/static-configuration/.
