### ISSUE TITLE
[Bug]: Autoscaler not able to scale up with Cilium?

### ISSUE THREAD

**Issue by zypriafl** [kube-hetzner/terraform-hcloud-kube-hetzner#814]
### Description

The cluster autoscaler is not able to create no new nodes.

I assume its related to "AcceptableRanges have not been populated yet. Skip checking"                                                                                               

Full autoscaler logs:

│ I0522 09:04:11.339007       1 main.go:474] Cluster Autoscaler 1.26.2                                                                                                                                            │
│ I0522 09:04:11.346487       1 leaderelection.go:248] attempting to acquire leader lease kube-system/cluster-autoscaler...                                                                                       │
│ I0522 09:04:28.736992       1 leaderelection.go:258] successfully acquired lease kube-system/cluster-autoscaler                                                                                                 │
│ I0522 09:04:29.545156       1 cloud_provider_builder.go:29] Building hetzner cloud provider.                                                                                                                    │
│ W0522 09:04:29.885913       1 hetzner_servers_cache.go:94] Fetching servers from Hetzner API                                                                                                                    │
│ I0522 09:04:30.673394       1 main.go:351] Registered cleanup signal handler                                                                                                                                    │
│ I0522 09:04:30.673450       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache                                                                                                 │
│ I0522 09:04:30.673473       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 16.902µs                                                                          │
│ I0522 09:04:40.674237       1 hetzner_node_group.go:438] Set node group app-scaler-auto-scaler size from 0 to 0, expected delta 0                                                                               │
│ I0522 09:04:40.674261       1 hetzner_node_group.go:438] Set node group draining-node-pool size from 0 to 0, expected delta 0                                                                                   │
│ W0522 09:04:40.674455       1 hetzner_server_type_cache.go:93] Fetching server types from Hetzner API                                                                                                           │
│ W0522 09:04:40.733547       1 clusterstate.go:428] AcceptableRanges have not been populated yet. Skip checking                                                                                                  │
│ W0522 09:04:40.733563       1 clusterstate.go:428] AcceptableRanges have not been populated yet. Skip checking   

### Kube.tf file

```terraform
locals {
  # First and foremost set your Hetzner API token here. It can be found in your Project > Security > API Token (Read & Write is required).  
  hcloud_token = ".........."
  cluster_ipv4_cidr = "172.17.0.0/24"
}

module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  version = "v2.1.6"
  hcloud_token = local.hcloud_token
  source = "kube-hetzner/kube-hetzner/hcloud"
  ssh_public_key = file("/home/.../.ssh/web_app_scaler.pub")
  ssh_private_key = file("/home/.../.ssh/web_app_scaler")
  network_region = "eu-central"
  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]
  agent_nodepools = [
    {
      name        = "agent-middle",
      server_type = "cx31",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 0
    },
    {
      name        = "agent-large",
      server_type = "cx51",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },    
    {
      name        = "egress",
      server_type = "cpx11",
      location    = "fsn1",
      labels = [
        "node.kubernetes.io/role=egress"
      ],
      taints = [
        "node.kubernetes.io/role=egress:NoSchedule"
      ],
      floating_ip = true
      count = 1
      },    
  ]
  extra_firewall_rules = [
    {
      description     = "For outgoing."
      direction       = "out"
      protocol        = "tcp"
      port            = "any"
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    }
  ]
  network_ipv4_cidr = "172.16.0.0/16"
  cluster_ipv4_cidr = "172.17.0.0/24"
  load_balancer_type     = "lb11"
  load_balancer_location = "fsn1"
  base_domain = "app.......com"
  disable_hetzner_csi = true
  automatically_upgrade_k3s = false
  automatically_upgrade_os = false
  ingress_controller = "none"
  cni_plugin = "cilium"
  enable_cert_manager= "true"
  cluster_name = "app-scaler"
  allow_scheduling_on_control_plane = false
  lb_hostname = "app........com"
  autoscaler_nodepools = [
    {
      name        = "auto-scaler"
      server_type = "cx41"
      location    = "fsn1"
      min_nodes   = 1
      max_nodes   = 5
    }
  ]
  cilium_values = <<EOT
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - ${local.cluster_ipv4_cidr}
kubeProxyReplacement: strict
l7Proxy: "false"
bpf:
  masquerade: "true"
egressGateway:
  enabled: "true" 
  EOT
}

provider "hcloud" {
  token = local.hcloud_token
}

terraform {
  required_version = ">= 1.3.3"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.38.2"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}
```

### Platform

Linux

**Comment by mysticaltech** [comment]
@zypriafl Check the control planes logs at the kubernetes level. Honestly I have no idea what could be causing this. We never saw it before. @kube-hetzner/core Any ideas?

**Comment by zypriafl** [comment]
@mysticaltech In this setup I used Cilium (Egress Gateway) for the first time. Are there any known issues with autoscaling and using Cilium?

**Comment by mysticaltech** [comment]
@zypriafl It could be, as Cilium is not super well tested. Any assitance with this would be very much appreciated!

**Comment by mysticaltech** [comment]
@zypriafl Just so we are sure that this is cilium related, could you please comment the cni line in kube.tf and try again? And also do give cilium a shot again, cause sometimes Hetzner has little issues on their API side.

**Comment by zypriafl** [comment]
@mysticaltech Thanks for the reply, two questions:
- I tried to use Cilium because of the Egress-Gateway feature, do you know a way to implement this without Cilium?
- Can I change to Cilium on and existing Cluster. In this case would try to create the Cluster with Cilium (to get autoscaling working) then activate Cilium in a second step?

**Comment by mysticaltech** [comment]
@zypriafl You could do that but it wouldn't be practical IMHO. Please see the debug section in the readme on how to debug. Basically you need to understand what is happening and why! Also it could very well be that the Cilium values need tweaking, maybe use the default ones first which are more tested (and only include the settings absolutely necessary for egress).

**Comment by markthebault** [comment]
I have the same problem here, anyone find a way to fix it? I tried `hostNetwork: true` in the autoscaler but that does not change anything

**Comment by mysticaltech** [comment]
@markthebault If you could help us debug this it would be amazing. If you want to, please see the debug section in the readme, on how to SSH into the nodes and see the k3s logs. Thanks!

**Comment by zypriafl** [comment]
For me this works now as expected on a fresh cluster and using the latest release :
 ```
  cilium_values = <<EOT
ipam:
  operator:
    mode: kubernetes
kubeProxyReplacement: strict
l7Proxy: "false"
bpf:
  masquerade: "true"
egressGateway:
  enabled: "true" 
  EOT
  ```

**Comment by mysticaltech** [comment]
Very good to hear, thanks for sharing @zypriafl ! 

@markthebault FYI.

**Comment by nupplaphil** [comment]
> For me this works now as expected on a fresh cluster and using the latest release :
> 
> ```
>  cilium_values = <<EOT
> ipam:
>  operator:
>    mode: kubernetes
> kubeProxyReplacement: strict
> l7Proxy: "false"
> bpf:
>  masquerade: "true"
> egressGateway:
>  enabled: "true" 
>  EOT
> ```

I believe there's a typo in the config, shouldn't `mode: kubernetes` be set directly under `ipam`, should it?

Like:
```
 cilium_values = <<EOT
ipam:
 mode: kubernetes
kubeProxyReplacement: strict
l7Proxy: "false"
bpf:
 masquerade: "true"
egressGateway:
 enabled: "true" 
 EOT
```

So maybe your cluster isn't using the kuberenetes mode

**Comment by mysticaltech** [comment]
Yes @nupplaphil, you're right!
