### ISSUE TITLE
[Feature Request]: Adding Services in Load Balancer created for nginx-ingress-controller via Terraform

### ISSUE THREAD

**Issue by prabhatnagpal** [kube-hetzner/terraform-hcloud-kube-hetzner#818]
### Description

I came across a requirement to add ingress rule for my website in Kubernetes Cluster, but I couldn't find any parameter in kube.tf file to add a new service for port 8080.

For Example, when we create the Kubernetes Cluster with kube-hetzner terraform after enabling nginx ingress controller, there is a load balancer created with 2 services, one for port 80 and other for port 443.
Now, I created an Ingress resource in my namespace where the microservices are deployed and I want to connect to my backend microservice which is running on port 8080 and the path prefix I give is "/".
Now, I have to manually add the service for port 8080 binding to my nodePort for the backend service, in LoadBalancer from Hetzner Cloud Console.

Feature is required for doing this with kube-hetzner terraform itself.

**Comment by mysticaltech** [comment]
@prabhatnagpal We already have a similar feature, see the "adding extras" section in the readme https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/README.md#adding-extras

**Comment by prabhatnagpal** [comment]
@mysticaltech Will the kustomization.yaml.tpl help me to configure this?:-
![image](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/assets/16299546/53d3a8e5-9085-49bb-9a7d-5024201c5acc)

**Comment by mysticaltech** [comment]
@prabhatnagpal Ah I understand. Basically, we do not need to touch Hetzner services, they are setup automatically by the ingress controller. What you may need to do is create a helmchartconfig for traefik and add the services you want, and probably the same for nginx. Please search this project for helmchartconfig for examples.

**Comment by mysticaltech** [comment]
Also take a look at `traefik_values` and `nginx_values` in kube.tf. Your custom services can be setup there too, no need for helmchartconfigs, and it works even after cluster deploy.

**Comment by prabhatnagpal** [comment]
Thanks @mysticaltech , will look into it 👍

**Comment by mysticaltech** [comment]
@prabhatnagpal In the case of Traefik, "services" are called EntryPoints, see https://doc.traefik.io/traefik/routing/entrypoints/.

**Comment by prabhatnagpal** [comment]
@mysticaltech I looked at the advanced section but that is for tweaking the ingress controller values which resides in nginx namespace. I'll define where I am stuck:-

Namespace: testing
Deployment: java based listens on port 8080
Service: Type: NodePort, nodeport: 31080, targetport: 8080
Ingress: path /, backend: service_name, port: 8080, host: subdomain.example.com

After this part, I have to open HetznerCloud Console to allow port 8080 to connect to nodeport 31080 on loadbalancer by adding a service which is different from nginx controller and its values.
The Custom Service you are saying to add by editing nginx_ingress_values in kube.tf would result in customizing the resources in nginx namespace and I want the loadbalancer rule 8080 -> 31080 to be added for microservice running in testing namespace, which is just using nginx as ingressClass.

**Comment by mysticaltech** [comment]
@prabhatnagpal Very good to hear, well done!! 🥳
