### ISSUE TITLE
[Bug]: longhorn_volume_size not working in control_plane_nodepools

### ISSUE THREAD

**Issue by RelativeSure** [kube-hetzner/terraform-hcloud-kube-hetzner#845]
### Description

I have set longhorn_volume_size in control_plane_nodepools and it doesn't create a volume in hcloud. When I use it in agent_nodepools it works just fine.

### Kube.tf file

```terraform
locals {
  hcloud_token = "xxxxxxxxxxx"
}

module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token

  source = "github.com/kube-hetzner/terraform-hcloud-kube-hetzner"

  ssh_public_key = file("~/.ssh/id_ed25519.pub")
  ssh_private_key = file("~/.ssh/id_ed25519")

  network_region = "eu-central" 

  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cpx31",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
      longhorn_volume_size = 50
    }    
  ]

  agent_nodepools = [
    {
      name        = "agent-large",
      server_type = "cpx31",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 0
      longhorn_volume_size = 50
    },
  ]
  load_balancer_type     = "lb11"
  load_balancer_location = "fsn1"

  base_domain = "<domain>"

  enable_longhorn = true

  enable_klipper_metal_lb = "true"

  automatically_upgrade_os = false

  kured_options = {
    "reboot-days": "su"
    "start-time": "3am"
    "end-time": "8am"
    "time-zone": "Local"
  }

  initial_k3s_channel = "stable"

  enable_cert_manager = true


  additional_tls_sans = ["<domain>"]

  lb_hostname = "lb.<domain>"

}
```

### Platform

Linux

**Comment by mysticaltech** [comment]
@RelativeSure This is by design, your control plane should not be involved in any computational activity appart from managing the cluster. Now the only thing we allow is scheduling, it you turn the flag on in your kube.tf, but it's not recommended either by kubernetes best practices.

**Comment by mysticaltech** [comment]
So if you have 3 control plane nodes, let's say small ones like cpx11, you barely have enough space for the OS (MicroOS uses snapshots), so it wouldn't be wise either way.

**Comment by RelativeSure** [comment]
Okay thanks. I am just confused in how I need to setup a single node cluster.

**Comment by RelativeSure** [comment]
@mysticaltech Is it possible to add to the documentation on how to setup a single node cluster? Will definitely help new people to k8s like me.

**Comment by mysticaltech** [comment]
Ah I see, nothing specially needed, only use 1 control plane, but you cannot use longhorn with it, it wouldn't make sense anyways. You will have Hetzner CSI for volumes, which is the default and works well too. Longhorn is more interesting for large clusters with lots of data.
