### ISSUE TITLE
[Bug]: Floating IP not persistent

### ISSUE THREAD

**Issue by sebastianlutter** [kube-hetzner/terraform-hcloud-kube-hetzner#869]
### Description

The floating_ip feature added with https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/611 does not persist the IP configuration on the servers `eth0` interface. 

* set `floating_ip=true` on some agent node(s)
* start the cluster, wait until finished
* ssh into the server, test floating ip is configured
```
$ ssh root@159.69.115.1
k3s-agent-small-vlr:~ # ip a s eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 96:00:02:54:1c:d5 brd ff:ff:ff:ff:ff:ff
    altname enp1s0
    inet 116.202.2.72/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet 159.69.115.1/32 scope global dynamic eth0
       valid_lft 86162sec preferred_lft 86162sec
    inet6 2a01:4f8:1c17:7c97::1/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::9400:2ff:fe54:1cd5/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```
* reboot the server, ssh into the server when up again, check interface again
```
k3s-agent-small-vlr:~ # reboot

$ ssh root@159.69.115.1

k3s-agent-small-vlr:~ # ip a s eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 96:00:02:54:1c:d5 brd ff:ff:ff:ff:ff:ff
    altname enp1s0
    inet 159.69.115.1/32 scope global dynamic noprefixroute eth0
       valid_lft 86352sec preferred_lft 86352sec
    inet6 2a01:4f8:1c17:7c97::1/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::9400:2ff:fe54:1cd5/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

The server node can no longer be reached via the floating_ip since the eth0 device has no working persistent config. 

The config files from the PR code are in place but have no effect:
```
k3s-agent-small-vlr:~ # cat /etc/sysconfig/network/ifcfg-eth0 
BOOTPROTO='static'
STARTMODE='auto'
IPADDR=116.202.2.72/32
IPADDR_1=159.69.115.1/32

k3s-agent-small-vlr:~ # cat /etc/sysconfig/network/ifroute-eth0 
172.31.1.1 - 255.255.255.255 eth0
default 172.31.1.1 - eth0 src 116.202.2.72
```

But since Suse has been replaced `wickedd` by NetworkManager this does not work. The following NetworkManager config created by cloud-init is managing the device:
```
k3s-agent-small-vlr:~ # cat /etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection 
# Generated by cloud-init. Changes will be lost.

[connection]
id=cloud-init eth0
uuid=1dd9a779-d327-56e1-8454-c65e2556c12c
type=ethernet

[user]
org.freedesktop.NetworkManager.origin=cloud-init

[ethernet]
mac-address=96:00:02:54:1C:D5

[ipv4]
method=auto
may-fail=false

[ipv6]
method=manual
may-fail=false
address1=2a01:4f8:1c17:7c97::1/64
gateway=fe80::1
dns=2a01:4ff:ff00::add:1;2a01:4ff:ff00::add:2;
```

A possible solution is to use NetworkManager dispatcher scripts (/etc/NetworkManager/dispatcher.d/90-add-floating-ip.sh):
```
#!/bin/bash
if [ "$1" == "eth0" -a "$2" == "up" ]; then
  ip addr add 116.202.2.72 dev eth0
fi
```
(see discussion https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/866)

But I'm not sure if this will work well with the cilium egress feature (the dispatcher scripts adds the IP as second IP and does not set a explicit route)

### Kube.tf file

```terraform
locals {
  hcloud_token = "xxxxxxxxxxx"
}
module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
  source = "kube-hetzner/kube-hetzner/hcloud"
  ssh_public_key = file("id_ed25519.pub")
  ssh_private_key = file("id_ed25519")
  control_plane_nodepools = [
    {
      name        = "control-plane-hel1",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]
  agent_nodepools = [
    {
      name        = "agent-small",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
      floating_ip = true
      #floating_ip_id = "568730"
    }
  ]
  load_balancer_type     = "lb11"
  load_balancer_location = "fsn1"
}

provider "hcloud" {
  token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
}
terraform {
  required_version = ">= 1.4.0"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.41.0"
    }
  }
}
output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}
variable "hcloud_token" {
  sensitive = true
  default   = ""
}
```

### Platform

Linux (Ubuntu 22.04)

**Comment by mysticaltech** [comment]
@sebastianlutter Amazing debug! Please PR welcome, it would help a lot 🙏

**Comment by sebastianlutter** [comment]
> @sebastianlutter Amazing debug! Please PR welcome, it would help a lot pray

There is one thing I'm unsure about. @JurgenTreeum added the following comment:
```
[ . . . ]
# its important: floating IP should be first on the interface IP list, move main IP to the second position
ip addr del {NODE_PRIMARY_IP}/32 dev eth0
ip addr add {NODE_PRIMARY_IP}/32 dev eth0
```
My approach sets the floating IP as second IP, while he explicitly set it as first and moved the other IP to the second spot. I do not understand why, but I guess this is egress specific. Would be great if @JurgenTreeum or someone familiar with the egress functionality could comment on this. I don't want to break the egress functionality.

If the order of IPs and the routing is needed like described in `/etc/sysconfig/network/ifcfg-eth0` and `/etc/sysconfig/network/ifroute-eth0` then the dispatcher script needs to be improved. I can work on this, but someone needs to explain to me what the egress feature needs (and how to test/debug the egress feature)

**Comment by sshcherbinin** [comment]
@sebastianlutter see solution (wicked => NetworkManager) https://github.com/treeumcorp/terraform-hcloud-kube-hetzner/commit/294a88656047092320cd486ce878b2a193ff0f23

P.S. floating ip in the 1th position needs for egress routing through the floating ip (when the connection is from the server side)

**Comment by sebastianlutter** [comment]
@sshcherbinin Obviously the better way to use nmcli. Thanks for letting me know

I plan to add support for existing floating IPs, see https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/857#discussioncomment-6291894

Hope your solution is merged into upstream soon, then I'll build on top of your commit

**Comment by mysticaltech** [comment]
@kube-hetzner/core Any thoughts on this?

**Comment by mysticaltech** [comment]
@sshcherbinin PR welcome, and with explanations would be wonderful! 🙏
