### ISSUE TITLE
[Bug]: Cluster CIDR is not honored by K3s/Cilium

### ISSUE THREAD

**Issue by zypriafl** [kube-hetzner/terraform-hcloud-kube-hetzner#906]
### Description

Our cluster is assigning Pod CIDRs for the range [10.42.0.0/16](http://10.42.0.0/16), but the HCCM configuration sets this to "--cluster-cidr=[172.17.0.0/24](http://172.17.0.0/24)". 

Logs from HCCM:
Flag --allow-untagged-cloud has been deprecated, This flag is deprecated and will be removed in a future release. A cluster-id will be required on cloud instances.
I0724 13:59:16.207436       1 serving.go:348] Generated self-signed cert in-memory
I0724 13:59:16.574446       1 serving.go:348] Generated self-signed cert in-memory
W0724 13:59:16.574556       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0724 13:59:16.941798       1 metrics.go:41] Starting metrics server at :8233
I0724 13:59:18.033375       1 cloud.go:146] Hetzner Cloud k8s cloud controller v1.17.1 started
W0724 13:59:18.033401       1 main.go:74] detected a cluster without a ClusterID.  A ClusterID will be required in the future.  Please tag your cluster to avoid any future issues
I0724 13:59:18.033423       1 controllermanager.go:167] Version: v0.0.0-master+$Format:%H$
I0724 13:59:18.037551       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0724 13:59:18.037665       1 shared_informer.go:311] Waiting for caches to sync for RequestHeaderAuthRequestController
I0724 13:59:18.037780       1 configmap_cafile_content.go:202] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::client-ca-file"
I0724 13:59:18.037864       1 shared_informer.go:311] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0724 13:59:18.037947       1 configmap_cafile_content.go:202] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
I0724 13:59:18.038018       1 shared_informer.go:311] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0724 13:59:18.038772       1 secure_serving.go:210] Serving securely on [::]:10258
I0724 13:59:18.039379       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0724 13:59:18.138828       1 shared_informer.go:318] Caches are synced for RequestHeaderAuthRequestController
I0724 13:59:18.138828       1 shared_informer.go:318] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0724 13:59:18.138907       1 shared_informer.go:318] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0724 13:59:18.352748       1 controllermanager.go:336] Started "cloud-node"
I0724 13:59:18.352806       1 node_controller.go:161] Sending events to api server.
I0724 13:59:18.352851       1 node_controller.go:170] Waiting for informer caches to sync
I0724 13:59:18.353035       1 controllermanager.go:336] Started "cloud-node-lifecycle"
I0724 13:59:18.353132       1 node_lifecycle_controller.go:113] Sending events to api server
I0724 13:59:18.353285       1 controllermanager.go:336] Started "service"
I0724 13:59:18.353432       1 controller.go:229] Starting service controller
I0724 13:59:18.353450       1 shared_informer.go:311] Waiting for caches to sync for service
I0724 13:59:18.460803       1 controllermanager.go:336] Started "route"
I0724 13:59:18.461003       1 route_controller.go:104] Starting route controller
I0724 13:59:18.461086       1 shared_informer.go:311] Waiting for caches to sync for route
I0724 13:59:18.553530       1 shared_informer.go:318] Caches are synced for service
I0724 13:59:18.553860       1 load_balancers.go:109] "ensure Load Balancer" op="hcloud/loadBalancers.EnsureLoadBalancer" service="traefik" nodes=["app-scaler-auto-scaler-136f9ac7070f0914","app-scaler-auto-scaler-2402a18da250bf34","app-scaler-auto-scaler-4ff260b21d0b000d","app-scaler-auto-scaler-9c09a3e6f241c57","app-scaler-egress-lmg","app-scaler-auto-scaler-11f65c4f7140d69c"]
I0724 13:59:18.554241       1 event.go:307] "Event occurred" object="traefik/traefik" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
I0724 13:59:18.561622       1 shared_informer.go:318] Caches are synced for route
I0724 13:59:21.572149       1 load_balancer.go:712] "update service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=80 loadBalancerID=1290988
I0724 13:59:22.368457       1 load_balancer.go:712] "update service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=443 loadBalancerID=1290988
I0724 13:59:23.698020       1 load_balancers.go:159] "reload HC Load Balancer" op="hcloud/loadBalancers.EnsureLoadBalancer" loadBalancerID=1290988
I0724 13:59:24.008215       1 event.go:307] "Event occurred" object="traefik/traefik" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"
I0724 13:59:35.211684       1 route_controller.go:216] action for Node "app-scaler-control-plane-fsn1-cqm" with CIDR "10.42.0.0/24": "keep"
I0724 13:59:35.211718       1 route_controller.go:216] action for Node "app-scaler-egress-lmg" with CIDR "10.42.1.0/24": "keep"
I0724 13:59:35.211742       1 route_controller.go:216] action for Node "app-scaler-auto-scaler-11f65c4f7140d69c" with CIDR "10.42.24.0/24": "keep"
I0724 13:59:35.211751       1 route_controller.go:216] action for Node "app-scaler-auto-scaler-136f9ac7070f0914" with CIDR "10.42.8.0/24": "keep"
I0724 13:59:35.211757       1 route_controller.go:216] action for Node "app-scaler-auto-scaler-2402a18da250bf34" with CIDR "10.42.9.0/24": "keep"
I0724 13:59:35.211765       1 route_controller.go:216] action for Node "app-scaler-auto-scaler-4ff260b21d0b000d" with CIDR "10.42.25.0/24": "keep"
I0724 13:59:35.211771       1 route_controller.go:216] action for Node "app-scaler-auto-scaler-9c09a3e6f241c57" with CIDR "10.42.7.0/24": "keep"
I0724 13:59:52.069466       1 route_controller.go:216] action for Node "app-scaler-auto-scaler-136f9ac7070f0914" with CIDR "10.42.8.0/24": "keep"
I0724 13:59:52.069510       1 route_controller.go:216] action for Node "app-scaler-auto-scaler-2402a18da250bf34" with CIDR "10.42.9.0/24": "keep"
I0724 13:59:52.069524       1 route_controller.go:216] action for Node "app-scaler-auto-scaler-4ff260b21d0b000d" with CIDR "10.42.25.0/24": "keep"
I0724 13:59:52.069536       1 route_controller.go:216] action for Node "app-scaler-auto-scaler-9c09a3e6f241c57" with CIDR "10.42.7.0/24": "keep"
I0724 13:59:52.069548       1 route_controller.go:216] action for Node "app-scaler-control-plane-fsn1-cqm" with CIDR "10.42.0.0/24": "keep"
I0724 13:59:52.069730       1 route_controller.go:216] action for Node "app-scaler-egress-lmg" with CIDR "10.42.1.0/24": "keep"

### Kube.tf file

```terraform
locals {
  # First and foremost set your Hetzner API token here. It can be found in your Project > Security > API Token (Read & Write is required).  
  hcloud_token = "***********"
  cluster_ipv4_cidr = "172.17.0.0/24"
}

module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  version = "v2.3.1"
  hcloud_token = local.hcloud_token
  source = "kube-hetzner/kube-hetzner/hcloud"
  ssh_public_key = file("*************")
  ssh_private_key = file(""*************")
  network_region = "eu-central"
  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cpx11",  # change to cx11 for new cluster
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]
  agent_nodepools = [
    {
      name        = "agent-middle",
      server_type = "cx31",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 0
    },
    {
      name        = "agent-large",
      server_type = "cx51",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 0
    },    
    {
      name        = "agent-middle-large",
      server_type = "cx41",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 0
    },        
    {
      name        = "egress",
      server_type = "cpx11",
      location    = "fsn1",
      labels = [
        "node.kubernetes.io/role=egress"
      ],
      taints = [
        "node.kubernetes.io/role=egress:NoSchedule"
      ],
      floating_ip = true
      count = 1
      },
  ]
  extra_firewall_rules = [
    {
      description     = "For outgoing."
      direction       = "out"
      protocol        = "tcp"
      port            = "any"
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    }
  ]
  network_ipv4_cidr = "172.16.0.0/16"
  cluster_ipv4_cidr = "172.17.0.0/24"
  automatically_upgrade_k3s = false
  automatically_upgrade_os = false
  cni_plugin = "cilium"
  enable_cert_manager= "true"
  cluster_name = "*******"
  allow_scheduling_on_control_plane = false
  autoscaler_nodepools = [
    {
      name        = "auto-scaler"
      server_type = "cx41"
      location    = "fsn1"
      min_nodes   = 1
      max_nodes   = 10
    }
  ]
  cilium_values = <<EOT
ipam:
  operator:
    mode: kubernetes
kubeProxyReplacement: strict
l7Proxy: "false"
bpf:
  masquerade: "true"
egressGateway:
  enabled: "true" 
  EOT
}

provider "hcloud" {
  token = local.hcloud_token
}

terraform {
  required_version = ">= 1.3.3"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.41.0"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}
```

### Platform

Linux

**Comment by M4t7e** [comment]
Hi @zypriafl, please have a look at https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/902. If this is merged, you should be able to change the cluster CIDR with your current configuration. Currently this would only work if you leave the cilium config (`cilium_values`) untouched and not overwrite it in your kube.tf. Then cilium takes care about the pod CIDR assignment and ignores K3s IPAM (K3s uses by default `10.42.0.0/16` -> https://docs.k3s.io/cli/server#networking) entirely. See also my comments below the referenced [PR](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/902), if you are interested in more details.

PS: Your network for `cluster_ipv4_cidr` is pretty small. Normally you should have a /24 network for a single pod network per node and not just a single /24 for all of them. Btw, it is also separated from the network CIDR, which is highly recommended to avoid. This can lead to routing problems if you would go to native pod routing setup in future. See also here:
```
  # If you must change the network CIDR you can do so below, but it is highly advised against.
  # network_ipv4_cidr = "10.0.0.0/8"

  # If you must change the cluster CIDR you can do so below, but it is highly advised against.
  # Cluster CIDR must be a part of the network CIDR!
  # cluster_ipv4_cidr = "10.42.0.0/16"
```

**Comment by zypriafl** [comment]
@M4t7e Thanks for your help here.
