### ISSUE TITLE
[Feature Request]: Using only private network

### ISSUE THREAD

**Issue by ceyhunn** [kube-hetzner/terraform-hcloud-kube-hetzner#914]
### Description

Hi,

It would be nice to use only private network (including servers, cp load balancer) with router (for internet access) and wireguard app server (for vpn access) for creating k3s clusters.

**Comment by mysticaltech** [comment]
@ceyhunn Thanks for your suggestion! Private network is already possible, you can close all the incoming ports, please search for "firewall" in kube.tf.example. Other solutions have been discussed in the part but it's not practical to implement in this project directly. However you can add it yourself on the side, as this project can be a module that integrates in a greater terraform project.

**Comment by ceyhunn** [comment]
Hi @mysticaltech , 
thank you for the answer, but hetzner firewall is applied to servers, not load balancers, hetzner load balancers can't be safe if public ip of it is enabled.

**Comment by mysticaltech** [comment]
@ceyhunn How can the LB be reached if it doesn't have a public IP! 😅 And that's up to Hetzner really, they ensure the security of it.

**Comment by M4t7e** [comment]
I think the only way would be routing from somewhere to the internal network via VPN or something similar. Some kind of internal-only app maybe. The use case should be solved with #917 and #918.

**Comment by ceyhunn** [comment]
> I think the only way would be routing from somewhere to the internal network via VPN or something similar. Some kind of internal-only app maybe. The use case should be solved with #917 and #918.

Yes, that is I want. I already said about that. 

> @ceyhunn How can the LB be reached if it doesn't have a public IP! sweat_smile And that's up to Hetzner really, they ensure the security of it.

Not correct, I think, control plane load balancer and k3s servers have to be private and access to them through private network by vpn, also not need to set additional firewall rules and pay additional money for the servers' public ip.  Steps I can share with you:
1. Create wireguard vpn server (with public ip enabled)
2. Create router server in order to give internet access for servers (with public ip enabled).
3. Create private network for servers 
4. And eventually steps that creating a k3s cluster.

**Comment by ceyhunn** [comment]
Hi @M4t7e ,
Can you please add option to disable public ip of servers, and connect to servers with ssh via private ip, which created by private network.

**Comment by mysticaltech** [comment]
@ceyhunn If you close the ssh port, the servers are basically inaccessible from the outside world. No need to disable the public interface, and this is not something we are considering doing right now.
