### ISSUE TITLE
[Bug]: Cannot update etcd_s3_backup config

### ISSUE THREAD

**Issue by Silvest89** [kube-hetzner/terraform-hcloud-kube-hetzner#920]
### Description
So I am switching to another S3 for backup, however changing it doesn't trigger any changes.
Updating/changing the etcd s3 backup doesn't do anything.
Doing terraform plan/apply just shows that there are no changes.

### Kube.tf file

```terraform
.
```

### Platform

Linux

**Comment by mysticaltech** [comment]
@Silvest89 This is related to #850. We will implemented ASAP, however PR welcome if you want to give it a shot. 

@kube-hetzner/core FYI.
