### ISSUE TITLE
[Bug]: Terraform destroy loops forever deleting network 

### ISSUE THREAD

**Issue by kerlexov** [kube-hetzner/terraform-hcloud-kube-hetzner#962]
### Description

Deleting resource `module.kube-hetzner.hcloud_network_subnet.agent[0]`  is stuck because network has attached loadbalancer which needs to be deleted first.

### Kube.tf file

```terraform
locals {
  hcloud_token = "xxxxxxxxxxx"
}

module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token

  source = "kube-hetzner/kube-hetzner/hcloud"

  
  ssh_public_key = file("~/.ssh/id_ed25519.pub")
  ssh_private_key = file("~/.ssh/id_ed25519")

  network_region = "eu-central" 


  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cpx11",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1

      # Enable automatic backups via Hetzner (default: false)
      # backups = true
    },
    {
      name        = "control-plane-nbg1",
      server_type = "cpx11",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1

      # Enable automatic backups via Hetzner (default: false)
      # backups = true
    },
    {
      name        = "control-plane-hel1",
      server_type = "cpx11",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1

      # Enable automatic backups via Hetzner (default: false)
      # backups = true
    }
  ]

  agent_nodepools = [
    {
      name        = "agent-small",
      server_type = "cpx11",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1

      # Enable automatic backups via Hetzner (default: false)
      # backups = true
    },
    {
      name        = "agent-large",
      server_type = "cpx21",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1

      # Enable automatic backups via Hetzner (default: false)
      # backups = true
    },
    {
      name        = "storage",
      server_type = "cpx21",
      location    = "nbg1",
      # Fully optional, just a demo.
      labels      = [
        "node.kubernetes.io/server-usage=storage"
      ],
      taints      = [],
      count       = 1
    },
    {
      name        = "egress",
      server_type = "cpx11",
      location    = "nbg1",
      labels = [
        "node.kubernetes.io/role=egress"
      ],
      taints = [
        "node.kubernetes.io/role=egress:NoSchedule"
      ],
      floating_ip = true
      count = 1
    },
    # Arm based nodes, currently available only in FSN location
    {
      name        = "agent-arm-small",
      server_type = "cax11",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]


  load_balancer_type     = "lb11"
  load_balancer_location = "nbg1"

}

provider "hcloud" {
  token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
}

terraform {
  required_version = ">= 1.4.0"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.41.0"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}

variable "hcloud_token" {
  sensitive = true
  default   = ""
}
```

### Screenshots

module.kube-hetzner.null_resource.agents["0-1-agent"]: Destroying... [id=4378546449057821101]
module.kube-hetzner.null_resource.agents["0-0-agent"]: Destroying... [id=2245253304593820113]
module.kube-hetzner.local_file.kustomization_backup[0]: Destroying... [id=3c6a262b418d2c7b0922601f93c95bcaf7af645e]
module.kube-hetzner.local_sensitive_file.kubeconfig[0]: Destroying... [id=1204d911ee3d6c1cf4b2780e0ad365d6480e1cb3]
module.kube-hetzner.null_resource.agents["0-1-agent"]: Destruction complete after 0s
module.kube-hetzner.null_resource.kustomization: Destroying... [id=1176689441261318891]
module.kube-hetzner.null_resource.agents["0-0-agent"]: Destruction complete after 0s
module.kube-hetzner.local_sensitive_file.kubeconfig[0]: Destruction complete after 0s
module.kube-hetzner.null_resource.kustomization: Destruction complete after 0s
module.kube-hetzner.local_file.kustomization_backup[0]: Destruction complete after 0s
module.kube-hetzner.null_resource.control_planes["0-0-control-plane-nbg1"]: Destroying... [id=8323284109425333128]
module.kube-hetzner.module.agents["0-1-agent"].hcloud_server_network.server: Destroying... [id=36789921-3314274]
module.kube-hetzner.module.agents["0-1-agent"].null_resource.registries: Destroying... [id=9131590256984552541]
module.kube-hetzner.module.agents["0-0-agent"].null_resource.registries: Destroying... [id=6037809664669556006]
module.kube-hetzner.module.agents["0-0-agent"].hcloud_server_network.server: Destroying... [id=36789918-3314274]
module.kube-hetzner.random_password.rancher_bootstrap[0]: Destroying... [id=none]
module.kube-hetzner.module.agents["0-0-agent"].null_resource.registries: Destruction complete after 0s
module.kube-hetzner.null_resource.control_planes["0-0-control-plane-nbg1"]: Destruction complete after 0s
module.kube-hetzner.module.agents["0-1-agent"].null_resource.registries: Destruction complete after 0s
module.kube-hetzner.random_password.rancher_bootstrap[0]: Destruction complete after 0s
module.kube-hetzner.null_resource.first_control_plane: Destroying... [id=3657543758649067362]
module.kube-hetzner.null_resource.first_control_plane: Destruction complete after 0s
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].null_resource.registries: Destroying... [id=5907814829418454506]
module.kube-hetzner.random_password.k3s_token: Destroying... [id=none]
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].null_resource.registries: Destruction complete after 0s
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].hcloud_server_network.server: Destroying... [id=36789912-3314274]
module.kube-hetzner.random_password.k3s_token: Destruction complete after 0s
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].hcloud_server_network.server: Destruction complete after 3s
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].hcloud_server.server: Destroying... [id=36789912]
module.kube-hetzner.module.agents["0-1-agent"].hcloud_server_network.server: Destruction complete after 3s
module.kube-hetzner.module.agents["0-1-agent"].hcloud_server.server: Destroying... [id=36789921]
module.kube-hetzner.module.agents["0-0-agent"].hcloud_server_network.server: Destruction complete after 3s
module.kube-hetzner.module.agents["0-0-agent"].hcloud_server.server: Destroying... [id=36789918]
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].hcloud_server.server: Destruction complete after 7s
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].random_string.server: Destroying... [id=gyj]
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].random_string.identity_file: Destroying... [id=j4b1lef9sfvdblkkx1gd]
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].random_string.server: Destruction complete after 0s
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].random_string.identity_file: Destruction complete after 0s
module.kube-hetzner.hcloud_network_subnet.control_plane[0]: Destroying... [id=3314274-10.255.0.0/16]
module.kube-hetzner.hcloud_placement_group.control_plane[0]: Destroying... [id=198981]
module.kube-hetzner.hcloud_placement_group.control_plane[0]: Destruction complete after 1s
module.kube-hetzner.module.agents["0-1-agent"].hcloud_server.server: Destruction complete after 8s
module.kube-hetzner.module.agents["0-1-agent"].random_string.server: Destroying... [id=gxc]
module.kube-hetzner.module.agents["0-1-agent"].random_string.identity_file: Destroying... [id=nq7yga54snlzmz6fd4xp]
module.kube-hetzner.module.agents["0-1-agent"].random_string.server: Destruction complete after 0s
module.kube-hetzner.module.agents["0-1-agent"].random_string.identity_file: Destruction complete after 0s
module.kube-hetzner.hcloud_network_subnet.control_plane[0]: Destruction complete after 2s
module.kube-hetzner.module.agents["0-0-agent"].hcloud_server.server: Destruction complete after 9s
module.kube-hetzner.hcloud_ssh_key.k3s[0]: Destroying... [id=14970056]
module.kube-hetzner.module.agents["0-0-agent"].random_string.identity_file: Destroying... [id=3vu9lkufr5vrdnf5nr0s]
module.kube-hetzner.module.agents["0-0-agent"].random_string.server: Destroying... [id=yud]
module.kube-hetzner.hcloud_firewall.k3s: Destroying... [id=1043519]
module.kube-hetzner.module.agents["0-0-agent"].random_string.server: Destruction complete after 0s
module.kube-hetzner.module.agents["0-0-agent"].random_string.identity_file: Destruction complete after 0s
module.kube-hetzner.hcloud_network_subnet.agent[0]: Destroying... [id=3314274-10.0.0.0/16]
module.kube-hetzner.hcloud_placement_group.agent[0]: Destroying... [id=198982]
module.kube-hetzner.hcloud_ssh_key.k3s[0]: Destruction complete after 0s
module.kube-hetzner.hcloud_placement_group.agent[0]: Destruction complete after 0s
module.kube-hetzner.hcloud_firewall.k3s: Destruction complete after 0s
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 10s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 20s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 30s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 40s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 50s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 1m0s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 1m10s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 1m20s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 1m30s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 1m40s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 1m50s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 2m0s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 2m10s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 2m20s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 2m30s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 2m40s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 2m50s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 3m0s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 3m10s elapsed]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Still destroying... [id=3314274-10.0.0.0/16, 3m20s elapsed]

### Platform

Linux

**Comment by mysticaltech** [comment]
@kerlexov You will get stuck during destroy this is expected, and we cannot do anything about this because the lb is not deployed by terraform but by the ingress controller. However, we provide a `cleanupkh` script to execute in another tab when it starts hanging. So to destroy you will need to execute this script, or manually deleted the lb and autoscaled nodes via hcloud cli or the ui, but best just use the script, please see the readme.
