### ISSUE TITLE
[Feature Request]: Install mtr by default on the nodes

### ISSUE THREAD

**Issue by schlichtanders** [kube-hetzner/terraform-hcloud-kube-hetzner#971]
### Description

Hi there,

I am in contact with hetzner for some networking problems I experience. Hetzner support asks me to run the network tool `mtr` from within a node.

I now installed it using 
```bash
zypper refresh
transactional-update shell
zypper install mtr
exit
reboot
```

I guess it would be great if such recommended tooling is included by default.

**Comment by mysticaltech** [comment]
@M4t7e It doesn't hurt having these useful tools on the OS. Please feel free to add them 🙏

**Comment by mysticaltech** [comment]
@M4t7e  FYI also added tcpdump, it's in v2.7.2.

**Comment by M4t7e** [comment]
@mysticaltech Thanks!
