### ISSUE TITLE
[Feature Request]: Able to disable loadbalancer (Both hetzner and klipperlb)

### ISSUE THREAD

**Issue by Silvest89** [kube-hetzner/terraform-hcloud-kube-hetzner#991]
### Description

As hetzner LB does not support UDP. I would like to be able to setup my own LB infra using nginx as a proxy.
I need UDP for Traefik http3/quic

**Comment by mysticaltech** [comment]
@Silvest89 In your kube.tf, just set `ingress_controller` to none and it should be disabled.
